# Generated by Django 5.0.10 on 2024-12-30 20:08

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('kind', models.CharField(choices=[('full', 'Web and Email notification'), ('web', 'Web notification'), ('email', 'Email notification')], default='full', max_length=10)),
                ('content', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Message Template',
                'verbose_name_plural': 'Message Templates',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('emails', models.JSONField(blank=True, default=list)),
                ('kind', models.CharField(max_length=100, verbose_name='Type')),
                ('level', models.PositiveSmallIntegerField(choices=[(0, 'Information'), (1, 'Important'), (2, 'Urgent')], default=0)),
                ('send_on', models.DateTimeField(null=True)),
                ('state', models.PositiveSmallIntegerField(choices=[(0, 'Queued'), (1, 'Sent'), (2, 'Read'), (3, 'Acknowledged'), (4, 'Failed')], default=0)),
                ('data', models.TextField(blank=True, verbose_name='Message')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
