# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-10 13:40


import django.utils.timezone
import model_utils.fields
from django.db import migrations, models

import misc.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False,
                                                                verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False,
                                                                      verbose_name='modified')),
                ('emails', misc.fields.JSONField(blank=True, default=[])),
                ('kind', models.CharField(max_length=100)),
                ('level',
                 models.PositiveSmallIntegerField(choices=[(0, 'Information'), (1, 'Important'), (2, 'Urgent')],
                                                  default=0)),
                ('send_on', models.DateTimeField(null=True)),
                ('state', models.PositiveSmallIntegerField(
                    choices=[(0, 'Queued'), (1, 'Sent'), (2, 'Read'), (3, 'Acknowledged')], default=0)),
                ('data', models.TextField(blank=True, verbose_name=b'Message')),
                ('details', misc.fields.JSONField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
