# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-23 18:36


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('notifier', '0002_notification_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(max_length=100, verbose_name=b'Type'),
        ),
    ]
