# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-07 17:59


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('notifier', '0003_auto_20170123_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='state',
            field=models.PositiveSmallIntegerField(
                choices=[(0, 'Queued'), (1, 'Sent'), (2, 'Read'), (3, 'Acknowledged'), (4, 'Failed')], default=0),
        ),
    ]
