# Generated by Django 5.0.9 on 2024-11-16 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0006_alter_notification_details_alter_notification_emails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='details',
        ),
    ]
