# Generated by Django 5.0.9 on 2024-11-22 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0008_messagetemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetemplate',
            name='kind',
            field=models.CharField(choices=[('full', 'Web and Email notification'), ('web', 'Web notification'), ('email', 'Email notification')], default='full', max_length=10),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
