# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-10 13:40


import django.utils.timezone
import model_utils.fields
from django.db import migrations, models

import misc.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DynEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', misc.fields.JSONField(blank=True, default={}, editable=False, null=True)),
                ('is_complete', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False,
                                                                verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False,
                                                                      verbose_name='modified')),
                ('pages', misc.fields.JSONField(blank=True, default=b'[{"fields": [], "name": "Page 1"}]', null=True)),
                ('actions', misc.fields.JSONField(blank=True, default=b'[["submit", "Submit"]]', null=True)),
            ],
            options={
                'ordering': ['-modified'],
            },
        ),
        migrations.CreateModel(
            name='FormType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False,
                                                                verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False,
                                                                      verbose_name='modified')),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('spec', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+',
                                           to='dynforms.FormSpec', verbose_name=b'Active Layout')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='formspec',
            name='form_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs',
                                    to='dynforms.FormType'),
        ),
        migrations.AddField(
            model_name='dynentry',
            name='spec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynforms.FormSpec'),
        ),
    ]
