# Generated by Django 3.2.4 on 2024-11-13 02:30

from django.db import migrations, models
import django.db.models.deletion
import misc.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dynforms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formspec',
            name='actions',
            field=misc.fields.JSONField(blank=True, default='[["submit", "Submit"]]', null=True),
        ),
        migrations.AlterField(
            model_name='formspec',
            name='pages',
            field=misc.fields.JSONField(blank=True, default='[{"name": "Page 1", "fields": []}]', null=True),
        ),
        migrations.AlterField(
            model_name='formtype',
            name='spec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dynforms.formspec', verbose_name='Active Layout'),
        ),
    ]
