# Generated by Django 5.0.9 on 2024-11-14 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynforms', '0002_auto_20241112_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynentry',
            name='details',
            field=models.JSONField(blank=True, default=dict, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='formspec',
            name='actions',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='formspec',
            name='pages',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
