# Generated by Django 5.0.9 on 2024-11-21 03:24

import django.utils.timezone
import model_utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynforms', '0003_alter_dynentry_details_alter_formspec_actions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynentry',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='dynentry',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
    ]
