# Generated by Django 5.0.9 on 2024-11-30 06:49

import django.db.models.deletion
from django.db import migrations, models


def transfer_formspec_data(apps, schema_editor):
    FormSpec = apps.get_model("dynforms", "FormSpec")
    db_alias = schema_editor.connection.alias
    for spec in FormSpec.objects.using(db_alias).all():
        spec.form_type.pages = spec.pages
        spec.form_type.actions = spec.actions
        spec.form_type.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dynforms', '0004_dynentry_created_dynentry_modified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formtype',
            options={'ordering': ['-modified']},
        ),
        migrations.AddField(
            model_name='dynentry',
            name='form_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dynforms.formtype'),
        ),
        migrations.AddField(
            model_name='formtype',
            name='actions',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='formtype',
            name='pages',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.RunPython(transfer_formspec_data),
    ]
