# Generated by Django 5.0.9 on 2024-11-30 20:23

import dynforms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynforms', '0005_alter_formtype_options_dynentry_form_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynentry',
            name='spec',
        ),
        migrations.RemoveField(
            model_name='formspec',
            name='form_type',
        ),
        migrations.RemoveField(
            model_name='formtype',
            name='spec',
        ),
        migrations.AlterField(
            model_name='formtype',
            name='actions',
            field=models.JSONField(blank=True, default=dynforms.models.default_actions, null=True),
        ),
        migrations.AlterField(
            model_name='formtype',
            name='pages',
            field=models.JSONField(blank=True, default=dynforms.models.default_pages, null=True),
        ),
    ]
