# Generated by Django 5.0.9 on 2024-11-30 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynforms', '0006_remove_dynentry_spec_remove_formspec_form_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormSpec',
        ),
    ]
