# Generated by Django 5.0.10 on 2024-12-30 20:08

import django.db.models.deletion
import django.utils.timezone
import misc.fields
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beamlines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('complete', 'Completed')], default='draft', max_length=20)),
                ('procedure', models.TextField(blank=True, null=True)),
                ('justification', models.TextField(blank=True, null=True)),
                ('shift_request', models.IntegerField(default=0, verbose_name='Shifts Requested')),
                ('good_dates', models.TextField(blank=True, null=True)),
                ('poor_dates', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BeamTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='start')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='end')),
                ('cancelled', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='start')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='end')),
                ('details', models.JSONField(blank=True, default=dict, editable=False, null=True)),
            ],
            options={
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('procedure', models.TextField(verbose_name='Sample Handling Procedure')),
                ('waste', models.JSONField(default=list, verbose_name='Waste Generation')),
                ('disposal', models.TextField(blank=True, verbose_name='Waste Disposal')),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=20, verbose_name='Status')),
                ('equipment', models.JSONField(default=list, verbose_name='Equipment')),
                ('permissions', models.JSONField(default=dict, verbose_name='Permission Requirements')),
                ('risk_level', models.IntegerField(choices=[(0, 'Not Reviewed'), (1, 'Low Risk'), (2, 'Moderate Risk'), (3, 'High Risk'), (4, 'Unacceptable')], default=0)),
            ],
            options={
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('user', 'General Access'), ('staff', 'Staff Access'), ('maintenance', 'Maintenance/Commissioning'), ('purchased', 'Purchased Access'), ('beamteam', 'Beam Team'), ('education', 'Education/Outreach')], default='user', max_length=20, verbose_name='Type')),
                ('title', models.TextField(null=True)),
                ('pending_team', misc.fields.StringListField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict, editable=False, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20, verbose_name='Status')),
                ('quantity', models.CharField(blank=True, max_length=50)),
                ('expiry', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('shifts', models.PositiveIntegerField(default=0)),
                ('kind', models.CharField(choices=[('user', 'General Access'), ('staff', 'Staff Access'), ('maintenance', 'Maintenance/Commissioning'), ('purchased', 'Purchased Access'), ('beamteam', 'Beam Team'), ('education', 'Education/Outreach')], max_length=20, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='start')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='end')),
                ('state', models.CharField(choices=[('ready', 'Ready'), ('live', 'Active'), ('complete', 'Complete'), ('cancelled', 'Cancelled'), ('terminated', 'Terminated')], default='ready', max_length=15)),
                ('kind', models.CharField(choices=[('onsite', 'On-Site'), ('remote', 'Remote'), ('mailin', 'Mail-In')], default='onsite', max_length=15, verbose_name='Session Type')),
                ('details', models.JSONField(blank=True, default=dict, editable=False, null=True)),
            ],
            options={
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='ShiftRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('progress', 'In Progress'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('comments', models.TextField(blank=True, null=True)),
                ('justification', models.TextField(blank=True, null=True)),
                ('shift_request', models.IntegerField(default=0)),
                ('good_dates', models.TextField(blank=True, null=True)),
                ('poor_dates', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('procedure', models.TextField(blank=True, null=True)),
                ('justification', models.TextField(blank=True, null=True)),
                ('shift_request', models.IntegerField(default=0)),
                ('shifts', models.IntegerField(default=0)),
                ('score', models.FloatField(default=0.0, verbose_name='Merit Score')),
                ('scores', models.JSONField(blank=True, default=dict, null=True)),
                ('declined', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True, null=True)),
                ('discretionary', models.BooleanField(default=False)),
                ('beamline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='beamlines.facility')),
            ],
        ),
    ]
