# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-10 13:40


import django.utils.timezone
import model_utils.fields
from django.db import migrations, models

import misc.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False,
                                                                verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False,
                                                                      verbose_name='modified')),
                ('procedure', models.TextField(blank=True, null=True)),
                ('justification', models.TextField(blank=True, null=True)),
                ('shift_request', models.IntegerField(default=0)),
                ('shifts', models.IntegerField(default=0)),
                ('score_merit', models.FloatField(default=0.0, verbose_name='Merit Score')),
                ('score_suitability', models.FloatField(default=0.0, verbose_name='Suitability Score')),
                ('score_capability', models.FloatField(default=0.0, verbose_name='Capability Score')),
                ('score_technical', models.FloatField(default=0.0, verbose_name='Technical Score')),
                ('declined', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True, null=True)),
                ('discretionary', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AllocationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False,
                                                                verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False,
                                                                      verbose_name='modified')),
                ('state',
                 models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('complete', 'Completed')],
                                  default='draft', max_length=20)),
                ('procedure', models.TextField(blank=True, null=True)),
                ('justification', models.TextField(blank=True, null=True)),
                ('shift_request', models.IntegerField(default=0, verbose_name='Shifts Requested')),
                ('good_dates', models.TextField(blank=True, null=True)),
                ('poor_dates', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BeamTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False,
                                                                verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False,
                                                                      verbose_name='modified')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='start')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='end')),
                ('cancelled', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True, default=b'', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False,
                                                                verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False,
                                                                      verbose_name='modified')),
                ('procedure', models.TextField(verbose_name='Sample Handling Procedure')),
                ('waste', misc.fields.JSONField(default=[], verbose_name='Waste Generation')),
                ('disposal', models.TextField(blank=True, verbose_name='Waste Disposal')),
                ('state',
                 models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')],
                                  default='pending', max_length=20)),
                ('equipment', misc.fields.JSONField(default=[], verbose_name='Equipment')),
                ('permissions', misc.fields.JSONField(default={}, verbose_name='Permission Requirements')),
                ('risk_level', models.IntegerField(
                    choices=[(0, 'Unknown'), (1, 'Low Risk'), (2, 'Medium Risk'), (3, 'High Risk'),
                             (4, 'Unacceptable Risk')], default=0)),
            ],
            options={
                'get_latest_by': 'modified',
            },
        ),
    ]
