# Generated by Django 5.0.9 on 2024-11-30 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beamlines', '0001_initial'),
        ('projects', '0001_initial'),
        ('proposals', '0001_initial'),
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='proposals.reviewcycle'),
        ),
        migrations.AddField(
            model_name='allocationrequest',
            name='beamline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_requests', to='beamlines.facility'),
        ),
        migrations.AddField(
            model_name='allocationrequest',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_requests', to='proposals.reviewcycle'),
        ),
        migrations.AddField(
            model_name='allocationrequest',
            name='tags',
            field=models.ManyToManyField(related_name='allocation_requests', to='beamlines.facilitytag', verbose_name='Scheduling Tags'),
        ),
        migrations.AddField(
            model_name='beamtime',
            name='beamline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beamtimes', to='beamlines.facility'),
        ),
        migrations.AddField(
            model_name='beamtime',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.schedule'),
        ),
        migrations.AddField(
            model_name='beamtime',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='beamtimes', to='beamlines.facilitytag'),
        ),
        migrations.AddField(
            model_name='labsession',
            name='equipment',
            field=models.ManyToManyField(blank=True, related_name='lab_sessions', to='beamlines.ancillary'),
        ),
        migrations.AddField(
            model_name='labsession',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_sessions', to='beamlines.lab'),
        ),
    ]
