# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-10 13:40


import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('samples', '0001_initial'),
        ('projects', '0002_materialreview_project_projectsample_reservation_session_shiftrequest'),
        ('proposals', '0001_initial'),
        ('beamlines', '0002_auto_20170110_0740'),
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='spokesperson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='session',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='session',
            name='team',
            field=models.ManyToManyField(related_name='sessions', to=settings.AUTH_USER_MODEL,
                                         verbose_name='Team Members'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='beamline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations',
                                    to='beamlines.Facility'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations',
                                    to='proposals.ReviewCycle'),
        ),
        migrations.AddField(
            model_name='projectsample',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_samples',
                                    to='projects.Material'),
        ),
        migrations.AddField(
            model_name='projectsample',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage',
                                    to='samples.Sample'),
        ),
        migrations.AddField(
            model_name='project',
            name='beamlines',
            field=models.ManyToManyField(related_name='projects', through='projects.Allocation',
                                         to='beamlines.Facility'),
        ),
        migrations.AddField(
            model_name='project',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects',
                                    to='proposals.ReviewCycle', verbose_name='First Cycle'),
        ),
        migrations.AddField(
            model_name='project',
            name='proposal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project',
                                    to='proposals.Proposal'),
        ),
        migrations.AddField(
            model_name='project',
            name='spokesperson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+',
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='submissions',
            field=models.ManyToManyField(blank=True, related_name='project', to='proposals.Submission'),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='projects', to='beamlines.FacilityTag'),
        ),
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ManyToManyField(related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='techniques',
            field=models.ManyToManyField(blank=True, related_name='projects', to='proposals.ConfigItem'),
        ),
        migrations.AddField(
            model_name='materialreview',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews',
                                    to='projects.Material'),
        ),
        migrations.AddField(
            model_name='material',
            name='controls',
            field=models.ManyToManyField(blank=True, related_name='materials', to='samples.SafetyControl'),
        ),
        migrations.AddField(
            model_name='material',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials',
                                    to='projects.Project'),
        ),
        migrations.AddField(
            model_name='material',
            name='samples',
            field=models.ManyToManyField(blank=True, related_name='projects', through='projects.ProjectSample',
                                         to='samples.Sample'),
        ),
        migrations.AddField(
            model_name='beamtime',
            name='beamline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beamtimes',
                                    to='beamlines.Facility'),
        ),
        migrations.AddField(
            model_name='beamtime',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beamtimes',
                                    to='projects.Project'),
        ),
        migrations.AddField(
            model_name='beamtime',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Schedule'),
        ),
        migrations.AddField(
            model_name='beamtime',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='beamtimes', to='beamlines.FacilityTag'),
        ),
        migrations.AddField(
            model_name='allocationrequest',
            name='beamline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_requests',
                                    to='beamlines.Facility'),
        ),
        migrations.AddField(
            model_name='allocationrequest',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_requests',
                                    to='proposals.ReviewCycle'),
        ),
        migrations.AddField(
            model_name='allocationrequest',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_requests',
                                    to='projects.Project'),
        ),
        migrations.AddField(
            model_name='allocationrequest',
            name='tags',
            field=models.ManyToManyField(related_name='allocation_requests', to='beamlines.FacilityTag',
                                         verbose_name='Scheduling Tags'),
        ),
        migrations.AddField(
            model_name='allocation',
            name='beamline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations',
                                    to='beamlines.Facility'),
        ),
        migrations.AddField(
            model_name='allocation',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations',
                                    to='proposals.ReviewCycle'),
        ),
        migrations.AddField(
            model_name='allocation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations',
                                    to='projects.Project'),
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together=set([('beamline', 'cycle', 'kind')]),
        ),
        migrations.AlterUniqueTogether(
            name='projectsample',
            unique_together=set([('material', 'sample')]),
        ),
        migrations.AlterUniqueTogether(
            name='beamtime',
            unique_together=set([('project', 'beamline', 'start')]),
        ),
        migrations.AlterUniqueTogether(
            name='allocation',
            unique_together=set([('beamline', 'cycle', 'project')]),
        ),
    ]
