# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-10 14:23


from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0003_auto_20170110_0740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialreview',
            name='material',
        ),
        migrations.RemoveField(
            model_name='materialreview',
            name='review_ptr',
        ),
        migrations.DeleteModel(
            name='MaterialReview',
        ),
    ]
