# Generated by Django 5.0.9 on 2024-12-15 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allocation',
            old_name='score_merit',
            new_name='score',
        ),
    ]
