# Generated by Django 5.0.11 on 2025-05-24 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftrequest',
            name='shift_request',
            field=models.IntegerField(default=0, verbose_name='Shifts Requested'),
        ),
    ]
