# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-12 23:43


import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models

import misc.fields


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beamlines', '0004_auto_20170112_1743'),
        ('projects', '0004_auto_20170110_0823'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False,
                                                                verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False,
                                                                      verbose_name='modified')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='start')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='end')),
                ('state', models.CharField(choices=[('ready', 'Ready'), ('active', 'Active'), ('complete', 'Complete'),
                                                    ('cancelled', 'Cancelled')], default='ready', max_length=15)),
                ('details', misc.fields.JSONField(blank=True, default={}, editable=False, null=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_sessions',
                                          to='beamlines.Lab')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_sessions',
                                              to='projects.Project')),
                ('spokesperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+',
                                                   to=settings.AUTH_USER_MODEL)),
                ('team', models.ManyToManyField(related_name='lab_sessions', to=settings.AUTH_USER_MODEL,
                                                verbose_name='Team Members')),
            ],
            options={
                'get_latest_by': 'modified',
            },
        ),
    ]
