# Generated by Django 5.0.9 on 2024-12-15 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_rename_score_merit_allocation_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='scores',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
