# Generated by Django 5.0.9 on 2024-12-16 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_allocation_scores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocation',
            name='score_capability',
        ),
        migrations.RemoveField(
            model_name='allocation',
            name='score_suitability',
        ),
        migrations.RemoveField(
            model_name='allocation',
            name='score_technical',
        ),
    ]
