# Generated by Django 5.0.11 on 2025-06-20 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_beamtime_schedule'),
        ('scheduler', '0003_alter_mode_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beamtime',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='scheduler.schedule'),
        ),
    ]
