# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-17 15:32


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('beamlines', '0006_auto_20170117_0720'),
        ('projects', '0005_labsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='labsession',
            name='workspaces',
            field=models.ManyToManyField(related_name='lab_sessions', to='beamlines.LabWorkSpace'),
        ),
    ]
