# Generated by Django 5.0.9 on 2024-12-30 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_remove_allocation_score_capability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftrequest',
            name='state',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('progress', 'In Progress'), ('completed', 'Completed')], default='draft', max_length=20),
        ),
    ]
