# Generated by Django 5.2.3 on 2025-07-10 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_beamtime_schedule'),
        ('proposals', '0031_submission_pool'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pool',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='projects', to='proposals.accesspool'),
        ),
    ]
