# Generated by Django 5.2.3 on 2025-07-11 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_pool'),
        ('proposals', '0033_remove_submission_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='pool',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='reservations', to='proposals.accesspool'),
        ),
    ]
