# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-19 17:12


from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0008_labsession_equipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labsession',
            name='state',
        ),
    ]
