# Generated by Django 5.2.3 on 2025-07-11 00:52

from django.db import migrations


def initialize_pools(apps, schema_editor):
    Reservation = apps.get_model('projects', 'Reservation')
    AccessPool = apps.get_model('proposals', 'AccessPool')

    # initialize pools TYPES and update Reservations
    kind_field = Reservation._meta.get_field('kind')
    for code, name in kind_field.choices:
        pool = AccessPool.objects.filter(name=name).first()
        if pool:
            Reservation.objects.filter(kind=code).update(pool=pool)


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_reservation_pool'),
    ]

    operations = [
        migrations.RunPython(initialize_pools, reverse_code=migrations.RunPython.noop),
    ]
