# Generated by Django 5.2.3 on 2025-07-11 01:00

from django.db import migrations
from django.db.models import Min


def remove_duplicates(apps, schema_editor):
    Reservation = apps.get_model('projects', 'Reservation')

    distinct_ids = Reservation.objects.values(
        'beamline', 'cycle', 'pool'
    ).order_by('beamline', 'cycle', 'pool').annotate(min_pk=Min('pk')).distinct()

    Reservation.objects.exclude(
        pk__in=[item['min_pk'] for item in distinct_ids]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('beamlines', '0006_alter_usersupport_schedule'),
        ('projects', '0009_auto_20250710_1852'),
        ('proposals', '0033_remove_submission_kind'),
    ]

    operations = [
        migrations.RunPython(remove_duplicates, reverse_code=migrations.RunPython.noop),
    ]
