# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-23 18:36


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0009_remove_labsession_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='risk_level',
            field=models.IntegerField(
                choices=[(0, 'Not Reviewed'), (1, 'Low Risk'), (2, 'Medium Risk'), (3, 'High Risk'),
                         (4, 'Unacceptable Risk')], default=0),
        ),
    ]
