# Generated by Django 5.2.3 on 2025-07-11 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beamlines', '0006_alter_usersupport_schedule'),
        ('projects', '0010_remove_duplicate_reservations'),
        ('proposals', '0033_remove_submission_kind'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('beamline', 'cycle', 'pool')},
        ),
    ]
