# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-13 18:26


import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0010_auto_20170123_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='delegate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+',
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+',
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='material',
            name='risk_level',
            field=models.IntegerField(
                choices=[(0, 'Not Reviewed'), (1, 'Low Risk'), (2, 'Moderate Risk'), (3, 'High Risk'),
                         (4, 'Unacceptable')], default=0),
        ),
        migrations.AlterField(
            model_name='material',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')],
                                   default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='projectsample',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'),
                                            ('expired', 'Expired')], default='pending', max_length=20,
                                   verbose_name='Status'),
        ),
    ]
