# Generated by Django 5.2.3 on 2025-07-11 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_reservation_unique_together'),
        ('proposals', '0033_remove_submission_kind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='kind',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='pool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='proposals.accesspool'),
        ),
    ]
