# Generated by Django 5.2.3 on 2025-07-15 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_remove_reservation_kind_alter_reservation_pool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='kind',
        ),
    ]
