# Generated by Django 5.2.3 on 2025-07-16 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_remove_project_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='_code',
            field=models.SlugField(blank=True),
        ),
    ]
