# Generated by Django 5.2.3 on 2025-07-16 04:53

from django.db import migrations
from misc import utils


def create_codes(apps, schema_editor):
    Project = apps.get_model('projects', 'Project')

    # loop through and calculate the code for each project
    code_func = utils.get_code_generator('project')
    all_projects = Project.objects.all()
    for project in all_projects:
        project._code = code_func(project)
    Project.objects.bulk_update(all_projects, ['_code'])


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_project__code'),
    ]

    operations = [
        migrations.RunPython(create_codes, migrations.RunPython.noop),
    ]
