# Generated by Django 5.0.9 on 2024-11-14 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_alter_beamtime_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labsession',
            name='details',
            field=models.JSONField(blank=True, default=dict, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='equipment',
            field=models.JSONField(default=list, verbose_name='Equipment'),
        ),
        migrations.AlterField(
            model_name='material',
            name='permissions',
            field=models.JSONField(default=dict, verbose_name='Permission Requirements'),
        ),
        migrations.AlterField(
            model_name='material',
            name='waste',
            field=models.JSONField(default=list, verbose_name='Waste Generation'),
        ),
        migrations.AlterField(
            model_name='project',
            name='details',
            field=models.JSONField(blank=True, default=dict, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='details',
            field=models.JSONField(blank=True, default=dict, editable=False, null=True),
        ),
    ]
