# Generated by Django 5.0.9 on 2024-11-14 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_alter_labsession_details_alter_material_equipment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='delegate_username',
        ),
        migrations.RemoveField(
            model_name='project',
            name='leader_username',
        ),
    ]
