# Generated by Django 5.2.3 on 2025-07-16 13:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_alter_project_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='code',
            field=models.SlugField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.SlugField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
