# Generated by Django 5.2.3 on 2025-07-16 13:53

from django.db import migrations
from misc import utils


def generate_code(apps, schema_editor):
    Material = apps.get_model("projects", "Material")
    code_func = utils.get_code_generator("MATERIAL")
    all_materials = Material.objects.all()
    for row in all_materials:
        row.code = code_func(row)
    Material.objects.bulk_update(all_materials, ["code"])


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_material_code_alter_project_code'),
    ]

    operations = [
        migrations.RunPython(generate_code, migrations.RunPython.noop),
    ]
