# Generated by Django 5.2.3 on 2025-07-16 13:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_auto_20250716_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='code',
            field=models.SlugField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
