# Generated by Django 5.2.3 on 2025-07-19 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beamlines', '0006_alter_usersupport_schedule'),
        ('projects', '0020_auto_20250716_0753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allocationrequest',
            options={'verbose_name': 'Renewal Request'},
        ),
        migrations.AlterField(
            model_name='shiftrequest',
            name='allocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='projects.allocation'),
        ),
        migrations.AlterField(
            model_name='shiftrequest',
            name='tags',
            field=models.ManyToManyField(related_name='bookings', to='beamlines.facilitytag', verbose_name='Tags'),
        ),
    ]
