# Generated by Django 5.2.3 on 2025-07-19 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beamlines', '0006_alter_usersupport_schedule'),
        ('projects', '0021_alter_allocationrequest_options_and_more'),
        ('proposals', '0042_alter_proposal_code_alter_submission_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocationrequest',
            name='beamline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='beamlines.facility'),
        ),
        migrations.AlterField(
            model_name='allocationrequest',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='proposals.reviewcycle'),
        ),
        migrations.AlterField(
            model_name='allocationrequest',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='allocationrequest',
            name='tags',
            field=models.ManyToManyField(related_name='renewals', to='beamlines.facilitytag', verbose_name='Tags'),
        ),
    ]
