# Generated by Django 5.2.3 on 2025-07-20 00:21

from django.db import migrations
import json


def convert_date_lists(apps, schema_editor):
    ShiftRequest = apps.get_model("projects", "ShiftRequest")
    AllocationRequest = apps.get_model("projects", "AllocationRequest")

    # Convert date lists to JSON strings
    for model in [ShiftRequest, AllocationRequest]:
        req_list = model.objects.all()
        for req in req_list:
            req.good_dates = json.dumps(req.good_dates.split(",") if req.good_dates else [])
            req.poor_dates = json.dumps(req.poor_dates.split(",") if req.poor_dates else [])

        model.objects.bulk_update(req_list, ["good_dates", "poor_dates"])


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_alter_allocationrequest_beamline_and_more'),
    ]

    operations = [
        migrations.RunPython(convert_date_lists, migrations.RunPython.noop),
    ]
