# Generated by Django 5.2.3 on 2025-07-20 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_auto_20250719_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocationrequest',
            name='good_dates',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='allocationrequest',
            name='poor_dates',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='shiftrequest',
            name='good_dates',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='shiftrequest',
            name='poor_dates',
            field=models.JSONField(default=list),
        ),
    ]
