# Generated by Django 5.2.3 on 2025-07-20 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_alter_allocationrequest_good_dates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocationrequest',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
