# Generated by Django 5.2.6 on 2025-09-08 21:59

from django.db import migrations, models


def populate_roles(apps, schema_editor):
    Project = apps.get_model('projects', 'Project')
    db_alias = schema_editor.connection.alias
    to_update = Project.objects.using(db_alias).all()
    for item in to_update:
        item._pending_team = item.pending_team

    Project.objects.using(db_alias).bulk_update(to_update, ['_pending_team'])


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_allocationrequest_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='_pending_team',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(populate_roles, reverse_code=migrations.RunPython.noop),
    ]
