# Generated by Django 5.2.4 on 2025-09-08 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_project__pending_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='pending_team',
        ),
    ]
