# Generated by Django 5.2.4 on 2025-09-08 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_remove_project_pending_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='_pending_team',
            new_name='pending_team',
        ),
    ]
