# Generated by Django 5.0.9 on 2024-11-30 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('ran_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('never', 'Never Ran'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='never', max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
