# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-10 13:40


from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('ran_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(
                    choices=[(b'never', b'Never Ran'), (b'running', b'Running'), (b'success', b'Success'),
                             (b'failed', b'Failed')], default=b'never', max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
