# Generated by Django 5.2.3 on 2025-06-28 06:04

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isocron', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('keep_logs', models.IntegerField(default=10, help_text='Number of logs to keep in the log')),
                ('run_every', models.CharField(blank=True, help_text='ISO 8601 Duration', max_length=50, null=True)),
                ('run_at', models.JSONField(default=list, help_text='List of ISO 8601 Time strings to run at', null=True)),
                ('retry_after', models.CharField(blank=True, help_text='ISO 8601 Duration', max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Background Task',
                'verbose_name_plural': 'Background Tasks',
            },
        ),
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('message', models.TextField(blank=True, help_text='Log message', null=True)),
                ('state', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='failed', max_length=20)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='isocron.backgroundtask')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='JobLog',
        ),
    ]
