# Generated by Django 5.2.3 on 2025-06-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isocron', '0002_backgroundtask_tasklog_delete_joblog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundtask',
            name='run_at',
            field=models.CharField(help_text='ISO 8601 Time String', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='backgroundtask',
            name='run_every',
            field=models.CharField(blank=True, help_text='ISO 8601 Time or Duration String', max_length=50, null=True),
        ),
    ]
