# Generated by Django 5.2.4 on 2025-09-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isocron', '0003_alter_backgroundtask_run_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundtask',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
