# Generated by Django 5.2.4 on 2025-09-20 17:39

from django.db import migrations
from misc.functions import SplitPart


def add_task_labels(apps, schema_editor):
    BackgroundTask = apps.get_model('isocron', 'BackgroundTask')
    BackgroundTask.objects.all().update(label=SplitPart('name', ".", 2))


class Migration(migrations.Migration):

    dependencies = [
        ('isocron', '0004_backgroundtask_label'),
    ]

    operations = [
        migrations.RunPython(add_task_labels),
    ]
