# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-10 13:40


from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False,
                                                                verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False,
                                                                      verbose_name='modified')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='start')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='end')),
                ('cancelled', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True, default=b'', null=True)),
                ('kind', models.CharField(choices=[(b'N', 'Normal'), (b'NS', 'Special Beam'), (b'D', 'Development'),
                                                   (b'DS', 'Special Development'), (b'M', 'Maintenance'),
                                                   (b'X', 'Shutdown')], default=b'N', max_length=10,
                                          verbose_name='Type')),
            ],
        ),
        migrations.CreateModel(
            name='ModeTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False,
                                                                verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False,
                                                                      verbose_name='modified')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False,
                                                                verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False,
                                                                      verbose_name='modified')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('tentative', 'Tentative'), ('live', 'Live')],
                                           default='draft', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShiftConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False,
                                                                verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False,
                                                                      verbose_name='modified')),
                ('start', models.TimeField()),
                ('duration', models.IntegerField(default=8)),
                ('number', models.IntegerField(default=3)),
                ('names', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='schedule',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules',
                                    to='scheduler.ShiftConfig', verbose_name=b'Shift Configuration'),
        ),
        migrations.AddField(
            model_name='mode',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Schedule'),
        ),
        migrations.AddField(
            model_name='mode',
            name='tags',
            field=models.ManyToManyField(blank=True, to='scheduler.ModeTag'),
        ),
        migrations.AlterUniqueTogether(
            name='mode',
            unique_together=set([('schedule', 'start', 'end')]),
        ),
    ]
