# Generated by Django 3.2.4 on 2024-11-13 02:30

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='mode',
            managers=[
                ('timeframed', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='mode',
            name='comments',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='mode',
            name='kind',
            field=models.CharField(choices=[('N', 'Normal'), ('NS', 'Special Beam'), ('D', 'Development'), ('DS', 'Special Development'), ('M', 'Maintenance'), ('X', 'Shutdown')], default='N', max_length=10, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='scheduler.shiftconfig', verbose_name='Shift Configuration'),
        ),
    ]
