# Generated by Django 4.2.16 on 2024-11-14 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_auto_20241112_2030'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='mode',
            managers=[
            ],
        ),
    ]
