# Generated by Django 5.2.3 on 2025-07-05 21:16

from django.db import migrations


def populate_kind_fk(apps, schema_editor):
    Mode = apps.get_model('scheduler', 'Mode')
    ModeType = apps.get_model('scheduler', 'ModeType')

    # loop through Mode.TYPES and create ModeType instances
    kind_field = Mode._meta.get_field('kind')
    choices = kind_field.choices
    to_create = [
        ModeType(
            acronym=mode_type[0],
            name=mode_type[1],
            description=mode_type[1],
        )
        for mode_type in choices
    ]
    ModeType.objects.bulk_create(to_create, ignore_conflicts=True)
    type_map = ModeType.objects.in_bulk(field_name='acronym')

    # Update existing Mode objects
    modes_to_update = list(Mode.objects.all())
    first_type = next(iter(type_map.values()))
    for mode in modes_to_update:
        mode.kind_fk = type_map.get(mode.kind, first_type)

    # Apply the updates in bulk
    Mode.objects.bulk_update(modes_to_update, ['kind_fk'], batch_size=1000)


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_modetype_mode_kind_fk'),
    ]

    operations = [
        migrations.RunPython(populate_kind_fk, reverse_code=migrations.RunPython.noop),
    ]
