# Generated by Django 5.2.3 on 2025-07-05 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_auto_20250705_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mode',
            name='kind',
        ),
    ]
