# Generated by Django 5.2.3 on 2025-07-05 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_remove_mode_kind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mode',
            name='kind_fk',
        ),
        migrations.AddField(
            model_name='mode',
            name='kind',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='modes', to='scheduler.modetype'),
            preserve_default=False,
        ),
    ]
