# Generated by Django 5.2.3 on 2025-07-05 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_remove_mode_kind_fk_mode_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='modetype',
            name='is_normal',
            field=models.BooleanField(default=False, help_text='Is this a normal mode? (e.g., work shift)'),
        ),
    ]
