# Generated by Django 5.2.3 on 2025-07-05 23:52

from django.db import migrations

MODE_COLORS = {
    'N': '#99cc00',
    'NS': '#739900',
    'D': '#ff9900',
    'DS': '#cc7a00',
    'X': '#ffff99',
    'M': '#00ccff',
    'NS-SB': '#739900',
    'DS-CSR': '#cc7a00',
}


def set_normal_mode(apps, schema_editor):
    ModeType = apps.get_model('scheduler', 'ModeType')
    ModeType.objects.filter(acronym__in=['N', 'NS']).update(is_normal=True)
    for acronym, color in MODE_COLORS.items():
        ModeType.objects.filter(acronym=acronym).update(color=color)


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_modetype_is_normal'),
    ]

    operations = [
        migrations.RunPython(set_normal_mode, reverse_code=migrations.RunPython.noop),
    ]
