[project]
name = "uso"
version = "25.9.12"
description = "User Services Online"
readme = "README.md"
authors = [
    { name = "Michel Fodje", email = "michel4j@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "django>=6.1.1,<7.0",
    "django-cas-ng~=5.0.1",
    "django-crisp-modals>=2026.1.2",
    "django-crispy-forms>=2.5",
    "django-dynamic-breadcrumbs==0.4.3",
    "django-dynforms>=2026.10.0",
    "django-formtools==2.5.1",
    "django-itemlist>=2026.1.15",
    "django-model-utils==5.0.0",
    "django-reportcraft>=2026.9.9",
    "djangorestframework==3.18.1",
    "docutils>=0.22.3",
    "faker>=38.2.0",
    "habanero>=2.3.0",
    "isodate~=0.7.2",
    "lxml~=6.0.1",
    "markdown>=3.10",
    "numpy>=2.5.3",
    "ortools>=9.14.6206",
    "pandas>=2.3.3",
    "phonenumbers>=8.13.49",
    "psycopg[binary,pool]>=3.3.2",
    "pycryptodome>=3.23.0",
    "pymemcache~=4.0.0",
    "python-dateutil~=2.9.0.post0",
    "python-dotenv>=1.2.1",
    "python-magic>=0.4.27",
    "pyyaml~=6.0.3",
    "requests>=2.32.5",
    "scipy>=1.18.1",
    "thefuzz>=0.22.1",
    "unidecode>=1.4.0",
]

[project.scripts]
uso = "uso:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
