# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-10 13:40


import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agreements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='users',
            field=models.ManyToManyField(
                related_name='agreements', through='agreements.Acceptance',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='acceptance',
            name='agreement',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='acceptances',
                to='agreements.Agreement'
            ),
        ),
        migrations.AddField(
            model_name='acceptance',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='acceptances',
                to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
