# Generated by Django 5.0.10 on 2024-12-30 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agreements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agreement',
            name='users',
            field=models.ManyToManyField(related_name='agreements', through='agreements.Acceptance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='acceptance',
            name='agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptances', to='agreements.agreement'),
        ),
    ]
