# Generated by Django 5.2.6 on 2025-09-08 21:59

from django.db import migrations, models


def populate_roles(apps, schema_editor):
    Agreement = apps.get_model('agreements', 'Agreement')
    db_alias = schema_editor.connection.alias
    for agreement in Agreement.objects.using(db_alias).all():
        agreement._roles = agreement.roles
        agreement.save(using=db_alias)


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='_roles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(populate_roles, reverse_code=migrations.RunPython.noop),
    ]
