# Generated by Django 5.2.4 on 2025-09-08 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0003_agreement__roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreement',
            name='roles',
        ),
    ]
