# Generated by Django 5.2.4 on 2025-09-08 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0004_remove_agreement_roles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agreement',
            old_name='_roles',
            new_name='roles',
        ),
    ]
