# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-10 13:40


import django.utils.timezone
import model_utils.fields
from django.db import migrations, models

import misc.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ancillary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False,
                    verbose_name='created'
                )),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False,
                    verbose_name='modified'
                )),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Ancillaries',
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False,
                    verbose_name='created'
                )),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False,
                    verbose_name='modified'
                )),
                ('kind', models.CharField(
                    choices=[(b'beamline', 'Beamline'), (b'sector', 'Sector'), (b'village', 'Department'),
                             (b'equipment', 'Equipment')], default=b'beamline', max_length=50, verbose_name='Type'
                )),
                ('name', models.CharField(max_length=255, unique=True)),
                ('acronym', models.CharField(max_length=20, unique=True)),
                ('port', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('range', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Spectral Range')),
                ('spot_size', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Spot Sizes')),
                ('flux', models.CharField(blank=True, max_length=255, null=True)),
                ('resolution',
                 models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Spectral Resolution')),
                ('source', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Source Type')),
                ('state', models.CharField(
                    choices=[(b'design', 'Design'), (b'construction', 'Construction'),
                             (b'commissioning', 'Commissioning'), (b'operating', 'Operating'),
                             (b'decommissioned', 'Decommissioned')], default=b'design',
                    max_length=20
                )),
                ('flex_schedule', models.BooleanField(default=False, verbose_name=b'Flexible Scheduling')),
                ('shift_size', models.IntegerField(
                    choices=[(4, 'Four Hours'), (8, 'Eight Hours')], default=8,
                    verbose_name=b'Shift Size (hrs)'
                )),
                ('details', misc.fields.JSONField(blank=True, default={}, editable=False)),
            ],
            options={
                'verbose_name_plural': 'Facilities',
            },
        ),
        migrations.CreateModel(
            name='FacilityTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False,
                    verbose_name='created'
                )),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False,
                    verbose_name='modified'
                )),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(
                    choices=[(b'scheduling', 'Scheduling'), (b'priority', 'Priority Area'), (b'other', 'Other')],
                    max_length=20
                )),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False,
                    verbose_name='created'
                )),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False,
                    verbose_name='modified'
                )),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='start')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='end')),
                ('cancelled', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True, default=b'', null=True)),
                ('facility', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, related_name='support',
                    to='beamlines.Facility'
                )),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Schedule')),
            ],
        ),
    ]
