# Generated by Django 5.0.10 on 2024-12-30 20:08

import django.db.models.manager
import django.utils.timezone
import misc.fields
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ancillary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('admin_roles', misc.fields.StringListField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict, editable=False)),
                ('available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Ancillaries',
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('kind', models.CharField(choices=[('beamline', 'Beamline'), ('sector', 'Sector'), ('village', 'Department'), ('equipment', 'Equipment')], default='beamline', max_length=50, verbose_name='Type')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('acronym', models.CharField(max_length=20, unique=True)),
                ('port', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('range', models.CharField(blank=True, max_length=255, null=True, verbose_name='Spectral Range')),
                ('spot_size', models.CharField(blank=True, max_length=255, null=True, verbose_name='Spot Sizes')),
                ('flux', models.CharField(blank=True, max_length=255, null=True)),
                ('resolution', models.CharField(blank=True, max_length=255, null=True, verbose_name='Spectral Resolution')),
                ('source', models.CharField(blank=True, max_length=255, null=True, verbose_name='Source Type')),
                ('state', models.CharField(choices=[('design', 'Design'), ('construction', 'Construction'), ('commissioning', 'Commissioning'), ('operating', 'Operating'), ('decommissioned', 'Decommissioned')], default='design', max_length=20)),
                ('flex_schedule', models.BooleanField(default=False, verbose_name='Allocation Not Required')),
                ('shift_size', models.IntegerField(choices=[(4, 'Four Hours'), (8, 'Eight Hours')], default=8, verbose_name='Shift Size (hrs)')),
                ('details', models.JSONField(blank=True, default=dict, editable=False)),
            ],
            options={
                'verbose_name_plural': 'Facilities',
            },
        ),
        migrations.CreateModel(
            name='FacilityTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.CharField(choices=[('scheduling', 'Scheduling'), ('priority', 'Priority Area'), ('other', 'Other')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('acronym', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('admin_roles', misc.fields.StringListField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict, editable=False)),
                ('available', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LabWorkSpace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='start')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='end')),
                ('cancelled', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True, default='', null=True)),
            ],
            managers=[
                ('timeframed', django.db.models.manager.Manager()),
            ],
        ),
    ]
