# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-10 13:40


import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beamlines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersupport',
            name='staff',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='support',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='usersupport',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='support', to='beamlines.FacilityTag'),
        ),
        migrations.AddField(
            model_name='facilitytag',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beamlines.Facility'),
        ),
        migrations.AddField(
            model_name='facility',
            name='parent',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children',
                to='beamlines.Facility', verbose_name=b'Parent Facility'
            ),
        ),
        migrations.AlterUniqueTogether(
            name='usersupport',
            unique_together=set([('staff', 'facility', 'start')]),
        ),
    ]
