# Generated by Django 5.0.9 on 2024-11-30 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beamlines', '0001_initial'),
        ('samples', '0001_initial'),
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ancillary',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='samples.safetypermission'),
        ),
        migrations.AddField(
            model_name='facility',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='beamlines.facility', verbose_name='Parent Facility'),
        ),
        migrations.AddField(
            model_name='facilitytag',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beamlines.facility'),
        ),
        migrations.AddField(
            model_name='lab',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='samples.safetypermission'),
        ),
        migrations.AddField(
            model_name='labworkspace',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to='beamlines.lab'),
        ),
        migrations.AddField(
            model_name='usersupport',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support', to='beamlines.facility'),
        ),
        migrations.AddField(
            model_name='usersupport',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.schedule'),
        ),
    ]
