# Generated by Django 5.0.11 on 2025-03-06 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beamlines', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='beamlines.facility', verbose_name='Parent Facility'),
        ),
    ]
