# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-12 23:43


from django.db import migrations, models

import misc.fields


class Migration(migrations.Migration):
    dependencies = [
        ('samples', '0002_auto_20170110_0740'),
        ('beamlines', '0003_lab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='admin_roles',
            field=misc.fields.StringListField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='lab',
            name='permissions',
        ),
        migrations.AddField(
            model_name='lab',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='samples.SafetyPermission'),
        ),
    ]
