# Generated by Django 5.0.11 on 2025-06-20 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beamlines', '0004_alter_facility_parent'),
        ('scheduler', '0002_alter_mode_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersupport',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='scheduler.schedule'),
        ),
    ]
