# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-17 13:15


from django.db import migrations, models

import misc.fields


class Migration(migrations.Migration):
    dependencies = [
        ('samples', '0003_auto_20170116_1721'),
        ('beamlines', '0004_auto_20170112_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='ancillary',
            name='admin_roles',
            field=misc.fields.StringListField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ancillary',
            name='details',
            field=misc.fields.JSONField(blank=True, default={}, editable=False),
        ),
        migrations.AddField(
            model_name='ancillary',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='samples.SafetyPermission'),
        ),
        migrations.AddField(
            model_name='lab',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
