# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-17 13:20


import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('beamlines', '0005_auto_20170117_0715'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabWorkSpace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False,
                    verbose_name='created'
                )),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False,
                    verbose_name='modified'
                )),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='lab',
            name='workspaces',
        ),
        migrations.AddField(
            model_name='labworkspace',
            name='lab',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='workspaces',
                to='beamlines.Lab'
            ),
        ),
    ]
