# Generated by Django 5.2.3 on 2025-07-22 16:54

from django.db import migrations


def convert_types(apps, schema_editor):
    """
    This migration is a placeholder for future changes.
    Currently, it does not perform any operations.
    """
    # Placeholder for future operations
    Facility = apps.get_model('beamlines', 'Facility')
    # replace "village" with "department" in the kind field
    Facility.objects.filter(kind='village').update(kind='department')

    # replace "equipment" with "instrument" in the kind field
    Facility.objects.filter(kind='equipment').update(kind='instrument')


class Migration(migrations.Migration):

    dependencies = [
        ('beamlines', '0006_alter_usersupport_schedule'),
    ]

    operations = [
        migrations.RunPython(convert_types, migrations.RunPython.noop),
    ]
