# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-19 20:03


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('beamlines', '0007_auto_20170117_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='flex_schedule',
            field=models.BooleanField(default=False, verbose_name='Allocation Not Required'),
        ),
        migrations.AlterField(
            model_name='facilitytag',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
