# Generated by Django 5.2.3 on 2025-07-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beamlines', '0007_auto_20250722_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='kind',
            field=models.CharField(choices=[('beamline', 'Beamline'), ('sector', 'Sector'), ('department', 'Department'), ('instrument', 'Instrument')], default='beamline', max_length=50, verbose_name='Type'),
        ),
    ]
