# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-27 16:26


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('beamlines', '0008_auto_20170119_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labworkspace',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='labworkspace',
            unique_together=set([('lab', 'name')]),
        ),
    ]
