# Generated by Django 5.2.3 on 2025-07-24 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beamlines', '0008_alter_facility_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitytag',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='facilitytag',
            name='color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
