# Generated by Django 5.2.3 on 2025-07-29 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beamlines', '0009_facilitytag_active_facilitytag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='acronym',
            field=models.SlugField(max_length=20, unique=True),
        ),
    ]
