# Generated by Django 3.2.4 on 2024-11-13 02:30

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('beamlines', '0009_auto_20170127_1026'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usersupport',
            managers=[
                ('timeframed', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='facility',
            name='kind',
            field=models.CharField(
                choices=[('beamline', 'Beamline'), ('sector', 'Sector'), ('village', 'Department'),
                         ('equipment', 'Equipment')], default='beamline', max_length=50, verbose_name='Type'
            ),
        ),
        migrations.AlterField(
            model_name='facility',
            name='parent',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children',
                to='beamlines.facility', verbose_name='Parent Facility'
            ),
        ),
        migrations.AlterField(
            model_name='facility',
            name='range',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Spectral Range'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='resolution',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Spectral Resolution'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='shift_size',
            field=models.IntegerField(
                choices=[(4, 'Four Hours'), (8, 'Eight Hours')], default=8, verbose_name='Shift Size (hrs)'
            ),
        ),
        migrations.AlterField(
            model_name='facility',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Source Type'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='spot_size',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Spot Sizes'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='state',
            field=models.CharField(
                choices=[('design', 'Design'), ('construction', 'Construction'), ('commissioning', 'Commissioning'),
                         ('operating', 'Operating'), ('decommissioned', 'Decommissioned')], default='design',
                max_length=20
            ),
        ),
        migrations.AlterField(
            model_name='facilitytag',
            name='category',
            field=models.CharField(
                choices=[('scheduling', 'Scheduling'), ('priority', 'Priority Area'), ('other', 'Other')], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name='facilitytag',
            name='facility',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='beamlines.facility'
            ),
        ),
        migrations.AlterField(
            model_name='usersupport',
            name='comments',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
