# Generated by Django 5.2.6 on 2025-09-08 21:59

from django.db import migrations, models


def populate_roles(apps, schema_editor):
    Ancillary = apps.get_model('beamlines', 'Ancillary')
    Lab = apps.get_model('beamlines', 'Lab')
    db_alias = schema_editor.connection.alias
    for ancillary in Ancillary.objects.using(db_alias).all():
        ancillary._admin_roles = ancillary.admin_roles
        ancillary.save(using=db_alias)

    for lab in Lab.objects.using(db_alias).all():
        lab._admin_roles = lab.admin_roles
        lab.save(using=db_alias)


class Migration(migrations.Migration):

    dependencies = [
        ('beamlines', '0010_alter_lab_acronym'),
    ]

    operations = [
        migrations.AddField(
            model_name='ancillary',
            name='_admin_roles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='lab',
            name='_admin_roles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(populate_roles, reverse_code=migrations.RunPython.noop),
    ]
