# Generated by Django 5.0.9 on 2024-11-14 03:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('beamlines', '0010_auto_20241112_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ancillary',
            name='details',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AlterField(
            model_name='facility',
            name='details',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AlterField(
            model_name='lab',
            name='details',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
    ]
