# Generated by Django 5.2.4 on 2025-09-08 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beamlines', '0011_ancillary__admin_roles_lab__admin_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ancillary',
            name='admin_roles',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='admin_roles',
        ),
    ]
