# Generated by Django 5.2.4 on 2025-09-08 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beamlines', '0012_remove_ancillary_admin_roles_remove_lab_admin_roles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ancillary',
            old_name='_admin_roles',
            new_name='admin_roles',
        ),
        migrations.RenameField(
            model_name='lab',
            old_name='_admin_roles',
            new_name='admin_roles',
        ),
    ]
