# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-10 13:40


import django.utils.timezone
import model_utils.fields
from django.db import migrations, models

import misc.fields
import misc.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False,
                                                                verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False,
                                                                      verbose_name='modified')),
                ('object_id', models.PositiveIntegerField()),
                ('user_name', models.CharField(max_length=60, verbose_name=b'User name')),
                ('address', models.GenericIPAddressField(verbose_name=b'IP Address')),
                ('kind', models.CharField(
                    choices=[(b'task', 'Task Performed'), (b'create', 'Created'), (b'modify', 'Modified'),
                             (b'delete', 'Deleted')], max_length=20, verbose_name=b'Type')),
                ('object_repr', models.CharField(blank=True, max_length=200, null=True, verbose_name=b'Entity')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False,
                                                                verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False,
                                                                      verbose_name='modified')),
                ('object_id', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=100, verbose_name=b'name')),
                ('file', misc.fields.RestrictedFileField(help_text='Maximum size 2.5\xa0MB, Formats: PDF,JPEG,PNG.',
                                                         storage=misc.fields.LocalStorage(),
                                                         upload_to=misc.models.attachment_file,
                                                         verbose_name=b'Attachment')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('kind', models.CharField(
                    choices=[(b'scientific', 'Scientific'), (b'safety', 'Safety'), (b'ethics', 'Ethics'),
                             (b'other', 'Other')], max_length=20, verbose_name=b'Type')),
                ('is_editable', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Clarification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False,
                                                                verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False,
                                                                      verbose_name='modified')),
                ('object_id', models.PositiveIntegerField()),
                ('question', models.TextField()),
                ('response', models.TextField(blank=True, null=True)),
                ('content_type',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
