# Generated by Django 5.0.11 on 2025-06-14 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Description'),
        ),
    ]
