# Generated by Django 3.2.4 on 2024-11-13 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import misc.fields
import misc.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('misc', '0002_auto_20170110_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='address',
            field=models.GenericIPAddressField(verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='kind',
            field=models.CharField(choices=[('task', 'Task Performed'), ('create', 'Created'), ('modify', 'Modified'), ('delete', 'Deleted')], max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='object_repr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Entity'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='user_name',
            field=models.CharField(max_length=60, verbose_name='User name'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='description',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=misc.fields.RestrictedFileField(help_text='Maximum size 2.5\xa0MB, Formats: PDF,JPEG,PNG.', storage=misc.fields.LocalStorage(), upload_to=misc.models.attachment_file, verbose_name='Attachment'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='kind',
            field=models.CharField(choices=[('scientific', 'Scientific'), ('safety', 'Safety'), ('ethics', 'Ethics'), ('other', 'Other')], max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='clarification',
            name='responder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to=settings.AUTH_USER_MODEL),
        ),
    ]
