# Generated by Django 5.2.4 on 2025-08-05 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0003_alter_attachment_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='object_repr',
        ),
    ]
