# Generated by Django 5.2.4 on 2025-08-09 01:44

from django.db import migrations

# SQL to create the function.
# This function takes a jsonb object and a delimiter, expands the jsonb array
# elements into text rows, and then aggregates them into a single string.

CREATE_FUNCTION_SQL = """
CREATE OR REPLACE FUNCTION jsonb_array_to_string(json_data jsonb, delimiter text)
RETURNS text AS $$
BEGIN
    -- Check if the input is a valid JSON array
    IF jsonb_typeof(json_data) != 'array' THEN
        RETURN NULL; -- Or return an empty string '', or raise an exception
    END IF;

    -- Aggregate the array elements into a single string using the provided delimiter
    RETURN (
        SELECT string_agg(elem, delimiter)
        FROM jsonb_array_elements_text(json_data) AS elem
    );
END;
$$ LANGUAGE plpgsql IMMUTABLE;
"""

# SQL to drop the function when the migration is reversed.
# Note the updated signature with two arguments.
DROP_FUNCTION_SQL = "DROP FUNCTION IF EXISTS jsonb_array_to_string(jsonb, text);"


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0004_remove_activitylog_object_repr'),
    ]

    operations = [
        migrations.RunSQL(
            sql=CREATE_FUNCTION_SQL,
            reverse_sql=DROP_FUNCTION_SQL,
        ),
    ]
