# Generated by Django 5.2.4 on 2025-09-02 14:20

from django.db import migrations


def update_dynforms_data(apps, schema_editor):
    FormType = apps.get_model('dynforms', 'FormType')
    forms_to_update = FormType.objects.all()

    for form in forms_to_update:
        updated_actions = []
        for action, label in form.actions:
            if action == 'save' and label == 'Save & Preview':
                updated_actions.append(('preview', 'Preview'))
            elif action == 'save_continue':
                updated_actions.append(('save', label))
            elif action == 'save' and label == 'Submit':
                updated_actions.append(('submit', 'Submit'))
            elif action == 'submit' and label == 'Save':
                updated_actions.append(('save', 'Save'))
            else:
                updated_actions.append((action, label))
        form.actions = updated_actions
    FormType.objects.bulk_update(forms_to_update, ['actions'])


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0005_auto_20250808_1944'),
    ]

    operations = [
        migrations.RunPython(update_dynforms_data, reverse_code=migrations.RunPython.noop),
    ]
