# Generated by Django 5.2.6 on 2025-09-05 19:33

from django.db import migrations


import os
from django.db import migrations
from django.core import serializers


def load_fixture(apps, schema_editor):
    fixture_path = os.path.join(
        os.path.dirname(__file__),
        '..',
        'fixtures',
        '001-reportcraft.yml'
    )
    with open(fixture_path, 'r') as fixture_file:
        objects = serializers.deserialize('yaml', fixture_file)
        for obj in objects:
            obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0006_update_dynforms_data'),
    ]

    operations = [
        migrations.RunPython(load_fixture, reverse_code=migrations.RunPython.noop),
    ]
