# Generated by Django 5.2.6 on 2025-09-05 19:33

from django.db import migrations


import os
from django.db import migrations
from django.core import serializers


def load_fixture(apps, schema_editor):
    fixture_path = os.path.join(
        os.path.dirname(__file__),
        '..',
        'fixtures',
        '001-reportcraft.yml'
    )
    db_alias = schema_editor.connection.alias
    if not os.path.exists(fixture_path):
        return

    with open(fixture_path, 'r') as fixture_file:
        objects = serializers.deserialize('yaml', fixture_file)
        for obj in objects:
            obj.save(using=db_alias)


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0006_update_dynforms_data'),
        ('proposals', '0058_fix_cycle_schedules'),
        ('publications', '0025_publication_journal_metric'),
        ('users', '0014_rename__city_institution_city_and_more'),
    ]

    operations = [
        migrations.RunPython(load_fixture, reverse_code=migrations.RunPython.noop),
    ]
