# Generated by Django 5.2.4 on 2025-09-09 22:47

from django.db import migrations


CREATE_FUNCTION_SQL = """
CREATE OR REPLACE FUNCTION jsonb_array_avg(
    details jsonb,
    array_key text,
    value_key text
) RETURNS float AS $$
    SELECT AVG((item->>value_key)::float)
    FROM jsonb_array_elements(details->array_key) AS item
$$ LANGUAGE SQL IMMUTABLE;
"""

# SQL to drop the function when the migration is reversed.
# Note the updated signature with two arguments.
DROP_FUNCTION_SQL = "DROP FUNCTION IF EXISTS jsonb_array_avg(jsonb, text);"


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0007_update_reports'),
    ]

    operations = [
        migrations.RunSQL(
            sql=CREATE_FUNCTION_SQL,
            reverse_sql=DROP_FUNCTION_SQL,
        ),
    ]
