# Generated by Django 5.0.10 on 2024-12-30 20:08

import django.db.models.deletion
import django.utils.timezone
import misc.fields
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beamlines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('authors', misc.fields.StringListField(verbose_name='Authors')),
                ('title', models.TextField()),
                ('date', models.DateField(verbose_name='Published')),
                ('keywords', models.TextField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('article', 'Peer-Reviewed Article'), ('proceeding', 'Conference Proceeding'), ('phd_thesis', 'Doctoral Thesis'), ('msc_thesis', 'Masters Thesis'), ('magazine', 'Magazine Article'), ('chapter', 'Book / Chapter'), ('pdb', 'PDB Deposition'), ('patent', 'Patent')], default='article', max_length=20, verbose_name='Type')),
                ('citations', models.IntegerField(default=0)),
                ('reviewed', models.BooleanField(default=False, verbose_name='Reviewed')),
                ('category', models.CharField(blank=True, choices=[('beamline', 'Beamline'), ('dataless', 'Staff, No CLS Data'), ('design', 'Beamline Design'), ('facility', 'Facility')], max_length=30, null=True, verbose_name='Category')),
                ('notes', models.TextField(blank=True, null=True)),
                ('affiliation', models.JSONField(default=dict)),
                ('history', models.JSONField(blank=True, default=list)),
                ('beamlines', models.ManyToManyField(blank=True, related_name='publications', to='beamlines.facility')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FundingSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('acronym', models.CharField(max_length=255)),
                ('kind', models.CharField(blank=True, max_length=50, null=True, verbose_name='Type')),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('doi', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=255)),
                ('issn', models.CharField(max_length=50, unique=True, verbose_name='ISSN')),
                ('publisher', models.CharField(blank=True, max_length=100, null=True)),
                ('kind', models.CharField(blank=True, max_length=100, null=True)),
                ('sjr', models.FloatField(default=0.0, verbose_name='SJR-Rank')),
                ('ifactor', models.FloatField(default=0.0, verbose_name='Impact Factor')),
                ('hindex', models.IntegerField(default=1.0, verbose_name='H-Index')),
                ('score_date', models.DateField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PublicationTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubjectArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('publication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='publications.publication')),
                ('code', models.CharField(max_length=50, null=True, unique=True, verbose_name='DOI')),
                ('volume', models.CharField(blank=True, max_length=100, null=True)),
                ('number', models.CharField(blank=True, max_length=20, null=True)),
                ('pages', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('publications.publication',),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('publication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='publications.publication')),
                ('code', models.CharField(blank=True, max_length=255, null=True, verbose_name='ISBN or DOI')),
                ('main_title', models.CharField(blank=True, max_length=255, null=True)),
                ('editor', models.TextField(blank=True, null=True)),
                ('publisher', models.CharField(blank=True, max_length=100, null=True)),
                ('edition', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('volume', models.CharField(blank=True, max_length=100, null=True)),
                ('pages', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Chapters/Books',
                'verbose_name_plural': 'Chapters/Books',
            },
            bases=('publications.publication',),
        ),
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('publication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='publications.publication')),
                ('code', models.CharField(max_length=30, null=True, unique=True, verbose_name='Patent Number')),
            ],
            options={
                'abstract': False,
            },
            bases=('publications.publication',),
        ),
        migrations.CreateModel(
            name='PDBDeposition',
            fields=[
                ('publication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='publications.publication')),
                ('code', models.CharField(max_length=4, unique=True)),
                ('details', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Macromolecule Structure',
            },
            bases=('publications.publication',),
        ),
    ]
