# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-10 13:40


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('publications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='publications', to=settings.AUTH_USER_MODEL,
                                         verbose_name='CLS Users'),
        ),
        migrations.AddField(
            model_name='pdbdeposition',
            name='reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdbs',
                                    to='publications.Publication'),
        ),
        migrations.AddField(
            model_name='article',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles',
                                    to='publications.Journal'),
        ),
    ]
