# Generated by Django 3.2.4 on 2024-11-13 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_auto_20170110_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectarea',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_areas', to='publications.subjectarea'),
        ),
    ]
