# Generated by Django 5.2.4 on 2025-08-04 23:20

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalMetric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('sjr_rank', models.FloatField(default=0.0, null=True, verbose_name='SJR-Rank')),
                ('sjr_quartile', models.SmallIntegerField(default=4, null=True, verbose_name='SJR-Quartile')),
                ('impact_factor', models.FloatField(default=0.0, null=True, verbose_name='Impact Factor')),
                ('h_index', models.IntegerField(default=1.0, null=True, verbose_name='H-Index')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Effective Date')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='publications.journal')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
