# Generated by Django 5.2.4 on 2025-08-04 23:33

import publications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_journalmetric'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='hindex',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='ifactor',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='score_date',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='sjr',
        ),
        migrations.RemoveField(
            model_name='journalmetric',
            name='date',
        ),
        migrations.AddField(
            model_name='journal',
            name='codes',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='ISSN Codes'),
        ),
        migrations.AddField(
            model_name='journal',
            name='short_name',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='journals', to='publications.subjectarea'),
        ),
        migrations.AddField(
            model_name='journalmetric',
            name='year',
            field=models.IntegerField(default=publications.models.default_year, verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='title',
            field=models.TextField(),
        ),
    ]
