# Generated by Django 5.2.4 on 2025-08-04 23:34

from django.db import migrations


def populate_journal_codes(apps, schema_editor):
    Journal = apps.get_model('publications', 'Journal')
    to_update = Journal.objects.all()
    for journal in to_update:
        if not journal.codes:
            journal.codes = [code.strip() for code in journal.issn.split(';')]

    Journal.objects.bulk_update(to_update, ['codes'], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_remove_journal_hindex_remove_journal_ifactor_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_journal_codes, migrations.RunPython.noop),
    ]
