# Generated by Django 5.2.4 on 2025-08-04 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0005_auto_20250804_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='citations',
        ),
        migrations.AddField(
            model_name='publication',
            name='author_list',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Author List'),
        ),
        migrations.AddField(
            model_name='publication',
            name='info',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='keyword_list',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Keyword List'),
        ),
    ]
