# Generated by Django 5.2.4 on 2025-08-04 23:56

from django.db import migrations


def save_book_info(apps, schema_editor):
    Book = apps.get_model('publications', 'Book')

    book_to_update = Book.objects.all()
    for book in book_to_update:
        book.info = {
            'code': book.code,
            'main_title': book.main_title,
            'editors': book.editor,
            'publisher': book.publisher,
            'edition': book.edition,
            'address': book.address,
            'volume': book.volume,
            'pages': book.pages,
        }
    Book.objects.bulk_update(book_to_update, ['info'], batch_size=500)


def save_article_info(apps, schema_editor):
    Article = apps.get_model('publications', 'Article')

    article_to_update = Article.objects.all()
    for article in article_to_update:
        article.info = {
            'code': article.code,
            'journal': None if not article.journal else article.journal.pk,
            'volume': article.volume,
            'number': article.number,
            'pages': article.pages,
        }
    Article.objects.bulk_update(article_to_update, ['info'], batch_size=500)


def save_pdb_deposition_info(apps, schema_editor):
    PDBDeposition = apps.get_model('publications', 'PDBDeposition')
    pdb_depositions = PDBDeposition.objects.all()
    for pdb in pdb_depositions:
        pdb.info = {
            'code': pdb.code,
            'reference': None if not pdb.reference else pdb.reference.pk,
        }
    PDBDeposition.objects.bulk_update(pdb_depositions, ['info'], batch_size=500)


def save_patent_info(apps, schema_editor):
    Patent = apps.get_model('publications', 'Patent')

    patent_to_update = Patent.objects.all()
    for patent in patent_to_update:
        patent.info = {
            'code': patent.code,
        }
    Patent.objects.bulk_update(patent_to_update, ['info'], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0006_remove_publication_citations_publication_author_list_and_more'),
    ]

    operations = [
        migrations.RunPython(save_book_info, migrations.RunPython.noop),
        migrations.RunPython(save_article_info, migrations.RunPython.noop),
        migrations.RunPython(save_pdb_deposition_info, migrations.RunPython.noop),
        migrations.RunPython(save_patent_info, migrations.RunPython.noop),
    ]
