# Generated by Django 5.2.4 on 2025-08-05 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0008_remove_book_publication_ptr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='editor',
            new_name='editors',
        ),
    ]
