# Generated by Django 5.2.4 on 2025-08-05 01:57

from django.db import migrations
import re


def save_author_and_keywords(apps, schema_editor):
    Publication = apps.get_model('publications', 'Publication')
    to_update = Publication.objects.all()
    for pub in to_update:
        pub.author_list = pub.authors
        pub.keyword_list = [kw.strip() for kw in re.split(r'\s*[,;]+\s*', pub.keywords)] if pub.keywords else []
    Publication.objects.bulk_update(to_update, ['author_list', 'keyword_list'], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0009_rename_editor_publication_editors'),
    ]

    operations = [
        migrations.RunPython(save_author_and_keywords, migrations.RunPython.noop),
    ]
