# Generated by Django 5.2.4 on 2025-08-05 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0010_auto_20250804_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='doi',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
