# Generated by Django 5.2.4 on 2025-08-05 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0011_publication_doi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='doi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
