# Generated by Django 5.2.4 on 2025-08-05 04:57

from django.db import migrations
from django.db.models.fields.json import KT


def restore_publication_info(apps, schema_editor):
    Publication = apps.get_model('publications', 'Publication')

    field_names = [
        'code', 'main_title', 'editors', 'publisher', 'edition', 'address', 'volume', 'pages',
    ]
    field_updates = {
        key: KT(f'info__{key}') for key in field_names
    }
    field_updates['issue'] = KT('info__number')

    Publication.objects.update(**field_updates)

    to_update = Publication.objects.all()
    for pub in to_update:
        pub.journal_id = pub.info.get('journal')
        pub.reference_id = pub.info.get('reference')

    Publication.objects.bulk_update(
        to_update, ['journal_id', 'reference_id'], batch_size=500
    )


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0012_alter_publication_code_alter_publication_doi'),
    ]

    operations = [
        migrations.RunPython(restore_publication_info, migrations.RunPython.noop),
    ]
