# Generated by Django 5.2.4 on 2025-08-05 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0013_auto_20250804_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='keywords',
        ),
    ]
