# Generated by Django 5.2.4 on 2025-08-05 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0014_remove_publication_authors_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='author_list',
            new_name='authors',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='keyword_list',
            new_name='keywords',
        ),
    ]
