# Generated by Django 5.2.4 on 2025-08-05 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0015_rename_author_list_publication_authors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='kind',
            field=models.CharField(choices=[('article', 'Peer-Reviewed Article'), ('proceeding', 'Conference Proceeding'), ('phd_thesis', 'Doctoral Thesis'), ('msc_thesis', 'Masters Thesis'), ('magazine', 'Magazine Article'), ('chapter', 'Book Chapter'), ('book', 'Book'), ('pdb', 'PDB Deposition'), ('patent', 'Patent')], default='article', max_length=20, verbose_name='Type'),
        ),
    ]
