# Generated by Django 5.2.4 on 2025-08-05 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0016_alter_publication_kind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='history',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='info',
        ),
    ]
