# Generated by Django 5.2.4 on 2025-08-05 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0017_remove_publication_history_remove_publication_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='doi',
        ),
    ]
