# Generated by Django 5.2.4 on 2025-08-05 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0018_remove_publication_doi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='kind',
        ),
        migrations.AlterField(
            model_name='fundingsource',
            name='doi',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
