# Generated by Django 5.2.4 on 2025-08-05 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0019_remove_journal_kind_alter_fundingsource_doi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundingsource',
            name='kind',
        ),
        migrations.AlterField(
            model_name='fundingsource',
            name='acronym',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
