# Generated by Django 5.2.4 on 2025-08-06 00:13

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import publications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0020_remove_fundingsource_kind_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleMetric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('citations', models.IntegerField(default=0, verbose_name='Citations')),
                ('mentions', models.IntegerField(default=0, verbose_name='Views')),
                ('year', models.IntegerField(default=publications.models.default_year, verbose_name='Year')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='publications.publication')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
