# Generated by Django 5.2.4 on 2025-08-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0021_articlemetric'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemetric',
            name='self_cites',
            field=models.IntegerField(default=0, verbose_name='Self-Citations'),
        ),
        migrations.AlterField(
            model_name='articlemetric',
            name='mentions',
            field=models.IntegerField(default=0, verbose_name='Mentions'),
        ),
        migrations.AlterUniqueTogether(
            name='articlemetric',
            unique_together={('publication', 'year')},
        ),
    ]
