# Generated by Django 5.2.4 on 2025-08-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0023_alter_journalmetric_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='pdb_doi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='PDB DOI'),
        ),
    ]
