# Generated by Django 5.2.4 on 2025-08-08 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0024_publication_pdb_doi'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='journal_metric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='publications.journalmetric'),
        ),
    ]
