# Generated by Django 5.2.4 on 2025-09-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0025_publication_journal_metric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='issn',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ISSN'),
        ),
    ]
