# Generated by Django 5.0.9 on 2024-11-30 21:18

import django.db.models.deletion
import django.utils.timezone
import misc.fields
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beamlines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('details', models.JSONField(blank=True, default=dict, editable=False, null=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('leader_username', models.CharField(blank=True, max_length=50, null=True)),
                ('delegate_username', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.TextField(null=True)),
                ('keywords', models.TextField(null=True)),
                ('team', misc.fields.StringListField(blank=True, null=True)),
                ('state', models.IntegerField(choices=[(0, 'Not Submitted'), (1, 'Submitted')], default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('details', models.JSONField(blank=True, default=dict, editable=False, null=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('object_id', models.PositiveIntegerField()),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.IntegerField(choices=[(0, 'Pending'), (1, 'Open'), (2, 'Submitted'), (3, 'Closed')], default=0)),
                ('score', models.FloatField(default=0)),
                ('score_1', models.FloatField(default=0)),
                ('score_2', models.FloatField(default=0)),
                ('due_date', models.DateField(null=True)),
                ('kind', models.CharField(choices=[('scientific', 'Scientific Review'), ('technical', 'Technical Review'), ('safety', 'Safety Review'), ('ethics', 'Ethics Review'), ('equipment', 'Equipment Review'), ('approval', 'Safety Approval')], default='scientific', max_length=30, verbose_name='Type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReviewCycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('mock', 'Mock Cycle'), ('normal', 'Normal Cycle')], default='normal', max_length=20, verbose_name='Cycle Type')),
                ('open_date', models.DateField(verbose_name='Call Open Date')),
                ('close_date', models.DateField(verbose_name='Call Close Date')),
                ('alloc_date', models.DateField(verbose_name='Allocation Date')),
                ('due_date', models.DateField(null=True, verbose_name='Reviews Due')),
                ('state', models.SmallIntegerField(choices=[(0, 'Call Pending'), (1, 'Call Open'), (2, 'Assigning'), (3, 'Review'), (4, 'Allocation'), (5, 'Scheduling'), (6, 'Active'), (7, 'Archived')], default=0)),
            ],
            options={
                'get_latest_by': 'start_date',
            },
        ),
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('karma', models.DecimalField(decimal_places=2, default='0.0', max_digits=4)),
                ('comments', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('user__last_name',),
            },
        ),
        migrations.CreateModel(
            name='ReviewTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=128)),
                ('acronym', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(null=True)),
                ('special', models.BooleanField(default=None, null=True, unique=True, verbose_name='Special Requests')),
                ('min_reviewers', models.IntegerField(default=0, verbose_name='Min Reviews/Proposal')),
                ('max_proposals', models.IntegerField(default=0, verbose_name='Max Proposals/Reviewer')),
                ('notify_offset', models.IntegerField(default=1, verbose_name='Notification Delay (days)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScoreAdjustment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('reason', models.TextField()),
                ('value', models.FloatField(default=0.5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('kind', models.CharField(choices=[('user', 'User Access'), ('staff', 'Staff Access'), ('purchased', 'Purchased Access'), ('beamteam', 'Beam Team'), ('education', 'Education/Outreach')], default='user', max_length=20, verbose_name='Access Type')),
                ('state', models.IntegerField(choices=[(0, 'Pending'), (1, 'Started'), (2, 'Reviewed'), (3, 'Complete')], default=0)),
                ('comments', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('diffraction', 'Diffraction/Scattering'), ('imaging', 'Imaging/Microscopy'), ('spectroscopy', 'Spectroscopy'), ('other', 'Other')], default='other', max_length=50, verbose_name='Category')),
                ('acronym', models.CharField(blank=True, max_length=20, null=True, verbose_name='Acronym')),
            ],
            options={
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='FacilityConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('accept', models.BooleanField(default=False, verbose_name='Accept Proposals')),
                ('comments', models.TextField(blank=True, null=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='beamlines.facility')),
            ],
            options={
                'verbose_name': 'Facility Configuration',
                'ordering': ['-cycle'],
                'get_latest_by': 'cycle',
            },
        ),
        migrations.CreateModel(
            name='ConfigItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('state', models.CharField(choices=[('design', 'Design'), ('construction', 'Construction'), ('commissioning', 'Commissioning'), ('operating', 'Active')], default='operating', max_length=30)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='proposals.facilityconfig')),
            ],
        ),
    ]
