# Generated by Django 5.0.9 on 2024-11-30 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dynforms', '0001_initial'),
        ('proposals', '0001_initial'),
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='areas',
            field=models.ManyToManyField(blank=True, related_name='proposals', to='publications.subjectarea', verbose_name='Research Subject Areas'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='form_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dynforms.formtype'),
        ),
    ]
