# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-10 13:40


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dynforms', '0001_initial'),
        ('proposals', '0001_initial'),
        ('publications', '0001_initial'),
        ('beamlines', '0002_auto_20170110_0740'),
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='prc_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submission',
            name='techniques',
            field=models.ManyToManyField(blank=True, related_name='submissions', to='proposals.ConfigItem'),
        ),
        migrations.AddField(
            model_name='submission',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposals.ReviewTrack'),
        ),
        migrations.AddField(
            model_name='scoreadjustment',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments',
                                    to='proposals.Submission'),
        ),
        migrations.AddField(
            model_name='scoreadjustment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewer',
            name='areas',
            field=models.ManyToManyField(to='publications.SubjectArea', verbose_name='Subject Areas'),
        ),
        migrations.AddField(
            model_name='reviewer',
            name='committee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committee',
                                    to='proposals.ReviewTrack', verbose_name='PRC Member'),
        ),
        migrations.AddField(
            model_name='reviewer',
            name='techniques',
            field=models.ManyToManyField(related_name='reviewers', to='proposals.Technique'),
        ),
        migrations.AddField(
            model_name='reviewer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewcycle',
            name='call_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles',
                                    to='proposals.CallType'),
        ),
        migrations.AddField(
            model_name='reviewcycle',
            name='reviewers',
            field=models.ManyToManyField(blank=True, related_name='cycles', to='proposals.Reviewer'),
        ),
        migrations.AddField(
            model_name='reviewcycle',
            name='schedule',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cycle',
                                       to='scheduler.Schedule'),
        ),
        migrations.AddField(
            model_name='review',
            name='proposal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews',
                                    to='proposals.Submission'),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews',
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='spec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynforms.FormSpec'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='areas',
            field=models.ManyToManyField(blank=True, related_name='proposals', to='publications.SubjectArea',
                                         verbose_name='Research Subject Areas'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='spec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynforms.FormSpec'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='spokesperson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+',
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facilityconfig',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposals.ReviewCycle',
                                    verbose_name='Start Cycle'),
        ),
        migrations.AddField(
            model_name='facilityconfig',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs',
                                    to='beamlines.Facility'),
        ),
        migrations.AddField(
            model_name='facilityconfig',
            name='techniques',
            field=models.ManyToManyField(related_name='configs', through='proposals.ConfigItem',
                                         to='proposals.Technique'),
        ),
        migrations.AddField(
            model_name='configitem',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items',
                                    to='proposals.FacilityConfig'),
        ),
        migrations.AddField(
            model_name='configitem',
            name='technique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items',
                                    to='proposals.Technique'),
        ),
        migrations.AddField(
            model_name='configitem',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposals.ReviewTrack'),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together=set([('proposal', 'track')]),
        ),
        migrations.AlterUniqueTogether(
            name='reviewcycle',
            unique_together=set([('start_date', 'open_date')]),
        ),
        migrations.AlterUniqueTogether(
            name='facilityconfig',
            unique_together=set([('cycle', 'facility')]),
        ),
        migrations.AlterUniqueTogether(
            name='configitem',
            unique_together=set([('config', 'technique')]),
        ),
    ]
