# Generated by Django 5.0.9 on 2024-11-30 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dynforms', '0001_initial'),
        ('proposals', '0002_initial'),
        ('publications', '0002_initial'),
        ('scheduler', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='spokesperson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='review',
            name='form_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dynforms.formtype'),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewcycle',
            name='schedule',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cycle', to='scheduler.schedule'),
        ),
        migrations.AddField(
            model_name='review',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='proposals.reviewcycle', verbose_name='Cycle'),
        ),
        migrations.AddField(
            model_name='facilityconfig',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposals.reviewcycle', verbose_name='Start Cycle'),
        ),
        migrations.AddField(
            model_name='reviewer',
            name='areas',
            field=models.ManyToManyField(to='publications.subjectarea', verbose_name='Subject Areas'),
        ),
        migrations.AddField(
            model_name='reviewer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewcycle',
            name='reviewers',
            field=models.ManyToManyField(blank=True, related_name='cycles', to='proposals.reviewer'),
        ),
        migrations.AddField(
            model_name='reviewer',
            name='committee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committee', to='proposals.reviewtrack', verbose_name='PRC Member'),
        ),
        migrations.AddField(
            model_name='configitem',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposals.reviewtrack'),
        ),
        migrations.AddField(
            model_name='scoreadjustment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submission',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='proposals.reviewcycle'),
        ),
        migrations.AddField(
            model_name='submission',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='proposals.proposal'),
        ),
        migrations.AddField(
            model_name='submission',
            name='techniques',
            field=models.ManyToManyField(blank=True, related_name='submissions', to='proposals.configitem'),
        ),
        migrations.AddField(
            model_name='submission',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='proposals.reviewtrack'),
        ),
        migrations.AddField(
            model_name='scoreadjustment',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adjustment', to='proposals.submission'),
        ),
        migrations.AddField(
            model_name='reviewer',
            name='techniques',
            field=models.ManyToManyField(related_name='reviewers', to='proposals.technique'),
        ),
        migrations.AddField(
            model_name='facilityconfig',
            name='techniques',
            field=models.ManyToManyField(related_name='configs', through='proposals.ConfigItem', to='proposals.technique'),
        ),
        migrations.AddField(
            model_name='configitem',
            name='technique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='proposals.technique'),
        ),
        migrations.AlterUniqueTogether(
            name='reviewcycle',
            unique_together={('start_date', 'open_date')},
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('proposal', 'track')},
        ),
        migrations.AlterUniqueTogether(
            name='facilityconfig',
            unique_together={('cycle', 'facility')},
        ),
        migrations.AlterUniqueTogether(
            name='configitem',
            unique_together={('config', 'technique')},
        ),
    ]
