# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-10 13:53


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('proposals', '0002_auto_20170110_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='content_type',
            field=models.ForeignKey(default=77, on_delete=django.db.models.deletion.CASCADE,
                                    to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='object_id',
            field=models.PositiveIntegerField(default=2846),
            preserve_default=False,
        ),
    ]
