# Generated by Django 5.0.9 on 2024-12-13 15:16

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynforms', '0001_initial'),
        ('proposals', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('code', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('score_fields', models.JSONField(blank=True, default=dict, null=True)),
                ('form_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dynforms.formtype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
