# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-10 15:09


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('proposals', '0003_auto_20170110_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='cycle',
            field=models.ForeignKey(default=25, on_delete=django.db.models.deletion.CASCADE, related_name='reviews',
                                    to='proposals.ReviewCycle', verbose_name='Cycle'),
            preserve_default=False,
        ),
    ]
