# Generated by Django 5.0.11 on 2025-02-18 15:20

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facilityconfig',
            options={'get_latest_by': 'start_date', 'ordering': ['-start_date'], 'verbose_name': 'Facility Configuration'},
        ),
        migrations.AddField(
            model_name='facilityconfig',
            name='start_date',
            field=models.DateField(default=datetime.date(2025, 2, 18), verbose_name='Start Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facilityconfig',
            name='cycle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='proposals.reviewcycle', verbose_name='Start Cycle'),
        ),
    ]
