# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-10 16:30


from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('proposals', '0004_review_cycle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='proposal',
        ),
    ]
