# Generated by Django 5.0.9 on 2024-12-13 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0004_reviewtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='proposals.reviewtype'),
            preserve_default=False,
        ),
    ]
