# Generated by Django 5.0.11 on 2025-02-22 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0005_alter_reviewer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewtype',
            name='is_safety',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reviewtype',
            name='is_scientific',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reviewtype',
            name='low_better',
            field=models.BooleanField(default=True, verbose_name='Lower Score Better'),
        ),
        migrations.CreateModel(
            name='ReviewStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('min_reviews', models.IntegerField(default=1, verbose_name='Minimum Reviews')),
                ('blocks', models.BooleanField(default=True)),
                ('pass_score', models.FloatField(blank=True, null=True)),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='proposals.reviewtype')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='proposals.reviewtrack')),
            ],
            options={
                'ordering': ('track', 'position'),
                'unique_together': {('track', 'kind')},
            },
        ),
    ]
