# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-14 21:47


import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('proposals', '0005_remove_review_proposal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewcycle',
            name='spec_date',
        ),
        migrations.AddField(
            model_name='reviewcycle',
            name='alloc_date',
            field=models.DateField(default=datetime.date(2017, 1, 14), verbose_name='Allocation Start'),
            preserve_default=False,
        ),
    ]
