# Generated by Django 5.0.9 on 2024-12-15 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0005_review_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='kind',
            field=models.CharField(choices=[('scientific', 'Scientific Review'), ('technical', 'Technical Review'), ('safety', 'Safety Review'), ('ethics', 'Ethics Review'), ('equipment', 'Equipment Review'), ('approval', 'Safety Approval')], default='scientific', max_length=30, verbose_name='Kind'),
        ),
    ]
