# Generated by Django 5.0.9 on 2024-12-16 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0006_alter_review_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewtype',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
