# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-14 22:43


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('proposals', '0006_auto_20170114_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewcycle',
            name='call_type',
        ),
        migrations.AddField(
            model_name='reviewcycle',
            name='kind',
            field=models.CharField(choices=[('mock', 'Mock Cycle'), ('normal', 'Normal Cycle')], default='normal',
                                   max_length=20, verbose_name='Cycle Type'),
        ),
        migrations.AlterField(
            model_name='reviewcycle',
            name='alloc_date',
            field=models.DateField(verbose_name='Allocation Date'),
        ),
    ]
