# Generated by Django 5.0.11 on 2025-02-22 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0006_reviewtype_is_safety_reviewtype_is_scientific_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewtrack',
            name='duration',
            field=models.IntegerField(default=4, verbose_name='Project Duration (cycles)'),
        ),
        migrations.AddField(
            model_name='reviewtrack',
            name='require_call',
            field=models.BooleanField(default=True, verbose_name='Require Call'),
        ),
    ]
