# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-14 23:24


from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('proposals', '0007_auto_20170114_1643'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewcycle',
            options={'get_latest_by': 'start_date'},
        ),
    ]
