# Generated by Django 5.0.9 on 2024-12-16 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0007_reviewtype_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='score_1',
        ),
        migrations.RemoveField(
            model_name='review',
            name='score_2',
        ),
    ]
