# Generated by Django 5.0.11 on 2025-02-22 19:44

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0007_reviewtrack_duration_reviewtrack_require_call'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewstage',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='reviewstage',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='reviewstage',
            name='blocks',
            field=models.BooleanField(default=True, verbose_name='Block Downstream'),
        ),
        migrations.AlterField(
            model_name='reviewstage',
            name='pass_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Passing Score'),
        ),
        migrations.AlterField(
            model_name='reviewstage',
            name='position',
            field=models.IntegerField(default=0, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='reviewtrack',
            name='duration',
            field=models.IntegerField(default=4, verbose_name='Project Cycles'),
        ),
        migrations.AlterField(
            model_name='reviewtrack',
            name='max_proposals',
            field=models.IntegerField(default=0, verbose_name='Max Workload'),
        ),
        migrations.AlterField(
            model_name='reviewtrack',
            name='min_reviewers',
            field=models.IntegerField(default=0, verbose_name='Min Reviews'),
        ),
        migrations.AlterField(
            model_name='reviewtrack',
            name='notify_offset',
            field=models.IntegerField(default=1, verbose_name='Notify After'),
        ),
    ]
