# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-16 23:21


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('proposals', '0008_auto_20170114_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewcycle',
            name='state',
            field=models.SmallIntegerField(
                choices=[(0, 'Call Pending'), (1, 'Call Open'), (2, 'Assigning'), (3, 'Review'), (4, 'Evaluation'),
                         (5, 'Scheduling'), (6, 'Active'), (7, 'Archived')], default=0),
        ),
    ]
