# Generated by Django 5.0.11 on 2025-02-22 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0008_reviewstage_created_reviewstage_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewstage',
            name='per_facility',
            field=models.BooleanField(default=False, verbose_name='Per Facility'),
        ),
    ]
