# Generated by Django 5.0.9 on 2024-12-16 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0008_remove_review_score_1_remove_review_score_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='kind',
        ),
    ]
