# Generated by Django 5.0.10 on 2024-12-30 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0009_remove_review_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='technique',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='proposals.technique'),
        ),
        migrations.AlterField(
            model_name='technique',
            name='category',
            field=models.CharField(choices=[('diffraction', 'Diffraction/Scattering'), ('imaging', 'Imaging'), ('microscopy', 'Microscopy'), ('spectroscopy', 'Spectroscopy'), ('other', 'Other')], default='other', max_length=50, verbose_name='Category'),
        ),
    ]
