# Generated by Django 5.0.11 on 2025-02-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0009_reviewstage_per_facility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewstage',
            name='per_facility',
        ),
        migrations.AddField(
            model_name='reviewtype',
            name='per_facility',
            field=models.BooleanField(default=False, verbose_name='Per Facility'),
        ),
    ]
