# Generated by Django 5.0.11 on 2025-02-22 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0010_remove_reviewstage_per_facility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='proposals.reviewstage'),
        ),
    ]
