# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-07 17:59


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('proposals', '0010_auto_20170119_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='state',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Started'), (2, 'Reviewed'), (3, 'Complete')],
                                      default=0),
        ),
        migrations.AlterField(
            model_name='submission',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions',
                                    to='proposals.ReviewTrack'),
        ),
    ]
