# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-08 18:41


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('proposals', '0011_auto_20170207_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='score_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='score_2',
            field=models.IntegerField(default=0),
        ),
    ]
