# Generated by Django 5.0.11 on 2025-02-25 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0011_review_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewer',
            name='committee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committee', to='proposals.reviewtrack', verbose_name='Committee Member'),
        ),
    ]
