# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-13 18:26


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('proposals', '0012_auto_20170208_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='reviewer',
        ),
        migrations.AlterField(
            model_name='reviewcycle',
            name='state',
            field=models.SmallIntegerField(
                choices=[(0, 'Call Pending'), (1, 'Call Open'), (2, 'Assigning'), (3, 'Review'), (4, 'Allocation'),
                         (5, 'Scheduling'), (6, 'Active'), (7, 'Archived')], default=0),
        ),
    ]
