# Generated by Django 5.0.11 on 2025-02-25 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0012_alter_reviewer_committee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewtrack',
            name='max_proposals',
            field=models.IntegerField(default=0, verbose_name='Max. Workload'),
        ),
        migrations.AlterField(
            model_name='reviewtrack',
            name='min_reviewers',
            field=models.IntegerField(default=0, verbose_name='Assignment'),
        ),
    ]
