# Generated by Django 5.0.11 on 2025-02-25 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0013_alter_reviewtrack_max_proposals_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewtrack',
            old_name='max_proposals',
            new_name='max_workload',
        ),
    ]
