# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2024-11-08 02:43


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('proposals', '0013_auto_20170213_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='score_1',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='score_2',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='scoreadjustment',
            name='value',
            field=models.FloatField(default=0.5),
        ),
    ]
