# Generated by Django 5.0.11 on 2025-02-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0014_rename_max_proposals_reviewtrack_max_workload'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewer',
            name='declined',
            field=models.DateField(blank=True, null=True),
        ),
    ]
