# Generated by Django 5.0.11 on 2025-02-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0015_reviewer_declined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewtype',
            name='is_safety',
        ),
        migrations.RemoveField(
            model_name='reviewtype',
            name='is_scientific',
        ),
        migrations.AddField(
            model_name='reviewtype',
            name='kind',
            field=models.CharField(choices=[('safety', 'Safety Review'), ('technical', 'Technical Review'), ('scientific', 'Scientific Review'), ('approval', 'Safety Approval')], default='technical', max_length=20),
        ),
    ]
