# Generated by Django 5.0.11 on 2025-03-01 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0016_remove_reviewtype_is_safety_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewer',
            name='declined',
            field=models.DateField(blank=True, null=True, verbose_name='Opt out'),
        ),
    ]
