# Generated by Django 5.0.11 on 2025-03-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0017_alter_reviewer_declined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewer',
            name='declined',
            field=models.DateField(blank=True, null=True, verbose_name='Opted-out'),
        ),
        migrations.AlterField(
            model_name='reviewstage',
            name='blocks',
            field=models.BooleanField(default=True, verbose_name='Block Passage'),
        ),
    ]
