# Generated by Django 5.0.9 on 2024-11-30 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0017_proposal_form_type_review_form_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='spec',
        ),
        migrations.RemoveField(
            model_name='review',
            name='spec',
        ),
    ]
