# Generated by Django 5.0.11 on 2025-06-14 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0018_alter_reviewer_declined_alter_reviewstage_blocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
