# Generated by Django 5.2.3 on 2025-07-01 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0019_alter_proposal_created_alter_proposal_modified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewtrack',
            name='special',
        ),
    ]
