# Generated by Django 5.2.3 on 2025-07-01 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0020_remove_reviewtrack_special'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='proposals.reviewstage'),
        ),
        migrations.AlterField(
            model_name='review',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='proposals.reviewtype'),
        ),
    ]
