# Generated by Django 5.2.3 on 2025-07-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0021_alter_review_stage_alter_review_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewstage',
            name='auto_create',
            field=models.BooleanField(default=True, verbose_name='Create Review Automatically'),
        ),
    ]
