# Generated by Django 5.2.3 on 2025-07-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0022_reviewstage_auto_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewstage',
            name='max_workload',
            field=models.IntegerField(default=0, verbose_name='Max Workload'),
        ),
        migrations.AlterField(
            model_name='reviewstage',
            name='auto_create',
            field=models.BooleanField(default=True, verbose_name='Auto Create'),
        ),
    ]
