# Generated by Django 5.2.3 on 2025-07-07 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0023_reviewstage_max_workload_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewtrack',
            name='max_workload',
        ),
        migrations.RemoveField(
            model_name='reviewtrack',
            name='min_reviewers',
        ),
    ]
