# Generated by Django 5.2.3 on 2025-07-08 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0024_remove_reviewtrack_max_workload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='state',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Started'), (2, 'Reviewed'), (3, 'Complete'), (4, 'Approved'), (5, 'Rejected')], default=0),
        ),
    ]
