# Generated by Django 5.2.3 on 2025-07-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0025_alter_submission_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewstage',
            name='auto_start',
            field=models.BooleanField(default=True, verbose_name='Auto Start'),
        ),
    ]
