# Generated by Django 5.2.3 on 2025-07-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0026_reviewstage_auto_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='approved',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
