# Generated by Django 5.2.3 on 2025-07-09 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0027_submission_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewcycle',
            name='state',
            field=models.SmallIntegerField(choices=[(0, 'Call Pending'), (1, 'Call Open'), (2, 'Assigning'), (3, 'Review'), (4, 'Evaluation'), (5, 'Scheduling'), (6, 'Active'), (7, 'Archived')], default=0),
        ),
        migrations.AlterField(
            model_name='submission',
            name='state',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Started'), (2, 'Reviewed'), (3, 'Complete')], default=0),
        ),
        migrations.AlterUniqueTogether(
            name='configitem',
            unique_together={('config', 'technique', 'track')},
        ),
    ]
