# Generated by Django 5.2.3 on 2025-07-10 05:11

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0028_alter_reviewcycle_state_alter_submission_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('role', models.CharField(max_length=128, blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='submission',
            name='kind',
            field=models.CharField(choices=[
                ('user', 'General Access'), ('staff', 'Staff Access'), ('purchased', 'Purchased Access'),
                ('beamteam', 'Beam Team'), ('education', 'Education/Outreach')
            ], default='user', max_length=20, verbose_name='Access Type'),
        ),
    ]
