# Generated by Django 5.2.3 on 2025-07-10 05:11

from django.db import migrations


def add_initial_pool(apps, schema_editor):
    AccessPool = apps.get_model('proposals', 'AccessPool')
    AccessPool.objects.get_or_create(
        name='General Access',
        defaults={
            'description': 'Default access pool for proposals available to everyone.',
            'role': '',
            'is_default': True
        }
    )


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0029_accesspool'),
    ]

    operations = [
        migrations.RunPython(add_initial_pool, migrations.RunPython.noop),
    ]
