# Generated by Django 5.2.3 on 2025-07-10 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0030_auto_20250709_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='pool',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='submissions', to='proposals.accesspool'),
        ),
    ]
