# Generated by Django 5.2.3 on 2025-07-10 05:32

from django.db import migrations


def create_pools(apps, schema_editor):
    Submission = apps.get_model('proposals', 'Submission')
    AccessPool = apps.get_model('proposals', 'AccessPool')

    # Create pools based on existing TYPES and update submissions
    kind_field = Submission._meta.get_field('kind')
    for code, name in kind_field.choices:
        pool, created = AccessPool.objects.get_or_create(
            name=name,
            defaults={
                'description': f'Pool for {name} beam time',
                'role': '',
                'is_default': False
            }
        )
        Submission.objects.filter(kind=code).update(pool=pool)


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0031_submission_pool'),
    ]

    operations = [
        migrations.RunPython(create_pools, reverse_code=migrations.RunPython.noop),
    ]
