# Generated by Django 5.2.3 on 2025-07-10 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0032_auto_20250709_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='kind',
        ),
    ]
