# Generated by Django 5.2.3 on 2025-07-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0033_remove_submission_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewstage',
            name='weight',
            field=models.FloatField(default=1.0, verbose_name='Weight'),
        ),
    ]
