# Generated by Django 5.2.3 on 2025-07-14 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0034_reviewstage_weight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesspool',
            options={'ordering': ['is_default']},
        ),
    ]
