# Generated by Django 5.2.3 on 2025-07-15 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0035_alter_accesspool_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScoreAdjustment',
        ),
    ]
