# Generated by Django 5.2.3 on 2025-07-15 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0036_delete_scoreadjustment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configitem',
            name='state',
        ),
    ]
