# Generated by Django 5.2.3 on 2025-07-16 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0037_remove_configitem_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='_code',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='_code',
            field=models.SlugField(blank=True),
        ),
    ]
