# Generated by Django 5.2.3 on 2025-07-16 04:53

from django.db import migrations
from misc import utils


def create_codes(apps, schema_editor):
    Proposal = apps.get_model('proposals', 'Proposal')
    Submission = apps.get_model('proposals', 'Submission')

    # loop through and calculate the code for each proposal and submission
    proposal_code_func = utils.get_code_generator('PROPOSAL')

    all_proposals = Proposal.objects.all()
    for project in all_proposals:
        project._code = proposal_code_func(project)
    Proposal.objects.bulk_update(all_proposals, ['_code'])

    submission_code_func = utils.get_code_generator('SUBMISSION')
    all_submissions = Submission.objects.all()
    for submission in all_submissions:
        submission._code = submission_code_func(submission)
    Submission.objects.bulk_update(all_submissions, ['_code'])


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0038_proposal__code_submission__code'),
    ]

    operations = [
        migrations.RunPython(create_codes, migrations.RunPython.noop),
    ]
