# Generated by Django 5.2.3 on 2025-07-16 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0039_auto_20250715_2253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='_code',
            new_name='code',
        ),
    ]
