# Generated by Django 5.2.3 on 2025-07-16 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0040_rename__code_proposal_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='code',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='code',
            field=models.SlugField(unique=True),
        ),
    ]
