# Generated by Django 5.2.3 on 2025-07-16 13:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0041_alter_proposal_code_alter_submission_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='code',
            field=models.SlugField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='code',
            field=models.SlugField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
