# Generated by Django 5.2.3 on 2025-07-24 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0042_alter_proposal_code_alter_submission_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewcycle',
            name='state',
            field=models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Open'), (2, 'Assigning'), (3, 'Review'), (4, 'Evaluation'), (5, 'Scheduling'), (6, 'Active'), (7, 'Archived')], default=0),
        ),
    ]
