# Generated by Django 5.2.3 on 2025-07-27 04:40

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0043_alter_reviewcycle_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text='Name of the cycle type', max_length=100, unique=True)),
                ('start_date', models.DateField()),
                ('duration', models.IntegerField(default=6, help_text='Duration in months')),
                ('call_week', models.IntegerField(default=0, help_text='Week Number')),
                ('review_duration', models.IntegerField(default=6, help_text='Duration in weeks for review')),
                ('allocation_offset', models.IntegerField(default=2, help_text='Offset in weeks for allocation')),
                ('open_on', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=2, help_text='Week day')),
                ('close_on', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=2, help_text='Week day')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
