# Generated by Django 5.2.3 on 2025-07-27 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0044_cycletype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cycletype',
            name='call_week',
        ),
        migrations.AddField(
            model_name='cycletype',
            name='active',
            field=models.BooleanField(default=True, help_text='Is this cycle type active?'),
        ),
        migrations.AddField(
            model_name='cycletype',
            name='call_offset',
            field=models.IntegerField(default=21, help_text='Weeks before start date'),
        ),
        migrations.AlterField(
            model_name='cycletype',
            name='start_date',
            field=models.DateField(help_text='Year ignored, only month and day are used'),
        ),
    ]
