# Generated by Django 5.2.3 on 2025-07-27 04:49

from django.db import migrations


def create_cycle_types(apps, schema_editor):
    CycleType = apps.get_model('proposals', 'CycleType')
    CycleType.objects.get_or_create(
        name='Jan-Jun',
        defaults={
            'start_date': '2025-01-01',
            'duration': 6,
            'call_offset': 21,
            'review_duration': 6,
            'allocation_offset': 2,
            'open_on': 2,
            'close_on': 2,
            'active': True,
        }
    )
    CycleType.objects.get_or_create(
        name='Jul-Dec',
        defaults={
            'start_date': '2025-07-01',
            'duration': 6,
            'call_offset': 21,
            'review_duration': 6,
            'allocation_offset': 2,
            'open_on': 2,
            'close_on': 2,
            'active': True,
        }
    )


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0045_remove_cycletype_call_week_cycletype_active_and_more'),
    ]

    operations = [
        migrations.RunPython(create_cycle_types, migrations.RunPython.noop),
    ]
