# Generated by Django 5.2.3 on 2025-07-27 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0046_auto_20250726_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewcycle',
            name='kind',
        ),
        migrations.AddField(
            model_name='reviewcycle',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cycles', to='proposals.cycletype'),
        ),
    ]
