# Generated by Django 5.2.3 on 2025-07-27 05:11

from django.db import migrations


def set_cycle_type(apps, schema_editor):
    ReviewCycle = apps.get_model('proposals', 'ReviewCycle')
    CycleType = apps.get_model('proposals', 'CycleType')

    # Set the cycle type for existing review cycles
    to_update = ReviewCycle.objects.filter(type__isnull=True)
    default_cycle_type = CycleType.objects.first()  # Assuming you want to set it to the first available type by default
    for cycle in to_update:
        cycle.type = CycleType.objects.filter(start_date__month=cycle.start_date.month).first() or default_cycle_type
    ReviewCycle.objects.bulk_update(to_update, ['type'])


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0047_remove_reviewcycle_kind_reviewcycle_type'),
    ]

    operations = [
        migrations.RunPython(set_cycle_type, migrations.RunPython.noop),
    ]
