# Generated by Django 5.2.3 on 2025-07-27 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0048_auto_20250726_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewcycle',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='cycles', to='proposals.cycletype'),
            preserve_default=False,
        ),
    ]
