# Generated by Django 5.2.3 on 2025-07-27 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0049_alter_reviewcycle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycletype',
            name='call_period',
            field=models.IntegerField(default=4, help_text='Duration of call in weeks'),
        ),
        migrations.AlterField(
            model_name='cycletype',
            name='review_duration',
            field=models.IntegerField(default=6, help_text='Review period in weeks'),
        ),
        migrations.AlterField(
            model_name='cycletype',
            name='start_date',
            field=models.DateField(help_text='Year ignored'),
        ),
    ]
