# Generated by Django 5.2.3 on 2025-07-27 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0050_cycletype_call_period_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewcycle',
            options={'get_latest_by': 'start_date', 'verbose_name': 'Cycle'},
        ),
    ]
