# Generated by Django 5.2.3 on 2025-07-27 16:43

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0051_alter_reviewcycle_options'),
        ('scheduler', '0009_auto_20250705_1752'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reviewcycle',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='reviewcycle',
            constraint=models.UniqueConstraint(models.F('type'), django.db.models.functions.datetime.ExtractYear('start_date'), name='unique_cycle_type_per_year'),
        ),
    ]
