# Generated by Django 5.2.3 on 2025-07-27 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0052_alter_reviewcycle_unique_together_and_more'),
        ('scheduler', '0009_auto_20250705_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycletype',
            name='shifts',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='cycle_types', to='scheduler.shiftconfig'),
        ),
    ]
