# Generated by Django 5.2.4 on 2025-08-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0053_cycletype_shifts'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='_team',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
