# Generated by Django 5.2.4 on 2025-08-16 17:04

from django.db import migrations


def copy_team(apps, schema_editor):
    Proposal = apps.get_model('proposals', 'Proposal')
    to_update = Proposal.objects.filter(team__isnull=False)
    for proposal in to_update:
        proposal._team = proposal.team

    Proposal.objects.bulk_update(to_update, ['_team'])


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0054_proposal__team'),
    ]

    operations = [
        migrations.RunPython(copy_team, reverse_code=migrations.RunPython.noop),
    ]
