# Generated by Django 5.2.4 on 2025-08-16 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0055_auto_20250816_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='team',
        ),
    ]
