# Generated by Django 5.2.4 on 2025-08-16 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0056_remove_proposal_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='_team',
            new_name='team',
        ),
    ]
