# Generated by Django 5.2.5 on 2025-09-04 15:47

from django.db import migrations


def fix_cycle_schedules(apps, schema_editor):
    ReviewCycle = apps.get_model('proposals', 'ReviewCycle')

    for cycle in ReviewCycle.objects.all():
        schedule = cycle.schedule
        schedule.start_date = cycle.start_date
        schedule.end_date = cycle.end_date
        schedule.description = f"{cycle.start_date:%Y} {cycle.type.name}: Schedule"
        schedule.save()


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0057_rename__team_proposal_team'),
    ]

    operations = [
        migrations.RunPython(fix_cycle_schedules, reverse_code=migrations.RunPython.noop),
    ]
