# Generated by Django 5.2.4 on 2025-09-22 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0058_fix_cycle_schedules'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesspool',
            name='tracks',
            field=models.ManyToManyField(blank=True, related_name='pools', to='proposals.reviewtrack'),
        ),
    ]
