# Generated by Django 5.2.4 on 2025-09-22 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0059_accesspool_tracks'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesspool',
            name='code',
            field=models.CharField(default='G', max_length=5),
        ),
    ]
