# Generated by Django 5.2.4 on 2025-09-22 02:24

from django.db import migrations


def populate_pool_code(apps, schema_editor):
    AccessPool = apps.get_model('proposals', 'AccessPool')
    for pool in AccessPool.objects.all():
        pool.code = pool.name[0].upper()
        pool.save(update_fields=['code'])


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0060_accesspool_code'),
    ]

    operations = [
        migrations.RunPython(populate_pool_code),
    ]
