# Generated by Django 5.2.4 on 2025-09-23 01:11

from django.db import migrations


def add_tracks_to_pools(apps, schema_editor):
    AccessPool = apps.get_model('proposals', 'AccessPool')
    Track = apps.get_model('proposals', 'ReviewTrack')

    for pool in AccessPool.objects.all():
        if pool.is_default:
            pool.tracks.add(*Track.objects.filter(require_call=True))
        else:
            pool.tracks.add(*Track.objects.filter(require_call=False))


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0061_populate_pool_code'),
    ]

    operations = [
        migrations.RunPython(add_tracks_to_pools, reverse_code=migrations.RunPython.noop),
    ]
