# Generated by Django 5.2.4 on 2025-09-23 01:11
from django.core import serializers
from django.db import migrations
import os


def load_fixture(apps, schema_editor):
    fixture_path = os.path.join(
        os.path.dirname(__file__),
        '..',
        'fixtures',
        '002-pools.yml'
    )
    db_alias = schema_editor.connection.alias
    if not os.path.exists(fixture_path):
        return

    with open(fixture_path, 'r') as fixture_file:
        objects = serializers.deserialize('yaml', fixture_file)
        for obj in objects:
            obj.save(using=db_alias)


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0061_populate_pool_code'),
    ]

    operations = [
        migrations.RunPython(load_fixture, reverse_code=migrations.RunPython.noop),
    ]
