# Generated by Django 5.2.6 on 2025-09-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0061_populate_pool_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewtrack',
            name='reviewers',
            field=models.ManyToManyField(blank=True, related_name='tracks', to='proposals.reviewer'),
        ),
    ]
