# Generated by Django 5.0.10 on 2024-12-30 20:08

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('city_code', models.CharField(max_length=20, unique=True)),
                ('city_name', models.CharField(max_length=100)),
                ('conditions', models.JSONField()),
            ],
            options={
                'verbose_name': 'Weather Location',
                'verbose_name_plural': 'Weather Locations',
            },
        ),
    ]
