# Generated by Django 5.2.3 on 2025-06-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weather',
            options={'verbose_name': 'Weather Data', 'verbose_name_plural': 'Weather Data'},
        ),
        migrations.RemoveField(
            model_name='weather',
            name='city_code',
        ),
        migrations.AddField(
            model_name='weather',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='city_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='conditions',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
