# Generated by Django 5.0.9 on 2024-11-30 21:18

import django.db.models.deletion
import django.utils.timezone
import misc.fields
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dynforms', '0001_initial'),
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('address_1', models.CharField(max_length=255, verbose_name='Department')),
                ('address_2', models.CharField(blank=True, max_length=255, verbose_name='Street')),
                ('address_3', models.CharField(blank=True, max_length=255, verbose_name='Place')),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Province/State/Region')),
                ('postal_code', models.CharField(blank=True, max_length=100, verbose_name='Postal/Zip Code')),
                ('country', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('sector', models.CharField(blank=True, choices=[('k12', 'K-12 Academic'), ('academic', 'Post-Secondary Academic'), ('research', 'Research'), ('synchrotron', 'Synchrotron'), ('government', 'Government'), ('industry', 'Industry')], max_length=20, null=True)),
                ('domains', misc.fields.StringListField(blank=True, null=True, verbose_name='Institutional Email Suffixes')),
                ('state', models.CharField(choices=[('new', 'New'), ('pending', 'Pending'), ('started', 'Started'), ('active', 'Active'), ('exempt', 'Exempt'), ('expired', 'Expired')], default='new', max_length=20, verbose_name='Agreement')),
                ('contact_person', models.CharField(blank=True, max_length=200, verbose_name='Contact Person')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Contact Email')),
                ('contact_phone', models.CharField(blank=True, max_length=50, verbose_name='Contact Phone')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.institution', verbose_name='Parent Institution')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('username', models.SlugField(unique=True)),
                ('classification', models.CharField(blank=True, choices=[('student', 'K-12 Student'), ('undergraduate', 'Undergraduate Student'), ('masters', 'Masters Student'), ('doctorate', 'Doctorate Student'), ('postdoc', 'Post Doctorate'), ('faculty', 'Faculty'), ('professional', 'Professional'), ('other', 'Other')], max_length=20, null=True)),
                ('alt_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Alternate Email')),
                ('title', models.CharField(blank=True, choices=[('Prof', 'Prof'), ('Mr', 'Mr'), ('Ms', 'Ms'), ('Dr', 'Dr'), ('Sr', 'Sir')], max_length=20, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('preferred_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Preferred First Name')),
                ('other_names', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('photo', models.URLField(blank=True, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='Emergency Contact (Full Name)')),
                ('emergency_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('roles', misc.fields.StringListField(blank=True)),
                ('permissions', misc.fields.StringListField(blank=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('research_field', models.ManyToManyField(blank=True, to='publications.subjectarea')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.address')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.institution')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('details', models.JSONField(blank=True, default=dict, editable=False, null=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('hash', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(max_length=250)),
                ('form_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dynforms.formtype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SecureLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('hash', models.CharField(max_length=50, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
