# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-19 05:02


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='institution',
            name='contact_person',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='institution',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
