# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-19 13:28


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_auto_20170118_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name=b'Contact Email'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='contact_person',
            field=models.CharField(blank=True, max_length=200, verbose_name=b'Contact Person'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name=b'Contact Phone'),
        ),
    ]
