# Generated by Django 5.0.11 on 2025-06-14 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
