# Generated by Django 5.2.3 on 2025-07-15 14:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_registration_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default=uuid.uuid4, max_length=254, unique=True),
        ),
    ]
