# Generated by Django 5.2.5 on 2025-09-02 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The common name of the country.', max_length=100, unique=True)),
                ('alpha2', models.CharField(help_text='Two-letter country code.', max_length=2, unique=True, verbose_name='ISO 3166-1 alpha-2')),
                ('alpha3', models.CharField(help_text='Three-letter country code.', max_length=3, unique=True, verbose_name='ISO 3166-1 alpha-3')),
                ('numeric_code', models.CharField(blank=True, help_text='Three-digit country code.', max_length=3, null=True, unique=True, verbose_name='ISO 3166-1 numeric code')),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='ISO 3166-2 code')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='users.country')),
            ],
            options={
                'verbose_name_plural': 'Regions',
                'ordering': ['country__name', 'name'],
                'unique_together': {('country', 'name')},
            },
        ),
    ]
