# Generated by Django 5.2.5 on 2025-09-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_country_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='numeric_code',
            new_name='code',
        ),
        migrations.AddField(
            model_name='region',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='region',
            name='lon',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
    ]
