# Generated by Django 3.2.4 on 2024-11-13 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20241107_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.AlterField(
            model_name='institution',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Contact Email'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='contact_person',
            field=models.CharField(blank=True, max_length=200, verbose_name='Contact Person'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Contact Phone'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.institution', verbose_name='Parent Institution'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='sector',
            field=models.CharField(blank=True, choices=[('k12', 'K-12 Academic'), ('academic', 'Post-Secondary Academic'), ('research', 'Research'), ('synchrotron', 'Synchrotron'), ('government', 'Government'), ('industry', 'Industry')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='state',
            field=models.CharField(choices=[('new', 'New'), ('pending', 'Pending'), ('started', 'Started'), ('active', 'Active'), ('exempt', 'Exempt'), ('expired', 'Expired')], default='new', max_length=20, verbose_name='Agreement'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='classification',
            field=models.CharField(blank=True, choices=[('student', 'K-12 Student'), ('undergraduate', 'Undergraduate Student'), ('masters', 'Masters Student'), ('doctorate', 'Doctorate Student'), ('postdoc', 'Post Doctorate'), ('faculty', 'Faculty'), ('professional', 'Professional'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, choices=[('Prof', 'Prof'), ('Mr', 'Mr'), ('Ms', 'Ms'), ('Dr', 'Dr'), ('Sr', 'Sir')], max_length=20, null=True),
        ),
    ]
