# Generated by Django 5.2.4 on 2025-09-02 23:16

import os
from django.db import migrations
from django.core import serializers


def load_fixture(apps, schema_editor):
    fixture_path = os.path.join(
        os.path.dirname(__file__),
        '..',
        'fixtures',
        'country-regions.yml'
    )
    with open(fixture_path, 'r') as fixture_file:
        objects = serializers.deserialize('yaml', fixture_file)
        for obj in objects:
            obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_numeric_code_country_code_region_lat_and_more'),
    ]

    operations = [
        migrations.RunPython(load_fixture, reverse_code=migrations.RunPython.noop),
    ]
