# Generated by Django 5.0.9 on 2024-11-14 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_registration_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cfactor',
        ),
    ]
