# Generated by Django 5.2.4 on 2025-09-03 00:39

from django.db import migrations
from thefuzz import process


def populate_address_country(apps, schema_editor):
    Address = apps.get_model('users', 'Address')
    Country = apps.get_model('users', 'Country')

    countries = Country.objects.in_bulk(field_name='name')
    addresses = Address.objects.all()
    country_search = countries.keys()
    for address in addresses:
        c_name, score = process.extractOne(address.country, country_search)
        c = countries[c_name]
        regions = {c.name: c for c in c.regions.all()}
        r_name, score = process.extractOne(address.region, regions.keys())
        r = regions[r_name]
        address._country = c
        address._region = r
    Address.objects.bulk_update(addresses, ['_country', '_region'], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_address__country_address__region'),
    ]

    operations = [
        migrations.RunPython(populate_address_country, reverse_code=migrations.RunPython.noop),
    ]
