# Generated by Django 5.0.9 on 2024-11-30 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_registration_form_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='spec',
        ),
    ]
