# Generated by Django 5.2.4 on 2025-09-03 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_populate_address_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
        migrations.RemoveField(
            model_name='address',
            name='region',
        ),
    ]
