# Generated by Django 5.2.4 on 2025-09-03 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_address_country_remove_address_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='_country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='_region',
            new_name='region',
        ),
    ]
