# Generated by Django 5.2.4 on 2025-09-03 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename__country_address_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='_city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.country'),
        ),
        migrations.AddField(
            model_name='institution',
            name='_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.region'),
        ),
    ]
