# Generated by Django 5.2.4 on 2025-09-03 02:47

from django.db import migrations
from thefuzz import process


def populate_institution_address(apps, schema_editor):
    Institution = apps.get_model('users', 'Institution')
    Country = apps.get_model('users', 'Country')

    countries = Country.objects.in_bulk(field_name='name')
    institutions = Institution.objects.all()
    country_search = countries.keys()
    for inst in institutions:
        country = inst.location.split(',')[-1].strip() if inst.location else ''
        if not country:
            continue
        c_name, score = process.extractOne(country, country_search)
        c = countries[c_name]
        inst._country = c
        regions = {c.name: c for c in c.regions.all()}
        region = inst.location.split(',')[-2].strip() if len(inst.location.split(',')) > 1 else ''
        if not region:
            continue
        r_name, score = process.extractOne(region, regions.keys())
        r = regions[r_name]
        inst._region = r

    Institution.objects.bulk_update(institutions, ['_country', '_region'], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_institution__city_institution__country_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_institution_address, reverse_code=migrations.RunPython.noop),
    ]
