# Generated by Django 5.2.4 on 2025-09-03 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_populate_institution_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institution',
            old_name='_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='institution',
            old_name='_country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='institution',
            old_name='_region',
            new_name='region',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='location',
        ),
    ]
