# Generated by Django 5.2.6 on 2025-09-08 21:59

from django.db import migrations, models


def populate_roles(apps, schema_editor):
    User = apps.get_model('users', 'User')
    Institution = apps.get_model('users', 'Institution')
    db_alias = schema_editor.connection.alias
    to_update = Institution.objects.using(db_alias).all()
    for item in to_update:
        item._domains = item.domains

    Institution.objects.using(db_alias).bulk_update(to_update, ['_domains'])

    to_update = User.objects.using(db_alias).all()
    for item in to_update:
        item._permissions = item.permissions
        item._roles = item.roles
    User.objects.using(db_alias).bulk_update(to_update, ['_permissions', '_roles'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_rename__city_institution_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='_domains',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='_permissions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='_roles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(populate_roles, reverse_code=migrations.RunPython.noop),
    ]
