# Generated by Django 5.2.4 on 2025-09-08 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_institution__domains_user__permissions_user__roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='domains',
        ),
        migrations.RemoveField(
            model_name='user',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='user',
            name='roles',
        ),
        migrations.RenameField(
            model_name='institution',
            old_name='_domains',
            new_name='domains',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='_permissions',
            new_name='permissions',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='_roles',
            new_name='roles',
        ),
    ]
