# Generated by Django 5.2.6 on 2025-09-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_and_rename_json_fields_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='classification',
            field=models.CharField(choices=[('student', 'K-12 Student'), ('undergraduate', 'Undergraduate Student'), ('masters', 'Masters Student'), ('doctorate', 'Doctorate Student'), ('postdoc', 'Post Doctorate'), ('faculty', 'Faculty'), ('professional', 'Professional'), ('other', 'Other')], default='professional', max_length=20),
        ),
    ]
