# Generated by Django 5.0.10 on 2024-12-30 20:08

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hazard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('signal', models.CharField(blank=True, choices=[('warning', 'Warning'), ('danger', 'Danger')], max_length=10)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='HStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('text', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pictogram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('code', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('text', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SafetyControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('team', 'Team Requirements'), ('guide', 'Safety Instructions'), ('ppe', 'Personal Protection Equipment'), ('form', 'Forms'), ('delivery', 'Material Delivery/Removal'), ('signage', 'Signage and Permits'), ('disposal', 'Disposal and Storage')], default='guide', max_length=20)),
                ('kind', models.CharField(choices=[('engineering', 'Engineering Controls'), ('ppe', 'Personal Protection Equipment'), ('inspection', 'Equipment Inspection'), ('administrative', 'Administrative Controls'), ('other', 'Other Controls')], default='engineering', max_length=20)),
                ('active', models.BooleanField(default=True, verbose_name='Show in Review')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SafetyPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('code', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('review', models.BooleanField(default=True, verbose_name='Show in Review')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('object_id', models.PositiveIntegerField()),
                ('kind', models.CharField(choices=[('any', 'Anyone'), ('all', 'Everyone'), ('optional', 'Optional')], max_length=20, verbose_name='Type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HazardousSubstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('description', models.TextField()),
                ('hazards', models.ManyToManyField(related_name='substances', to='samples.hazard', verbose_name='Hazards')),
            ],
        ),
        migrations.AddField(
            model_name='hazard',
            name='hazard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samples.hstatement'),
        ),
        migrations.AddField(
            model_name='hazard',
            name='pictograms',
            field=models.ManyToManyField(related_name='hazards', to='samples.pictogram'),
        ),
        migrations.AddField(
            model_name='hazard',
            name='precautions',
            field=models.ManyToManyField(related_name='hazards', to='samples.pstatement'),
        ),
        migrations.AddField(
            model_name='hazard',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='hazards', to='samples.safetypermission'),
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('source', models.CharField(blank=True, max_length=100, null=True, verbose_name='Source of Material')),
                ('extra', models.CharField(blank=True, max_length=100, null=True, verbose_name='Additional Information')),
                ('kind', models.CharField(choices=[('', ''), ('chemical', 'Chemical'), ('macromolecule', 'Macromolecules'), ('geologic', 'Soil, rocks or geologic'), ('Human', [('human_subject', 'Human Subject'), ('human_tissue_alive', 'Human Tissue/Fluid (Living)'), ('human_tissue', 'Human Tissue/Fluid'), ('human_other', 'Other Human Material')]), ('Animal', [('live_animal', 'Live Animal'), ('animal_tissue', 'Non-Invasive Animal Tissue/Fluid (Cat A)'), ('animal_tissue_invasive', 'Invasive Animal Tissue/Fluid (Cat B+)'), ('animal_other', 'Other Animal Material')]), ('Other Biological', [('plant', 'Plant or Algae'), ('microbe', 'Bacteria, Protozoa or Virus'), ('fungi', 'Fungi'), ('gmo', 'Genetically Modified Organism'), ('bio_other', 'Other biological')]), ('other', 'Other')], default=None, max_length=100, verbose_name='Type')),
                ('state', models.CharField(choices=[('', ''), ('solid', 'Solid'), ('liquid', 'Liquid'), ('crystal', 'Crystal'), ('gas', 'Gas'), ('frozen', 'Frozen'), ('suspension', 'Suspension'), ('nano', 'Nano-Material'), ('fixed', 'Fixed'), ('sealed', 'Sealed Radioactive Source'), ('other', 'Other State')], default=None, max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_editable', models.BooleanField(default=True)),
                ('details', models.JSONField(blank=True, default=dict, editable=False, null=True)),
                ('hazard_types', models.ManyToManyField(related_name='samples', to='samples.pictogram', verbose_name='Hazard Types')),
                ('hazards', models.ManyToManyField(related_name='samples', to='samples.hazard', verbose_name='Hazards')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
