# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-10 13:40


import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='samples',
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hazardoussubstance',
            name='hazards',
            field=models.ManyToManyField(related_name='substances', to='samples.Hazard', verbose_name=b'Hazards'),
        ),
        migrations.AddField(
            model_name='hazard',
            name='hazard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samples.HStatement'),
        ),
        migrations.AddField(
            model_name='hazard',
            name='pictograms',
            field=models.ManyToManyField(related_name='hazards', to='samples.Pictogram'),
        ),
        migrations.AddField(
            model_name='hazard',
            name='precautions',
            field=models.ManyToManyField(related_name='hazards', to='samples.PStatement'),
        ),
        migrations.AlterUniqueTogether(
            name='hazard',
            unique_together=set([('signal', 'hazard')]),
        ),
    ]
