# Generated by Django 5.0.11 on 2025-06-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='hazards',
            field=models.ManyToManyField(blank=True, related_name='samples', to='samples.hazard', verbose_name='Hazards'),
        ),
    ]
