# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-16 23:21


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('samples', '0002_auto_20170110_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='state',
            field=models.CharField(
                choices=[(b'', b''), (b'solid', 'Solid'), (b'liquid', 'Liquid'), (b'crystal', 'Crystal'),
                         (b'gas', 'Gas'), (b'frozen', 'Frozen'), (b'suspension', 'Suspension'),
                         (b'nano', 'Nano-Material'), (b'fixed', 'Fixed'), (b'sealed', 'Sealed Radioactive Source'),
                         (b'other', 'Other State')], default=None, max_length=100),
        ),
    ]
