# Generated by Django 5.2.3 on 2025-07-01 17:36

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0003_alter_sample_hazards'),
    ]

    operations = [
        migrations.AddField(
            model_name='hazardoussubstance',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='hazardoussubstance',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='safetypermission',
            name='code',
            field=models.SlugField(),
        ),
    ]
