# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-17 13:39


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('samples', '0003_auto_20170116_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='safetypermission',
            name='review',
            field=models.BooleanField(default=True, verbose_name='Show in Review'),
        ),
    ]
