# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-07 18:02


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('samples', '0005_safetycontrol_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='hazard',
            name='permissions',
            field=models.ManyToManyField(related_name='hazards', to='samples.SafetyPermission'),
        ),
    ]
