# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-08 18:41


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('samples', '0006_hazard_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hazard',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='hazards', to='samples.SafetyPermission'),
        ),
    ]
