# Generated by Django 3.2.4 on 2024-11-13 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('samples', '0007_auto_20170208_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hazard',
            name='signal',
            field=models.CharField(blank=True, choices=[('warning', 'Warning'), ('danger', 'Danger')], max_length=10),
        ),
        migrations.AlterField(
            model_name='hazardoussubstance',
            name='hazards',
            field=models.ManyToManyField(related_name='substances', to='samples.Hazard', verbose_name='Hazards'),
        ),
        migrations.AlterField(
            model_name='hazardoussubstance',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='safetycontrol',
            name='category',
            field=models.CharField(choices=[('team', 'Team Requirements'), ('guide', 'Safety Instructions'), ('ppe', 'Personal Protection Equipment'), ('form', 'Forms'), ('delivery', 'Material Delivery/Removal'), ('signage', 'Signage and Permits'), ('disposal', 'Disposal and Storage')], default='guide', max_length=20),
        ),
        migrations.AlterField(
            model_name='safetycontrol',
            name='kind',
            field=models.CharField(choices=[('engineering', 'Engineering Controls'), ('ppe', 'Personal Protection Equipment'), ('inspection', 'Equipment Inspection'), ('administrative', 'Administrative Controls'), ('other', 'Other Controls')], default='engineering', max_length=20),
        ),
        migrations.AlterField(
            model_name='sample',
            name='extra',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Additional Information'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='hazard_types',
            field=models.ManyToManyField(related_name='samples', to='samples.Pictogram', verbose_name='Hazard Types'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='hazards',
            field=models.ManyToManyField(related_name='samples', to='samples.Hazard', verbose_name='Hazards'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='kind',
            field=models.CharField(choices=[('', ''), ('chemical', 'Chemical'), ('macromolecule', 'Macromolecules'), ('geologic', 'Soil, rocks or geologic'), ('Human', [('human_subject', 'Human Subject'), ('human_tissue_alive', 'Human Tissue/Fluid (Living)'), ('human_tissue', 'Human Tissue/Fluid'), ('human_other', 'Other Human Material')]), ('Animal', [('live_animal', 'Live Animal'), ('animal_tissue', 'Non-Invasive Animal Tissue/Fluid (Cat A)'), ('animal_tissue_invasive', 'Invasive Animal Tissue/Fluid (Cat B+)'), ('animal_other', 'Other Animal Material')]), ('Other Biological', [('plant', 'Plant or Algae'), ('microbe', 'Bacteria, Protozoa or Virus'), ('fungi', 'Fungi'), ('gmo', 'Genetically Modified Organism'), ('bio_other', 'Other biological')]), ('other', 'Other')], default=None, max_length=100, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sample',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Source of Material'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='state',
            field=models.CharField(choices=[('', ''), ('solid', 'Solid'), ('liquid', 'Liquid'), ('crystal', 'Crystal'), ('gas', 'Gas'), ('frozen', 'Frozen'), ('suspension', 'Suspension'), ('nano', 'Nano-Material'), ('fixed', 'Fixed'), ('sealed', 'Sealed Radioactive Source'), ('other', 'Other State')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='userrequirement',
            name='kind',
            field=models.CharField(choices=[('any', 'Anyone'), ('all', 'Everyone'), ('optional', 'Optional')], max_length=20, verbose_name='Type'),
        ),
    ]
