# coding=utf-8



COUNTRIES = [
    'Afghanistan', 'Albania', 'Algeria', 'American Samoa', 'Andorra', 'Angola', 'Anguilla',
    'Antarctica', 'Antigua and Barbuda', 'Argentina', 'Armenia', 'Aruba', 'Australia', 'Austria',
    'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize',
    'Benin', 'Bermuda', 'Bhutan', 'Bolivia', 'Bonaire, Sint Eustatius and Saba',
    'Bosnia and Herzegovina', 'Botswana', 'Bouvet Island', 'Brazil', 'British Indian Ocean Territory',
    'Brunei Darussalam', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cambodia', 'Cameroon', 'Canada',
    'Cape Verde', 'Cayman Islands', 'Central African Republic', 'Chad', 'Chile', 'China',
    'Christmas Island', 'Cocos (Keeling) Islands', 'Colombia', 'Comoros',
    'Congo, Republic of the (Brazzaville)', 'Congo, the Democratic Republic of the (Kinshasa)',
    'Cook Islands', 'Costa Rica', 'Croatia', 'Cuba', 'Cura\xe7ao', 'Cyprus', 'Czech Republic',
    "C\xf4te d'Ivoire, Republic of", 'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic', 'Ecuador',
    'Egypt', 'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia', 'Ethiopia',
    'Falkland Islands (Islas Malvinas)', 'Faroe Islands', 'Fiji', 'Finland', 'France', 'French Guiana',
    'French Polynesia', 'French Southern and Antarctic Lands', 'Gabon', 'Gambia, The', 'Georgia',
    'Germany', 'Ghana', 'Gibraltar', 'Greece', 'Greenland', 'Grenada', 'Guadeloupe', 'Guam',
    'Guatemala', 'Guernsey', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti',
    'Heard Island and McDonald Islands', 'Holy See (Vatican City)', 'Honduras', 'Hong Kong', 'Hungary',
    'Iceland', 'India', 'Indonesia', 'Iran, Islamic Republic of', 'Iraq', 'Ireland', 'Isle of Man',
    'Israel', 'Italy', 'Jamaica', 'Japan', 'Jersey', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati',
    "Korea, Democratic People's Republic of", 'Korea, Republic of', 'Kuwait', 'Kyrgyzstan', 'Laos',
    'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg',
    'Macao', 'Macedonia, Republic of', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta',
    'Marshall Islands', 'Martinique', 'Mauritania', 'Mauritius', 'Mayotte', 'Mexico',
    'Micronesia, Federated States of', 'Moldova', 'Monaco', 'Mongolia', 'Montenegro', 'Montserrat',
    'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nauru', 'Nepal', 'Netherlands', 'New Caledonia',
    'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'Niue', 'Norfolk Island',
    'Northern Mariana Islands', 'Norway', 'Oman', 'Pakistan', 'Palau', 'Palestine, State of', 'Panama',
    'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Pitcairn', 'Poland', 'Portugal',
    'Puerto Rico', 'Qatar', 'Romania', 'Russian Federation', 'Rwanda', 'R\xe9union',
    'Saint Barth\xe9lemy', 'Saint Helena, Ascension and Tristan da Cunha', 'Saint Kitts and Nevis',
    'Saint Lucia', 'Saint Martin', 'Saint Pierre and Miquelon', 'Saint Vincent and the Grenadines',
    'Samoa', 'San Marino', 'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia', 'Seychelles',
    'Sierra Leone', 'Singapore', 'Sint Maarten (Dutch part)', 'Slovakia', 'Slovenia', 'Solomon Islands',
    'Somalia', 'South Africa', 'South Georgia and South Sandwich Islands', 'South Sudan', 'Spain',
    'Sri Lanka', 'Sudan', 'Suriname', 'Swaziland', 'Sweden', 'Switzerland', 'Syrian Arab Republic',
    'Taiwan', 'Tajikistan', 'Tanzania, United Republic of', 'Thailand', 'Timor-Leste', 'Togo',
    'Tokelau', 'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan',
    'Turks and Caicos Islands', 'Tuvalu', 'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom',
    'United States', 'United States Minor Outlying Islands', 'Uruguay', 'Uzbekistan', 'Vanuatu',
    'Venezuela, Bolivarian Republic of', 'Viet Nam', 'Virgin Islands, British', 'Virgin Islands, U.S.',
    'Wallis and Futuna', 'Western Sahara', 'Yemen', 'Zambia', 'Zimbabwe', '\xc5land Islands'
]

COUNTRY_CODES = {
    'ERITREA': 'ER', 'PORTUGAL': 'PT', 'MONTENEGRO': 'ME', 'NEW CALEDONIA': 'NC',
    'SVALBARD AND JAN MAYEN': 'SJ', 'BAHAMAS': 'BS', 'TOGO': 'TG', 'CROATIA': 'HR',
    'LUXEMBOURG': 'LU', 'GUINEA-BISSAU': 'GW', 'WESTERN SAHARA': 'EH', 'KIRIBATI': 'KI',
    'THAILAND': 'TH', 'BARBADOS': 'BB', 'BENIN': 'BJ', 'PALESTINE, STATE OF': 'PS',
    'YEMEN': 'YE', 'ALGERIA': 'DZ', 'KAZAKHSTAN': 'KZ', 'SAUDI ARABIA': 'SA', 'COSTA RICA': 'CR',
    'ETHIOPIA': 'ET', 'SWEDEN': 'SE', 'HEARD ISLAND AND MCDONALD ISLANDS': 'HM',
    'TIMOR-LESTE': 'TL', 'NIUE': 'NU', 'PERU': 'PE', 'ZAMBIA': 'ZM', 'ANGUILLA': 'AI',
    'NORWAY': 'NO', 'QATAR': 'QA', 'PALAU': 'PW', 'NORFOLK ISLAND': 'NF', 'DENMARK': 'DK',
    'NEPAL': 'NP', 'AZERBAIJAN': 'AZ', 'PAPUA NEW GUINEA': 'PG', 'UNITED STATES': 'US',
    'ZIMBABWE': 'ZW', 'GABON': 'GA', 'GIBRALTAR': 'GI', 'SWAZILAND': 'SZ', 'VANUATU': 'VU',
    'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS': 'GS', 'IRAQ': 'IQ', 'ECUADOR': 'EC',
    'UZBEKISTAN': 'UZ', 'AUSTRALIA': 'AU', 'FRENCH SOUTHERN TERRITORIES': 'TF', 'PITCAIRN': 'PN',
    'GAMBIA': 'GM', 'WALLIS AND FUTUNA': 'WF', 'CENTRAL AFRICAN REPUBLIC': 'CF', 'FRANCE': 'FR',
    'TRINIDAD AND TOBAGO': 'TT', 'ARMENIA': 'AM', 'KUWAIT': 'KW', 'SRI LANKA': 'LK',
    'ARUBA': 'AW', "C\xd4TE D'IVOIRE": 'CI', 'COMOROS': 'KM', 'SAINT PIERRE AND MIQUELON': 'PM',
    'MACEDONIA, REPUBLIC OF': 'MK', 'TONGA': 'TO', 'GEORGIA': 'GE', 'HONDURAS': 'HN',
    'LIBYA': 'LY', 'SOUTH AFRICA': 'ZA', 'MAYOTTE': 'YT', 'INDONESIA': 'ID', 'VIET NAM': 'VN',
    'ANTARCTICA': 'AQ', 'ANTIGUA AND BARBUDA': 'AG', 'SOUTH SUDAN': 'SS', 'COLOMBIA': 'CO',
    'MARTINIQUE': 'MQ', 'SWITZERLAND': 'CH', 'VENEZUELA, BOLIVARIAN REPUBLIC OF': 'VE',
    'MOLDOVA, REPUBLIC OF': 'MD', 'CANADA': 'CA', 'JAMAICA': 'JM', 'EQUATORIAL GUINEA': 'GQ',
    'EGYPT': 'EG', 'LEBANON': 'LB', 'MONGOLIA': 'MN', 'BOTSWANA': 'BW',
    'COCOS (KEELING) ISLANDS': 'CC', 'AUSTRIA': 'AT', 'CONGO': 'CG', 'MALI': 'ML',
    'SLOVAKIA': 'SK', 'MAURITANIA': 'MR', 'COOK ISLANDS': 'CK', 'PAKISTAN': 'PK',
    'SEYCHELLES': 'SC', 'ANGOLA': 'AO', 'BOLIVIA, PLURINATIONAL STATE OF': 'BO',
    'SAINT LUCIA': 'LC', "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF": 'KP',
    'SAINT KITTS AND NEVIS': 'KN', 'UNITED STATES MINOR OUTLYING ISLANDS': 'UM', 'SENEGAL': 'SN',
    'MALAYSIA': 'MY', 'TANZANIA, UNITED REPUBLIC OF': 'TZ', 'SAINT VINCENT AND THE GRENADINES': 'VC',
    'IRELAND': 'IE', 'RUSSIAN FEDERATION': 'RU', 'GRENADA': 'GD', 'NEW ZEALAND': 'NZ',
    'SERBIA': 'RS', 'NIGERIA': 'NG', 'KYRGYZSTAN': 'KG', 'BANGLADESH': 'BD', 'ESTONIA': 'EE',
    'BOUVET ISLAND': 'BV', 'ICELAND': 'IS', 'SLOVENIA': 'SI', 'BRUNEI DARUSSALAM': 'BN',
    'TUNISIA': 'TN', 'LESOTHO': 'LS', 'SYRIAN ARAB REPUBLIC': 'SY',
    'HOLY SEE (VATICAN CITY STATE)': 'VA', 'BOSNIA AND HERZEGOVINA': 'BA',
    'MICRONESIA, FEDERATED STATES OF': 'FM', 'MONACO': 'MC', 'JAPAN': 'JP', 'R\xc9UNION': 'RE',
    'JERSEY': 'JE', 'UKRAINE': 'UA', 'ISRAEL': 'IL', 'CHAD': 'TD', 'MEXICO': 'MX',
    'SUDAN': 'SD', 'TUVALU': 'TV', 'LITHUANIA': 'LT', 'CAPE VERDE': 'CV',
    'SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA': 'SH', 'UNITED KINGDOM': 'GB', 'MOROCCO': 'MA',
    'NETHERLANDS': 'NL', 'UGANDA': 'UG', "LAO PEOPLE'S DEMOCRATIC REPUBLIC": 'LA',
    'BONAIRE, SINT EUSTATIUS AND SABA': 'BQ', '\xc5LAND ISLANDS': 'AX', 'BRAZIL': 'BR',
    'MADAGASCAR': 'MG', 'ALBANIA': 'AL', 'CZECH REPUBLIC': 'CZ',
    'BRITISH INDIAN OCEAN TERRITORY': 'IO', 'VIRGIN ISLANDS, U.S.': 'VI', 'RWANDA': 'RW',
    'GERMANY': 'DE', 'OMAN': 'OM', 'GUERNSEY': 'GG', 'PUERTO RICO': 'PR', 'NIGER': 'NE',
    'HONG KONG': 'HK', 'MALAWI': 'MW', 'TURKS AND CAICOS ISLANDS': 'TC', 'AFGHANISTAN': 'AF',
    'SAINT MARTIN (FRENCH PART)': 'MF', 'ITALY': 'IT', 'SURINAME': 'SR', 'PHILIPPINES': 'PH',
    'MONTSERRAT': 'MS', 'TAIWAN, PROVINCE OF CHINA': 'TW', 'BERMUDA': 'BM', 'FRENCH GUIANA': 'GF',
    'SOMALIA': 'SO', 'ARGENTINA': 'AR', 'CYPRUS': 'CY', 'TURKMENISTAN': 'TM', 'BAHRAIN': 'BH',
    'MALDIVES': 'MV', 'SIERRA LEONE': 'SL', 'MYANMAR': 'MM', 'SAINT BARTH\xc9LEMY': 'BL',
    'NICARAGUA': 'NI', 'CAYMAN ISLANDS': 'KY', 'MARSHALL ISLANDS': 'MH', 'LATVIA': 'LV',
    'CHINA': 'CN', 'GUYANA': 'GY', 'BELGIUM': 'BE', 'CURA\xc7AO': 'CW', 'BURKINA FASO': 'BF',
    'LIBERIA': 'LR', 'SAN MARINO': 'SM', 'GUAM': 'GU', 'AMERICAN SAMOA': 'AS', 'MAURITIUS': 'MU',
    'LIECHTENSTEIN': 'LI', 'NAMIBIA': 'NA', 'TAJIKISTAN': 'TJ', 'GREECE': 'GR', 'NAURU': 'NR',
    'BELIZE': 'BZ', 'FIJI': 'FJ', 'MOZAMBIQUE': 'MZ', 'BELARUS': 'BY', 'TURKEY': 'TR',
    'EL SALVADOR': 'SV', 'POLAND': 'PL', 'KOREA, REPUBLIC OF': 'KR', 'INDIA': 'IN',
    'GUATEMALA': 'GT', 'CAMBODIA': 'KH', 'SOLOMON ISLANDS': 'SB', 'CHRISTMAS ISLAND': 'CX',
    'HUNGARY': 'HU', 'MACAO': 'MO', 'SPAIN': 'ES', 'ISLE OF MAN': 'IM', 'CUBA': 'CU',
    'FAROE ISLANDS': 'FO', 'UNITED ARAB EMIRATES': 'AE', 'FINLAND': 'FI', 'ROMANIA': 'RO',
    'MALTA': 'MT', 'ANDORRA': 'AD', 'DJIBOUTI': 'DJ', 'GREENLAND': 'GL', 'JORDAN': 'JO',
    'SINT MAARTEN (DUTCH PART)': 'SX', 'KENYA': 'KE', 'PARAGUAY': 'PY', 'DOMINICAN REPUBLIC': 'DO',
    'VIRGIN ISLANDS, BRITISH': 'VG', 'DOMINICA': 'DM', 'GHANA': 'GH',
    'SAO TOME AND PRINCIPE': 'ST', 'CONGO, THE DEMOCRATIC REPUBLIC OF THE': 'CD', 'SAMOA': 'WS',
    'NORTHERN MARIANA ISLANDS': 'MP', 'BHUTAN': 'BT', 'URUGUAY': 'UY', 'GUINEA': 'GN',
    'PANAMA': 'PA', 'SINGAPORE': 'SG', 'IRAN, ISLAMIC REPUBLIC OF': 'IR', 'FRENCH POLYNESIA': 'PF',
    'TOKELAU': 'TK', 'FALKLAND ISLANDS (MALVINAS)': 'FK', 'CHILE': 'CL', 'BURUNDI': 'BI',
    'HAITI': 'HT', 'GUADELOUPE': 'GP', 'CAMEROON': 'CM', 'BULGARIA': 'BG'
}

REGIONS = {
    'NEW CALEDONIA': ['Iles Loyaute', 'Nord', 'Sud'],
    'BAHAMAS': [
        'Acklins Island', 'Berry Islands', 'Bimini', 'Black Point', 'Cat Island', 'Central Abaco',
        'Crooked Island and Long Cay', 'East Grand Bahama', 'Exuma', 'Freeport', 'Fresh Creek',
        "Governor's Harbour", 'Green Turtle Cay', 'Harbour Island', 'High Rock', 'Inagua',
        'Kemps Bay', 'Long Island', 'Marsh Harbour', 'Mayaguana', 'Moore\u2019s Island',
        'New Providence', 'Nichollstown and Berry Islands', 'North Abaco', 'North Andros',
        'North Eleuthera', 'Ragged Island', 'Rock Sound', 'San Salvador and Rum Cay',
        'Sandy Point', 'South Abaco', 'South Andros', 'South Eleuthera', 'West Grand Bahama'
    ],
    'TOGO': ['Centre', 'Kara', 'Maritime', 'Plateaux', 'Savannes'],
    'GAMBIA, THE': [
        'Banjul', 'Central River', 'Lower River', 'North Bank', 'Upper River', 'Western'],
    'VENEZUELA, BOLIVARIAN REPUBLIC OF': [
        'Amazonas', 'Anzo\xe1tegui', 'Apure', 'Aragua', 'Barinas',
        'Bol\xedvar', 'Carabobo', 'Cojedes', 'Delta Amacuro',
        'Dependencias Federales', 'Distrito Federal', 'Falc\xf3n',
        'Gu\xe1rico', 'Lara', 'Miranda', 'Monagas', 'M\xe9rida',
        'Nueva Esparta', 'Portuguesa', 'Sucre', 'Trujillo', 'T\xe1chira',
        'Vargas', 'Yaracuy', 'Zulia'
    ],
    'GUINEA-BISSAU': ['Bafat\xe1', 'Biombo', 'Bissau', 'Bolama-Bijagos', 'Cacheu', 'Gab\xfa', 'Oio',
                       'Quinara', 'Tombali'],
    'BARBADOS': ['Christ Church', 'Saint Andrew', 'Saint George', 'Saint James', 'Saint John',
                  'Saint Joseph', 'Saint Lucy', 'Saint Michael', 'Saint Peter', 'Saint Philip',
                  'Saint Thomas'],
    'ALGERIA': [
        'Adrar', 'Algiers', 'Annaba', 'A\xefn Defla', 'A\xefn T\xe9mouchent', 'Batna', 'Biskra',
        'Blida', 'Bordj Bou Arr\xe9ridj', 'Boumerd\xe8s', 'Bou\xefra', 'B\xe9char',
        'B\xe9ja\xefa', 'Chlef', 'Constantine', 'Djelfa', 'El Bayadh', 'El Oued', 'El Tarf',
        'Gharda\xefa', 'Guelma', 'Illizi', 'Jijel', 'Khenchela', 'Laghouat', 'Mascara', 'Mila',
        'Mostaganem', 'Msila', 'M\xe9d\xe9a', 'Na\xe2ma', 'Oran', 'Ouargla', 'Oum el Bouaghi',
        'Relizane', 'Sa\xefda', 'Sidi Bel Abb\xe8s', 'Skikda', 'Souk Ahras', 'S\xe9tif',
        'Tamanghasset', 'Tiaret', 'Tindouf', 'Tipaza', 'Tissemsilt', 'Tizi Ouzou', 'Tlemcen',
        'T\xe9bessa'
    ],
    'OMAN': ['Ad Dakhiliyah', 'Al Buraymi', 'Al Wusta', 'Az Zahirah', 'Janub al Batinah',
              'Janub ash Sharqiyah', 'Masqat', 'Musandam', 'Shamal al Batinah', 'Shamal ash Sharqiyah',
              'Zufar'],
    'AUSTRIA': ['Burgenland', 'K\xe4rnten', 'Nieder\xf6sterreich', 'Ober\xf6sterreich', 'Salzburg',
                 'Steiermark', 'Tirol', 'Vorarlberg', 'Wien'],
    'RWANDA': ['Eastern', 'Kigali', 'Northern', 'Southern', 'Western'], 'NIUE': ['Niue'],
    'PERU': ['Amazonas', 'Ancash', 'Apurimac', 'Arequipa', 'Ayacucho', 'Cajamarca', 'Callao', 'Cusco',
              'Huancavelica', 'Huanuco', 'Ica', 'Junin', 'La Libertad', 'Lambayeque', 'Lima', 'Loreto',
              'Madre de Dios', 'Moquegua', 'Municipalidad Metropolitana de Lima', 'Pasco', 'Piura', 'Puno',
              'San Martin', 'Tacna', 'Tumbes', 'Ucayali'],
    'ANGUILLA': ['Anguilla', 'Anguillita Island', 'Blowing Rock', 'Cove Cay', 'Crocus Cay',
                  "Deadman's Cay", 'Dog Island', 'East Cay', 'Little Island', 'Little Scrub Island',
                  'Mid Cay', 'North Cay', 'Prickly Pear Cays', 'Rabbit Island', 'Sandy Island/Sand Island',
                  'Scilly Cay', 'Scrub Island', 'Seal Island', 'Sombrero/Hat Island', 'South Cay',
                  'South Wager Island', 'West Cay'],
    'BELARUS': ['Brest voblast', 'Gorod Minsk', 'Homiel voblast', 'Hrodna voblast', 'Mahilyow voblast',
                 'Minsk voblast', 'Vitsebsk voblast'],
    'AZERBAIJAN': [
        'Ab\u015feron', 'Astara', 'A\u011fcab\u0259di', 'A\u011fdam', 'A\u011fda\u015f',
        'A\u011fstafa', 'A\u011fsu', 'Bab\u0259k', 'Balak\u0259n', 'Beyl\u0259qan',
        'Bil\u0259suvar', 'B\u0259rd\u0259', 'Culfa', 'C\u0259bray\u0131l', 'C\u0259lilabad',
        'Da\u015fk\u0259s\u0259n', 'F\xfczuli', 'Goranboy', 'G\xf6yg\xf6l', 'G\xf6y\xe7ay',
        'G\u0259d\u0259b\u0259y', 'Hac\u0131qabul', 'K\xfcrd\u0259mir', 'K\u01ddng\u01ddrli',
        'K\u0259lb\u0259c\u0259r', 'La\xe7\u0131n', 'Lerik', 'L\u0259nk\u0259ran',
        'Masall\u0131', 'Neft\xe7ala', 'Ordubad', 'O\u011fuz', 'Qax', 'Qazax', 'Qobustan',
        'Quba', 'Qubadli', 'Qusar', 'Q\u0259b\u0259l\u0259', 'Saatl\u0131', 'Sabirabad',
        'Salyan', 'Samux', 'Siy\u0259z\u0259n', 'S\u0259d\u0259r\u0259k', 'Tovuz',
        'T\u0259rt\u0259r', 'Ucar', 'Xa\xe7maz', 'Xocal\u0131', 'Xocav\u0259nd',
        'X\u0131z\u0131', 'Yard\u0131ml\u0131', 'Yevlax', 'Zaqatala', 'Z\u0259ngilan',
        'Z\u0259rdab', '\u0130mi\u015fli', '\u0130smay\u0131ll\u0131', '\u015eabran',
        '\u015eahbuz', '\u015eamax\u0131', '\u015eu\u015fa', '\u015e\u0259ki',
        '\u015e\u0259mkir', '\u015e\u0259rur'
    ],
    'UNITED STATES': [
        'Alabama', 'Alaska', 'American Samoa', 'Arizona', 'Arkansas',
        'Armed Forces Americas', 'Armed Forces Europe, Canada, Africa and Middle East',
        'Armed Forces Pacific', 'California', 'Colorado', 'Connecticut', 'Delaware',
        'District of Columbia', 'Florida', 'Georgia', 'Guam', 'Hawaii', 'Idaho',
        'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine',
        'Marshall Islands', 'Maryland', 'Massachusetts', 'Michigan', 'Micronesia',
        'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada',
        'New Hampshire', 'New Jersey', 'New Mexico', 'New York', 'North Carolina',
        'North Dakota', 'Northern Mariana Islands', 'Ohio', 'Oklahoma', 'Oregon', 'Palau',
        'Pennsylvania', 'Puerto Rico', 'Rhode Island', 'South Carolina', 'South Dakota',
        'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virgin Islands', 'Virginia',
        'Washington', 'West Virginia', 'Wisconsin', 'Wyoming'
    ], 'GIBRALTAR': ['Gibraltar'],
    'SWAZILAND': ['Hhohho', 'Lubombo', 'Manzini', 'Shiselweni'],
    'VANUATU': ['Malampa', 'P\xe9nama', 'Sanma', 'Sh\xe9fa', 'Taf\xe9a', 'Torba'],
    'IRAQ': [
        'Al Anb\u0101r', 'Al Ba\u015frah', 'Al Muthann\xe1', 'Al Q\u0101dis\u012byah', 'An Najaf',
        'Arb\u012bl', 'As Sulaym\u0101n\u012byah', 'Baghd\u0101d', 'B\u0101bil', 'Dh\u012b Q\u0101r',
        'Diy\u0101l\xe1', 'Dohuk', "Karbal\u0101'", 'Kirkuk', 'Mays\u0101n', 'N\u012bnaw\xe1',
        'W\u0101si\u0163', '\u015eal\u0101\u1e29 ad D\u012bn'
    ],
    'ECUADOR': [
        'Azuay', 'Bol\xedvar', 'Carchi', 'Ca\xf1ar', 'Chimborazo', 'Cotopaxi', 'El Oro',
        'Esmeraldas', 'Gal\xe1pagos', 'Guayas', 'Imbabura', 'Loja', 'Los R\xedos', 'Manab\xed',
        'Morona-Santiago', 'Napo', 'Orellana', 'Pastaza', 'Pichincha', 'Santa Elena',
        'Santo Domingo de los Ts\xe1chilas', 'Sucumb\xedos', 'Tungurahua', 'Zamora-Chinchipe'
    ],
    'UZBEKISTAN': [
        'Andijon', 'Buxoro', 'Farg\u2018ona', 'Jizzax', 'Namangan', 'Navoiy',
        'Qashqadaryo (Qarshi)', 'Qoraqalpog\u2018iston Respublikasi (Nukus)', 'Samarqand',
        'Sirdaryo (Guliston)', 'Surxondaryo (Termiz)', 'Toshkent shahri', 'Toshkent wiloyati',
        'Xorazm (Urganch)'],
    'FRANCE': [
        'Alsace', 'Aquitaine', 'Auvergne', 'Basse-Normandie', 'Bourgogne', 'Bretagne', 'Centre',
        'Champagne-Ardenne', 'Clipperton', 'Corse', 'Franche-Comt\xe9', 'Guadeloupe', 'Guyane',
        'Haute-Normandie', 'Languedoc-Roussillon', 'Limousin', 'Lorraine', 'Martinique', 'Mayotte',
        'Midi-Pyr\xe9n\xe9es', 'Nord-Pas-de-Calais', 'Novelle-Cal\xe9donie', 'Pays de la Loire',
        'Picardie', 'Poitou-Charentes', 'Polyn\xe9sie', "Provence-Alpes-Cote d'Azur", 'Rhone-Alpes',
        'R\xe9union', 'Saint Barth\xe9lemy', 'Saint Martin', 'Saint-Pierre-et-Miquelon',
        'Terres Australes Fran\xe7aises', 'Wallis-et-Futuna', '\xcele-de-France'
    ],
    'TRINIDAD AND TOBAGO': [
        'Arima', 'Chaguanas', 'Couva-Tabaquite-Talparo', 'Diefo Martin',
        'Mayaro-Rio Claro', 'Penal-Debe', 'Point Fortin', 'Port-of-Spain',
        'Princes Town', 'San Fernando', 'San Juan-Laventille', 'Sangre Grande',
        'Siparia', 'Tobago', 'Tunapuna-Piarco'
    ],
    'SRI LANKA': [
        'Basnahira', 'Dakunu', 'Madhyama', 'Naegenahira', 'Sabaragamuwa', 'Uturu',
        'Uturumaeda', 'Uva', 'Vayamba'
    ],
    'ARUBA': ['Aruba'],
    'TURKS AND CAICOS ISLANDS': ['Turks and Caicos Islands'],
    'NETHERLANDS': [
        'Drenthe', 'Flevoland', 'Friesland', 'Gelderland', 'Groningen', 'Limburg',
        'Noord-Brabant', 'Noord-Holland', 'Overijssel', 'Utrecht', 'Zeeland', 'Zuid-Holland'
    ],
    'LIBYA': [
        '  Mi\u015fr\u0101tah', 'Al Bu\u0163n\u0101n', 'Al Jabal al Akh\u1e11ar',
        'Al Jabal al Gharb\u012b', 'Al Jaf\u0101rah', 'Al Jufrah', 'Al Kufrah', 'Al Marj',
        'Al Marquab', 'Al W\u0101\u1e29\u0101t', 'An Nuqa\u0163 al Khams', 'Az Z\u0101wiyah',
        'Bangh\u0101z\u012b', 'Darnah', 'Gh\u0101t', 'Murzuq', 'N\u0101l\u016bt', 'Sabh\u0101',
        'Surt', 'W\u0101d\u012b ash Sh\u0101\u0163i\u02be', 'Yafran', '\u0162ar\u0101bulus'
    ],
    'SOUTH AFRICA': ['Eastern Cape', 'Free State', 'Gauteng', 'KwaZulu-Natal', 'Limpopo', 'Mpumalanga',
                      'North West', 'Northern Cape', 'Western Cape'],
    'FRENCH SOUTHERN AND ANTARCTIC LANDS': ['Adelie Land', 'Ile Crozet', 'Iles Kerguelen',
                                             'Iles Saint-Paul et Amsterdam'],
    'INDONESIA': [
        'Aceh', 'Bali', 'Bangka Belitung', 'Banten', 'Bengkulu', 'Gorontalo', 'Jakarta Raya',
        'Jambi', 'Jawa Barat', 'Jawa Tengah', 'Jawa Timur', 'Kalimantan Barat',
        'Kalimantan Selatan', 'Kalimantan Tengah', 'Kalimantan Timur', 'Kalimantan Utara',
        'Kepulauan Riau', 'Lampung', 'Maluku', 'Maluku Utara', 'Nusa Tenggara Barat',
        'Nusa Tenggara Timur', 'Papua', 'Papua Barat', 'Riau', 'Sulawesi Selatan',
        'Sulawesi Tengah', 'Sulawesi Tenggara', 'Sulawesi Utara', 'Sumatera Barat',
        'Sumatera Selatan', 'Sumatera Utara', 'Yogyakarta'
    ],
    'ANTARCTICA': ['Antarctica'],
    'MOZAMBIQUE': [
        'Cabo Delgado', 'Gaza', 'Inhambane', 'Manica', 'Maputo', 'Maputo (City)', 'Nampula',
        'Niassa', 'Sofala', 'Tete', 'Zambezia'
    ],
    'SOUTH SUDAN': [
        'Central Equatoria', 'Eastern Equatoria', 'Jonglei', 'Lakes',
        'Northern Bahr el Ghazal', 'Unity', 'Upper Nile', 'Warrap', 'Western Bahr el Ghazal',
        'Western Equatoria'
    ],
    'COLOMBIA': [
        'Amazonas', 'Antioquia', 'Arauca', 'Archipi\xe9lago de San Andr\xe9s', 'Atl\xe1ntico',
        'Bogot\xe1 D.C.', 'Bol\xedvar', 'Boyac\xe1', 'Caldas', 'Caquet\xe1', 'Casanare',
        'Cauca', 'Cesar', 'Choc\xf3', 'Cundinamarca', 'C\xf3rdoba', 'Guain\xeda', 'Guaviare',
        'Huila', 'La Guajira', 'Magdalena', 'Meta', 'Nari\xf1o', 'Norte de Santander',
        'Putumayo', 'Quind\xedo', 'Risaralda', 'Santander', 'Sucre', 'Tolima',
        'Valle del Cauca', 'Vaup\xe9s', 'Vichada'
    ],
    'MARTINIQUE': ['Martinique'],
    'EQUATORIAL GUINEA': [
        'Annob\xf3n', 'Bioko Norte', 'Bioko Sur', 'Centro Sur', 'Ki\xe9-Ntem', 'Litoral', 'Wele-Nzas'
    ],
    'MONGOLIA': [
        'Arhangay', 'Bayan-Olgiy', 'Bayanhongor', 'Bulgan', 'Darhan', 'Dornod', 'Dornogovi',
        'Dundgovi', 'Dzavhan', 'Govi-Altay', 'Govi-Sumber', 'Hovd', 'Hovsgol', 'Omnogovi',
        'Ovorhangay', 'Selenge', 'Suhbaatar', 'Tov', 'Ulaanbaatar', 'Uvs'],
    'MALI': ['Bamako', 'Gao', 'Kayes', 'Kidal', 'Koulikoro', 'Mopti', 'Segou', 'Sikasso',
              'Tombouctou'],
    'CHINA': [
        'Anhui', 'Beijing', 'Chongqing', 'Fujian', 'Gansu', 'Guangdong', 'Guangxi', 'Guizhou',
        'Hainan', 'Hebei', 'Heilongjiang', 'Henan', 'Hong Kong', 'Hubei', 'Hunan',
        'Inner Mongolia', 'Jiangsu', 'Jiangxi', 'Jilin', 'Liaoning', 'Macau', 'Ningxia',
        'Qinghai', 'Shaanxi', 'Shandong', 'Shanghai', 'Shanxi', 'Sichuan', 'Tianjin', 'Tibet',
        'Xinjiang', 'Yunnan', 'Zhejiang'],
    'ZAMBIA': ['Central', 'Copperbelt', 'Eastern', 'Luapula', 'Lusaka', 'North-Western', 'Northern',
                'Southern', 'Western'],
    'FALKLAND ISLANDS (ISLAS MALVINAS)': ['Falkland Islands (Islas Malvinas)'],
    'PAKISTAN': [
        'Bal\u014dchist\u0101n', 'Federally Administered Tribal Areas', 'Gilgit-Baltist\u0101n',
        'Isl\u0101m\u0101b\u0101d', 'Kha\u012bbar Pakht\u016bnkhw\u0101s', 'Punj\u0101b', 'Sindh',
        '\u0100z\u0101d Kashm\u012br'],
    'SAINT LUCIA': [
        'Anse-la-Raye', 'Canaries', 'Castries', 'Choiseul', 'Dennery', 'Gros Islet',
        'Laborie', 'Micoud', 'Soufriere', 'Vieux Fort'
    ],
    "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF": [
        'Chagang-do (Chagang Province)',
        'Hamgyong-bukto (North Hamgyong Province)',
        'Hamgyong-namdo (South Hamgyong Province)',
        'Hwanghae-bukto (North Hwanghae Province)',
        'Hwanghae-namdo (South Hwanghae Province)',
        'Kangwon-do (Kangwon Province)',
        'Nas\u014fn (Najin-S\u014fnbong)',
        "P'yongan-bukto (North P'yongan Province)",
        "P'yongan-namdo (South P'yongan Province)",
        "P'yongyang-si (P'yongyang City)",
        'Yanggang-do (Yanggang Province)'
    ],
    'SAINT KITTS AND NEVIS': ['Nevis', 'Saint Kitts'],
    'UNITED STATES MINOR OUTLYING ISLANDS': [
        'Bajo Nuevo Bank', 'Baker Island', 'Howland Island',
        'Jarvis Island', 'Johnston Atoll', 'Kingman Reef',
        'Midway Islands', 'Navassa Island', 'Palmyra Atoll',
        'Serranilla Bank', 'Wake Island'
    ],
    'SLOVENIA': [
        'Ajdovscina', 'Apace', 'Beltinci', 'Benedikt', 'Bistrica ob Sotli', 'Bled', 'Bloke',
        'Bohinj', 'Borovnica', 'Bovec', 'Braslovce', 'Brda', 'Brezice', 'Brezovica', 'Cankova',
        'Celje', 'Cerklje na Gorenjskem', 'Cerknica', 'Cerkno', 'Cerkvenjak', 'Cirkulane',
        'Crensovci', 'Crna na Koroskem', 'Crnomelj', 'Destrnik', 'Divaca', 'Dobje',
        'Dobrepolje', 'Dobrna', 'Dobrova-Polhov Gradec', 'Dobrovnik', 'Dol pri Ljubljani',
        'Dolenjske Toplice', 'Domzale', 'Dornava', 'Dravograd', 'Duplek', 'Gorenja Vas-Poljane',
        'Gorisnica', 'Gorje', 'Gornja Radgona', 'Gornji Grad', 'Gornji Petrovci', 'Grad',
        'Grosuplje', 'Hajdina', 'Hoce-Slivnica', 'Hodos', 'Horjul', 'Hrastnik',
        'Hrpelje-Kozina', 'Idrija', 'Ig', 'Ilirska Bistrica', 'Ivancna Gorica', 'Izola',
        'Jesenice', 'Jursinci', 'Kamnik', 'Kanal', 'Kidricevo', 'Kobarid', 'Kobilje',
        'Kocevje', 'Kodanjevica na Krki', 'Komen', 'Komenda', 'Koper', 'Kostel', 'Kozje',
        'Kranj', 'Kranjska Gora', 'Krizevci', 'Krsko', 'Kungota', 'Kuzma', 'Lasko', 'Lenart',
        'Lendava', 'Litija', 'Ljubljana', 'Ljubno', 'Ljutomer', 'Log-Dragomer', 'Logatec',
        'Loska Dolina', 'Loski Potok', 'Lovrenc na Pohorju', 'Luce', 'Lukovica', 'Majsperk',
        'Makole', 'Maribor', 'Markovci', 'Medvode', 'Menges', 'Metlika', 'Mezica',
        'Miklavz na Dravskem Polju', 'Miren-Kostanjevica', 'Mirna', 'Mirna Pec', 'Mislinja',
        'Mokronog-Trebelno', 'Moravce', 'Moravske Toplice', 'Mozirje', 'Murska Sobota', 'Naklo',
        'Nazarje', 'Nova Gorica', 'Novo Mesto', 'Odranci', 'Ormoz', 'Osilnica', 'Pesnica',
        'Piran', 'Pivka', 'Podcetrtek', 'Podlehnik', 'Podvelka', 'Poljcane', 'Postojna',
        'Prebold', 'Preddvor', 'Prevalje', 'Ptuj', 'Race-Fram', 'Radece', 'Radenci',
        'Radlje ob Dravi', 'Radovljica', 'Ravne na Koroskem', 'Razkrizje', 'Recica ob Savinji',
        'Rence-Vogrsko', 'Ribnica', 'Ribnica na Poboriu', 'Rogaska Slatina', 'Rogasovci',
        'Rogatec', 'Ruse', 'Salovci', 'Selnica ob Dravi', 'Semic', 'Sempeter-Vrtojba', 'Sencur',
        'Sentilj', 'Sentjernej', 'Sentjur', 'Sentrupert', 'Sevnica', 'Sezana', 'Skocjan',
        'Skofja Loka', 'Skofljica', 'Slovenj Gradec', 'Slovenska Bistrica', 'Slovenske Konjice',
        'Smarje pri elsah', 'Smarjeske Toplice', 'Smartno ob Paki', 'Smartno pri Litiji',
        'Sodrazica', 'Solcava', 'Sostanj', 'Sredisce ob Dravi', 'Starse', 'Store', 'Straza',
        'Sveta Ana', 'Sveta Andraz v Slovenskih Goricah', 'Sveta Trojica v Slovenskih Goricah',
        'Sveti Jurij', 'Sveti Jurij v Slovenskih Goricah', 'Sveti Tomaz', 'Tabor', 'Tisina',
        'Tolmin', 'Trbovlje', 'Trebnje', 'Trnovska Vas', 'Trzic', 'Trzin', 'Turnisce',
        'Velenje', 'Velika Polana', 'Velike Lasce', 'Verzej', 'Videm', 'Vipava', 'Vitanje',
        'Vodice', 'Vojnik', 'Vransko', 'Vrhnika', 'Vuzenica', 'Zagorje ob Savi', 'Zalec',
        'Zavrc', 'Zelezniki', 'Zetale', 'Ziri', 'Zirovnica', 'Zrece', 'Zuzemberk'
    ],
    'IRELAND': [
        'Carlow', 'Cavan', 'Clare', 'Cork', 'Donegal', 'Dublin', 'Galway', 'Kerry', 'Kildare',
        'Kilkenny', 'Laois', 'Leitrim', 'Limerick', 'Longford', 'Louth', 'Mayo', 'Meath',
        'Monaghan', 'Offaly', 'Roscommon', 'Sligo', 'Tipperary', 'Waterford', 'Westmeath',
        'Wexford', 'Wicklow'
    ],
    'GRENADA': ['Saint Andrew', 'Saint David', 'Saint George', 'Saint John', 'Saint Mark',
                 'Saint Patrick', 'Southern Grenadine Islands'],
    'BANGLADESH': ['Barisal', 'Chittagong', 'Dhaka', 'Khulna', 'Rajshahi', 'Rangpur', 'Sylhet'],
    'ESTONIA': [
        'Harjumaa (Tallinn)', 'Hiiumaa (Kardla)', 'Ida-Virumaa (Johvi)', 'J\xe4rvamaa (Paide)',
        'J\xf5gevamaa (Jogeva)', 'L\xe4\xe4ne-Virumaa (Rakvere)', 'L\xe4\xe4nemaa',
        'P\xe4rnumaa (Parnu)', 'P\xf5lvamaa (Polva)', 'Raplamaa (Rapla)', 'Saaremaa (Kuessaare)',
        'Tartumaa (Tartu)', 'Valgamaa (Valga)', 'Viljandimaa (Viljandi)', 'V\xf5rumaa (Voru)'],
    'ICELAND': ['Austurland', 'H\xf6fu\xf0borgarsv\xe6\xf0i utan Reykjav\xedkur', 'Nor\xf0urland eystra',
                 'Nor\xf0urland vestra', 'Su\xf0urland', 'Su\xf0urnes', 'Vestfir\xf0ir', 'Vesturland'],
    'BOSNIA AND HERZEGOVINA': ['Br\u010dko Distrikt', 'Federacija Bosne i Hercegovine', 'Republika Srpska'],
    'MICRONESIA, FEDERATED STATES OF': ['Chuuk (Truk)', 'Kosrae', 'Pohnpei', 'Yap'],
    'MONACO': [
        'Colle', 'Condamine', 'Fontvieille', 'Gare', 'Jardin Exotique', 'Larvotto', 'Malbousquet',
        'Monaco-Ville', 'Moneghetti', 'Monte-Carlo', 'Moulins', 'Port-Hercule', 'Saint-Roman',
        'Sainte-D\xe9vote', 'Source', 'Sp\xe9lugues', 'Vallon de la Rousse'],
    'CONGO, REPUBLIC OF THE (BRAZZAVILLE)': [
        'Bouenza', 'Brazzaville', 'Cuvette', 'Cuvette-Ouest',
        'Kouilou', 'Likouala', 'L\xe9koumou', 'Niari', 'Plateaux',
        'Pointe-Noire', 'Pool', 'Sangha'],
    'ISRAEL': ['HaDarom', 'HaMerkaz', 'HaTsafon', 'H\u0331efa', 'Tel-Aviv', 'Yerushalayim'],
    'MEXICO': [
        'Aguascalientes', 'Baja California', 'Baja California Sur', 'Campeche', 'Chiapas',
        'Chihuahua', 'Coahuila de Zaragoza', 'Colima', 'Distrito Federal', 'Durango', 'Guanajuato',
        'Guerrero', 'Hidalgo', 'Jalisco', 'Mexico', 'Michoacan de Ocampo', 'Morelos', 'Nayarit',
        'Nuevo Leon', 'Oaxaca', 'Puebla', 'Queretaro de Arteaga', 'Quintana Roo',
        'San Luis Potosi', 'Sinaloa', 'Sonora', 'Tabasco', 'Tamaulipas', 'Tlaxcala',
        'Veracruz-Llave', 'Yucatan', 'Zacatecas'],
    'TUVALU': ['Funafuti', 'Nanumanga', 'Nanumea', 'Niutao', 'Nui', 'Nukufetau', 'Nukulaelae', 'Vaitupu'],
    'SERBIA': [
        'Beograd (Belgrade)', 'Borski', 'Brani\u010devski', 'Jablani\u010dki', 'Ju\u017enobanatski',
        'Ju\u017enoba\u010dki', 'Kolubarski', 'Kosovski', 'Kosovsko-Mitrova\u010dki',
        'Kosovsko-Pomoravski', 'Ma\u010dvanski', 'Moravi\u010dki', 'Ni\u0161avski', 'Pe\u0107ki',
        'Pirotski', 'Podunavski', 'Pomoravski', 'Prizrenski', 'P\u010dinjski', 'Rasinski',
        'Ra\u0161ki', 'Severnobanatski', 'Severnoba\u010dki', 'Srednjebanatski', 'Sremski',
        'Topli\u010dki', 'Zaje\u010darski', 'Zapadnoba\u010dki', 'Zlatiborski', '\u0160umadijski'],
    'CAPE VERDE': [
        'Boa Vista', 'Brava', 'Calheta de S\xe3o Miguel', 'Maio', 'Mosteiros', 'Pa\xfal',
        'Porto Novo', 'Praia', 'Ribeira Brava', 'Ribeira Grande', 'Sal', 'Santa Catarina',
        'Santa Cruz', 'S\xe3o Domingos', 'S\xe3o Filipe', 'S\xe3o Nicolau', 'S\xe3o Vicente',
        'Tarrafal', 'Tarrafal de S\xe3o Nicolau'],
    'SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA': ['Ascension', 'Saint Helena', 'Tristan da Cunha'],
    'THAILAND': [
        'Amnat Charoen', 'Ang Thong', 'Bueng Kan', 'Buri Ram', 'Chachoengsao', 'Chai Nat',
        'Chaiyaphum', 'Chanthaburi', 'Chiang Mai', 'Chiang Rai', 'Chon Buri', 'Chumphon',
        'Kalasin', 'Kamphaeng Phet', 'Kanchanaburi', 'Khon Kaen', 'Krabi',
        'Krung Thep Mahanakhon (Bangkok)', 'Lampang', 'Lamphun', 'Loei', 'Lop Buri',
        'Mae Hong Son', 'Maha Sarakham', 'Mukdahan', 'Nakhon Nayok', 'Nakhon Phanom',
        'Nakhon Phathom', 'Nakhon Ratchasima', 'Nakhon Sawan', 'Nakhon Si Thammarat', 'Nan',
        'Narathiwat', 'Nong Bua Lam Phu', 'Nong Khai', 'Nonthaburi', 'Pathum Thani', 'Pattani',
        'Phangnga', 'Phatthalung', 'Phayao', 'Phetchabun', 'Phetchaburi', 'Phichit',
        'Phitsanulok', 'Phra Nakhon Si Ayutthaya', 'Phrae', 'Phuket', 'Prachin Buri',
        'Prachuap Khiri Khan', 'Ranong', 'Ratchaburi', 'Rayong', 'Roi Et', 'Sa Kaeo',
        'Sakon Nakhon', 'Samut Prakan', 'Samut Sakhon', 'Samut Songkhram', 'Saraburi', 'Satun',
        'Si Sa ket', 'Sing Buri', 'Songkhla', 'Sukhothai', 'Suphan Buri', 'Surat Thani',
        'Surin', 'Tak', 'Trang', 'Trat', 'Ubon Ratchathani', 'Udon Thani', 'Uthai Thani',
        'Uttaradit', 'Yala', 'Yasothon'],
    'BONAIRE, SINT EUSTATIUS AND SABA': ['Bonaire', 'Saba Isand', 'Sint Eustatius'],
    'NIGERIA': [
        'Abia', 'Abuja Federal Capital Territory', 'Adamawa', 'Akwa Ibom', 'Anambra', 'Bauchi',
        'Bayelsa', 'Benue', 'Borno', 'Cross River', 'Delta', 'Ebonyi', 'Edo', 'Ekiti', 'Enugu',
        'Gombe', 'Imo', 'Jigawa', 'Kaduna', 'Kano', 'Katsina', 'Kebbi', 'Kogi', 'Kwara',
        'Lagos', 'Nassarawa', 'Niger', 'Ogun', 'Ondo', 'Osun', 'Oyo', 'Plateau', 'Rivers',
        'Sokoto', 'Taraba', 'Yobe', 'Zamfara'],
    'ALBANIA': [
        'Berat', 'Dib\xebr', 'Durr\xebs', 'Elbasan', 'Fier', 'Gjirokast\xebr', 'Kor\xe7\xeb',
        'Kuk\xebs', 'Lezh\xeb', 'Shkod\xebr', 'Tirana', 'Vlor\xeb'],
    'CZECH REPUBLIC': [
        'Hlavn\xed m\u011bsto Praha', 'Jihomoravsk\xfd kraj', 'Jiho\u010desk\xfd kraj',
        'Karlovarsk\xfd kraj', 'Kr\xe1lov\xe9hradeck\xfd kraj', 'Libereck\xfd kraj',
        'Moravskoslezsk\xfd kraj', 'Olomouck\xfd kraj', 'Pardubick\xfd kraj',
        'Plze\u0148sk\xfd kraj', 'St\u0159edo\u010desk\xfd kraj', 'Vyso\u010dina',
        'Zl\xednsk\xfd kraj', '\xdasteck\xfd kraj'],
    'BRITISH INDIAN OCEAN TERRITORY': ['British Indian Ocean Territory'],
    'GUERNSEY': ['Castel', 'Forest', 'St. Andrew', 'St. Martin', 'St. Peter Port', 'St. Pierre du Bois',
                  'St. Sampson', 'St. Saviour', 'Torteval', 'Vale'], 'HONG KONG': ['Hong Kong'],
    'MALAWI': ['Balaka', 'Blantyre', 'Chikwawa', 'Chiradzulu', 'Chitipa', 'Dedza', 'Dowa', 'Karonga',
                'Kasungu', 'Likoma', 'Lilongwe', 'Machinga', 'Mangochi', 'Mchinji', 'Mulanje', 'Mwanza',
                'Mzimba', 'Nkhata Bay', 'Nkhotakota', 'Nsanje', 'Ntcheu', 'Ntchisi', 'Phalombe',
                'Rumphi', 'Salima', 'Thyolo', 'Zomba'],
    'AFGHANISTAN': [
        'Badakhshan', 'Badghis', 'Baghlan', 'Balkh', 'Bamyan', 'Daykundi', 'Farah',
        'Faryab', 'Ghazni', 'Ghor', 'Helmand', 'Herat', 'Jowzjan', 'Kabul', 'Kandahar',
        'Kapisa', 'Khost', 'Kunar', 'Kunduz', 'Laghman', 'Logar', 'Maidan Wardak',
        'Nangarhar', 'Nimruz', 'Nuristan', 'Paktia', 'Paktika', 'Panjshir', 'Parwan',
        'Samangan', 'Sar-e Pol', 'Takhar', 'Urozgan', 'Zabul'],
    'SAUDI ARABIA': [
        "'Asir", 'Al Bahah', 'Al Hudud ash Shamaliyah', 'Al Jawf', 'Al Madinah al Munawwarah',
        'Al Qasim', 'Ar Riyad', 'Ash Sharqiyah', "Ha'il", 'Jazan', 'Makkah al Mukarramah',
        'Najran', 'Tabuk'],
    'ITALY': [
        'Abruzzo', 'Basilicata', 'Calabria', 'Campania', 'Emilia-Romagna', 'Friuli-Venezia Giulia',
        'Lazio', 'Liguria', 'Lombardia', 'Marche', 'Molise', 'Piemonte', 'Puglia', 'Sardegna',
        'Sicilia', 'Toscana', 'Trentino-Alto Adige', 'Umbria', "Valle d'Aosta", 'Veneto'],
    'SURINAME': ['Brokopondo', 'Commewijne', 'Coronie', 'Marowijne', 'Nickerie', 'Para', 'Paramaribo',
                  'Saramacca', 'Sipaliwini', 'Wanica'],
    'PHILIPPINES': [
        'Abra', 'Agusan del Norte', 'Agusan del Sur', 'Aklan', 'Albay', 'Antique', 'Apayao',
        'Aurora', 'Basilan', 'Bataan', 'Batanes', 'Batangas', 'Benguet', 'Biliran', 'Bohol',
        'Bukidnon', 'Bulacan', 'Cagayan', 'Camarines Norte', 'Camarines Sur', 'Camiguin',
        'Capiz', 'Catanduanes', 'Cavite', 'Cebu', 'Compostela', 'Cotabato',
        'Davao Occidental', 'Davao Oriental', 'Davao del Norte', 'Davao del Sur',
        'Dinagat Islands', 'Eastern Samar', 'Guimaras', 'Ifugao', 'Ilocos Norte',
        'Ilocos Sur', 'Iloilo', 'Isabela', 'Kalinga', 'La Union', 'Laguna',
        'Lanao del Norte', 'Lanao del Sur', 'Leyte', 'Maguindanao', 'Masbate',
        'Mindoro Occidental', 'Mindoro Oriental', 'Misamis Occidental', 'Misamis Oriental',
        'Mountain Province', 'Negros Occidental', 'Negros Oriental', 'Northern Samar',
        'Nueva Ecija', 'Nueva Vizcaya', 'Palawan', 'Pampanga', 'Pangasinan', 'Quezon',
        'Quirino', 'Rizal', 'Romblon', 'Samar', 'Sarangani', 'Siquijor', 'Sorsogon',
        'Southern Leyte', 'Sultan Kudarat', 'Sulu', 'Surigao del Norte', 'Surigao del Sur',
        'Tarlac', 'Tawi-Tawi', 'Zambales', 'Zamboanga Sibugay', 'Zamboanga del Norte',
        'Zamboanga del Sur'],
    'KENYA': [
        'Baringo', 'Bomet', 'Bungoma', 'Busia', 'Eleyo/Marakwet', 'Embu', 'Garissa', 'Homa Bay',
        'Isiolo', 'Kajiado', 'Kakamega', 'Kericho', 'Kiambu', 'Kilifi', 'Kirinyaga', 'Kisii',
        'Kisumu', 'Kitui', 'Kwale', 'Laikipia', 'Lamu', 'Machakos', 'Makueni', 'Mandera',
        'Marsabit', 'Meru', 'Migori', 'Mombasa', "Murang'a", 'Nairobi City', 'Nakuru', 'Nandi',
        'Narok', 'Nyamira', 'Nyandarua', 'Nyeri', 'Samburu', 'Siaya', 'Taita/Taveta',
        'Tana River', 'Tharaka-Nithi', 'Trans Nzoia', 'Turkana', 'Uasin Gishu', 'Vihiga', 'Wajir',
        'West Pokot'],
    "C\xd4TE D'IVOIRE, REPUBLIC OF": [
        'Agn\xe9by', 'Bafing', 'Bas-Sassandra', 'Dengu\xe9l\xe9',
        'Dix-Huit Montagnes', 'Fromager', 'Haut-Sassandra', 'Lacs',
        'Lagunes', 'Marahou\xe9', 'Moyen-Cavally', 'Moyen-Como\xe9',
        "N'zi-Como\xe9", 'Savanes', 'Sud-Bandama', 'Sud-Como\xe9',
        'Vall\xe9e du Bandama', 'Worodougou', 'Zanzan'],
    'BERMUDA': ['City of Hamilton', 'Devonshire Parish', 'Hamilton Parish', 'Paget Parish',
                 'Pembroke Parish', 'Sandys Parish', "Smith's Parish", 'Southampton Parish',
                 "St. George's Parish", 'Town of St. George', 'Warwick Parish'],
    'FRENCH GUIANA': ['French Guiana'],
    'ARGENTINA': ['Buenos Aires', 'Capital Federal', 'Catamarca', 'Chaco', 'Chubut', 'Corrientes',
                   'C\xf3rdoba', 'Entre R\xedos', 'Formosa', 'Jujuy', 'La Pampa', 'La Rioja', 'Mendoza',
                   'Misiones', 'Neuqu\xe9n', 'R\xedo Negro', 'Salta', 'San Juan', 'San Luis',
                   'Santa Cruz', 'Santa Fe', 'Santiago del Estero', 'Tierra del Fuego', 'Tucum\xe1n'],
    'CYPRUS': ['Ammochostos', 'Keryneia', 'Larnaka', 'Lefkosia', 'Lemesos', 'Pafos'],
    'BAHRAIN': ['Al Jan\u016bb\u012byah', 'Al Man\u0101mah', 'Al Mu\u1e29arraq', 'Al Wus\u0163\xe1',
                 'Ash Sham\u0101l\u012byah'],
    'SIERRA LEONE': ['Eastern', 'Northern', 'Southern', 'Western'],
    'SAINT BARTH\xc9LEMY': ['Au Vent', 'Sous le Vent'],
    'CAYMAN ISLANDS': ['Creek', 'Eastern', 'Midland', 'South Town', 'Spot Bay', 'Stake Bay', 'West End',
                        'Western'],
    'LAOS': ['Attapu', 'Bok\xe8o', 'Bolikhamxai', 'Champasak', 'Houaphan', 'Khammouan', 'Louang Namtha',
              'Louangphabang', 'Oud\xf4mxai', 'Ph\xf4ngsali', 'Salavan', 'Savannakh\xe9t', 'Vientiane',
              'Xaignabouli', 'Xaisomboun', 'Xiangkhouang', 'X\xe9kong'], 'CURA\xc7AO': ['Cura\xe7ao'],
    'BURKINA FASO': [
        'Bal\xe9', 'Bam/Lake Bam', 'Banwa Province', 'Baz\xe8ga', 'Bougouriba',
        'Boulgou Province', 'Boulkiemd\xe9', 'Como\xe9/Komoe', 'Ganzourgou Province',
        'Gnagna', 'Gourma Province', 'Houet', 'Ioba', 'Kadiogo', 'Komondjari', 'Kompienga',
        'Kossi Province', 'Koulp\xe9logo', 'Kouritenga', 'Kourw\xe9ogo', 'K\xe9n\xe9dougou',
        'Loroum', 'L\xe9raba', 'Mouhoun', 'Namentenga', 'Naouri/Nahouri', 'Nayala',
        'Noumbiel', 'Oubritenga', 'Oudalan', 'Passor\xe9', 'Poni', 'Sangui\xe9',
        'Sanmatenga', 'Sissili', 'Soum', 'Sourou', 'S\xe9no', 'Tapoa', 'Tui/Tuy', 'Yagha',
        'Yatenga', 'Ziro', 'Zondoma', 'Zoundw\xe9ogo'],
    'LIBERIA': ['Bomi', 'Bong', 'Gbarpolu', 'Grand Bassa', 'Grand Cape Mount', 'Grand Gedeh',
                 'Grand Kru', 'Lofa', 'Margibi', 'Maryland', 'Montserrado', 'Nimba', 'River Cess',
                 'River Geee', 'Sinoe'],
    'MOLDOVA': ['  Edine\u021b', 'Aenii Noi', 'Basarabeasca', 'Bender', 'Briceni', 'B\u0103l\u021bi',
                 'Cahul', 'Cantemir', 'Chi\u0219in\u0103u', 'Cimi\u0219lia', 'Criuleni',
                 'C\u0103l\u0103ra\u0219i', 'C\u0103u\u0219eni', 'Dondu\u0219eni', 'Drochia',
                 'Dub\u0103sari', 'Flore\u0219ti', 'F\u0103le\u0219ti', 'Glodeni', 'G\u0103g\u0103uzia',
                 'H\xeence\u0219ti', 'Ialoveni', 'Leova', 'Nisporeni', 'Ocni\u021ba', 'Orhei', 'Rezina',
                 'R\xee\u0219cani', 'Soroca', 'Str\u0103\u0219eni', 'St\xeenga Nistrului', 'S\xeengerei',
                 'Taraclia', 'Telene\u0219ti', 'Ungheni', '\u0218old\u0103ne\u0219ti',
                 '\u0218tefan Vod\u0103'],
    'NAURU': ['Aiwo', 'Anabar', 'Anetan', 'Anibare', 'Baiti', 'Boe', 'Buada', 'Denigomodu', 'Ewa',
               'Ijuw', 'Meneng', 'Nibok', 'Uaboe', 'Yaren'],
    'FIJI': ['Ba', 'Bua', 'Cakaudrove', 'Kadavu', 'Lau', 'Lomaiviti', 'Macuata', 'Nadroga and Navosa',
              'Naitasiri', 'Namosi', 'Ra', 'Rewa', 'Rotuma', 'Serua', 'Tailevu'],
    'TAIWAN': ['Chang-hua', 'Chia-i', 'Hsin-chu', 'Hua-lien', 'Kao-hsiung', 'Keelung', 'Kinmen',
                'Lienchiang', 'Miao-li', "Nan-t'ou", 'New Taipei', "P'eng-hu", "P'ing-chung",
                "T'ai-chung", "T'ai-nan", "T'ai-pei", "T'ai-tung", "T'ao-yuan", 'Yi-lan', 'Yun-lin'],
    'ROMANIA': ['Alba', 'Arad', 'Arges', 'Bacau', 'Bihor', 'Bistrita-Nasaud', 'Botosani', 'Braila',
                 'Brasov', 'Bucuresti', 'Buzau', 'Calarasi', 'Caras-Severin', 'Cluj', 'Constanta',
                 'Covasna', 'Dambovita', 'Dolj', 'Galati', 'Giurgiu', 'Gorj', 'Harghita', 'Hunedoara',
                 'Ialomita', 'Iasi', 'Maramures', 'Mehedinti', 'Mures', 'Neamt', 'Olt', 'Prahova',
                 'Salaj', 'Satu Mare', 'Sibiu', 'Suceava', 'Teleorman', 'Timis', 'Tulcea', 'Valcea',
                 'Vaslui', 'Vrancea'],
    'EL SALVADOR': ['Ahuachap\xe1n', 'Caba\xf1as', 'Chalatenango', 'Cuscatl\xe1n', 'La Libertad',
                     'La Paz', 'La Uni\xf3n', 'Moraz\xe1n', 'San Miguel', 'San Salvador', 'San Vicente',
                     'Santa Ana', 'Sonsonate', 'Usulut\xe1n'],
    'POLAND': ['\u015awi\u0119tokrzyskie', 'Dolno\u015bl\u0105skie', 'Kujawsko-pomorskie', 'Lubelskie',
                'Lubuskie', 'Malopolskie', 'Mazowieckie', 'Opolskie', 'Podkarpackie', 'Podlaskie',
                'Pomorskie', 'Warmi\u0144sko-mazurskie', 'Wielkopolskie', 'Zachodniopomorskie',
                '\u0141\xf3dzkie', '\u015al\u0105skie'],
    'INDIA': ['Andaman and Nicobar Islands', 'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar',
               'Chandigarh', 'Chhattisgarh', 'Dadra and Nagar Haveli', 'Daman and Diu', 'Delhi', 'Goa',
               'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jammu and Kashmir', 'Jharkhand', 'Karnataka',
               'Kerala', 'Lakshadweep', 'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya',
               'Mizoram', 'Nagaland', 'Odisha', 'Puducherry', 'Punjab', 'Rajasthan', 'Sikkim',
               'Tamil Nadu', 'Telangana', 'Tripura', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal'],
    'SUDAN': ['Al Bahr al Ahmar', 'Al Jazirah', 'Al Khartum', 'Al Qadarif', 'An Nil al Abyad',
               'An Nil al Azraq', 'Ash Shamaliyah', 'Gharb Darfur', 'Gharb Kurdufan', 'Janub Darfur',
               'Janub Kurdufan', 'Kassala', 'Nahr an Nil', 'Shamal Darfur', 'Sharq Darfur',
               'Shiamal Kurdufan', 'Sinnar', 'Wasat Darfur Zalinjay'],
    'CHRISTMAS ISLAND': ['Christmas Island'],
    'HUNGARY': ['Baranya', 'Borsod-Abauj-Zemplen', 'Budapest', 'B\xe1cs-Kiskun', 'B\xe9k\xe9s',
                 'B\xe9k\xe9scsaba', 'Csongr\xe1d', 'Debrecen', 'Duna\xfajv\xe1ros', 'Eger', 'Fej\xe9r',
                 'Gy\u0151r', 'Gy\u0151r-Moson-Sopron', 'Hajd\xfa-Bihar', 'Heves',
                 'H\xf3dmez\u0151v\xe1s\xe1rhely', 'J\xe1sz-Nagykun-Szolnok', 'Kaposv\xe1r', 'Kecskem\xe9t',
                 'Kom\xe1rom-Esztergom', 'Miskolc', 'Nagykanizsa', 'Ny\xedregyh\xe1za', 'N\xf3gr\xe1d',
                 'Pest', 'P\xe9cs', 'Salg\xf3tarj\xe1n', 'Somogy', 'Sopron', 'Szabolcs-\xe1-Bereg',
                 'Szeged', 'Szeksz\xe1rd', 'Szolnok', 'Szombathely', 'Sz\xe9kesfeh\xe9rv\xe1r',
                 'Tatab\xe1nya', 'Tolna', 'Vas', 'Veszpr\xe9m', 'Veszpr\xe9m (City)', 'Zala',
                 'Zalaegerszeg', '\xc9rd'],
    'SPAIN': ['A Coru\xf1a', 'Albacete', 'Alicante', 'Almer\xeda', 'Araba/\xc1lava', 'Asturias',
               'Badajoz', 'Barcelona', 'Bizkaia', 'Burgos', 'Cantabria', 'Castell\xf3n', 'Ciudad Real',
               'Cuenca', 'Cueta', 'C\xe1ceres', 'C\xe1diz', 'C\xf3rdoba', 'Gipuzkoa', 'Girona',
               'Granada', 'Guadalajara', 'Huelva', 'Huesca', 'Illes Balears', 'Ja\xe9n', 'La Rioja',
               'Las Palmas', 'Le\xf3n', 'Lleida', 'Lugo', 'Madrid', 'Melilla', 'Murcia', 'M\xe1laga',
               'Navarre', 'Ourense', 'Palencia', 'Pontevedra', 'Salamanca', 'Santa Cruz de Tenerife',
               'Segovia', 'Sevilla', 'Soria', 'Tarragona', 'Teruel', 'Toledo', 'Valencia', 'Valladolid',
               'Zamora', 'Zaragoza', '\xc1vila'],
    'SOLOMON ISLANDS': ['Central', 'Choiseul', 'Guadalcanal', 'Honiara', 'Isabel', 'Makira-Ulawa',
                         'Malaita', 'Rennell and Bellona', 'Temotu', 'Western'],
    'UNITED ARAB EMIRATES': ['Abu Dhabi', 'Ajman', 'Dubai', 'Fujairah', 'Ras al Khaimah', 'Sharjah',
                              'Umm Al Quwain'],
    'MALTA': ['Attard', 'Balzan', 'Birgu', 'Birkirkara', 'Bir\u017cebbu\u0121a', 'Bormla', 'Dingli',
               'Fgura', 'Floriana', 'Fontana', 'Guda', 'G\u0127ajnsielem', 'G\u0127arb',
               'G\u0127arg\u0127ur', 'G\u0127asri', 'G\u0127axaq', 'G\u017cira', 'Iklin', 'Isla',
               'Kalkara', 'Ker\u010bem', 'Kirkop', 'Lija', 'Luqa', 'Marsa', 'Marsaskala', 'Marsaxlokk',
               'Mdina', 'Mellie\u0127a', 'Mosta', 'Mqabba', 'Msida', 'Mtarfa', 'Munxar', 'M\u0121arr',
               'Nadur', 'Naxxar', 'Paola', 'Pembroke', 'Piet\xe0', 'Qala', 'Qormi', 'Qrendi',
               'Rabat G\u0127awdex', 'Rabat Malta', 'Safi', 'San Lawrenz', 'San Pawl il-Ba\u0127ar',
               'San \u0120iljan', 'San \u0120wann', 'Sannat', 'Santa Lu\u010bija', 'Santa Venera',
               'Si\u0121\u0121iewi', 'Sliema', 'Swieqi', 'Tai Xbiex', 'Tarzien', 'Valletta',
               'Xag\u0127ra', 'Xewkija', 'Xg\u0127ajra', '\u0126amrun', '\u017babbar',
               '\u017bebbu\u0121 G\u0127awde', '\u017bebbu\u0121 Malta', '\u017bejtun', '\u017burrieq'],
    'ANDORRA': ['Andorra la Vella', 'Canillo', 'Encamp', 'Escaldes-Engordany', 'La Massana', 'Ordino',
                 'Sant Juli\xe0 de L\xf2ria'],
    'DJIBOUTI': ['Ali Sabieh', 'Arta', 'Dikhil', 'Obock', 'Tadjourah'], 'R\xc9UNION': ['R\xe9union'],
    'MARSHALL ISLANDS': ['Ailinglaplap', 'Ailuk', 'Arno', 'Aur', 'Bikini and Kili', 'Ebon', 'Jabat',
                          'Jaluit', 'Kwajalein', 'Lae', 'Lib', 'Likiep', 'Majuro', 'Maloelap', 'Mejit',
                          'Namdrik', 'Namu', 'Rongelap', 'Ujae', 'Utrik', 'Wotho', 'Wotje'],
    'WALLIS AND FUTUNA': ['Alo', 'Sigave', 'Wallis'],
    'PARAGUAY': ['Alto Paraguay', 'Alto Parana', 'Amambay', 'Asuncion', 'Caaguazu', 'Caazapa',
                  'Canindeyu', 'Central', 'Concepcion', 'Cordillera', 'Guaira', 'Itapua', 'Misiones',
                  'Neembucu', 'Paraguari', 'Presidente Hayes', 'San Pedro'],
    'DOMINICAN REPUBLIC': ['Cibao Central', 'Del Valle', 'Distrito Nacional', 'Enriquillo', 'Norcentral',
                            'Nordeste', 'Noroeste', 'Norte', 'Valdesia'],
    'VIRGIN ISLANDS, BRITISH': ['Anegada', 'Jost Van Dyke', 'Tortola', 'Virgin Gorda'],
    'DOMINICA': ['Saint Andrew Parish', 'Saint David Parish', 'Saint George Parish', 'Saint John Parish',
                  'Saint Joseph Parish', 'Saint Luke Parish', 'Saint Mark Parish', 'Saint Patrick Parish',
                  'Saint Paul Parish', 'Saint Peter Parish'],
    'GHANA': ['Ashanti', 'Brong-Ahafo', 'Central', 'Eastern', 'Greater Accra', 'Northern', 'Upper East',
               'Upper West', 'Volta', 'Western'],
    'SAMOA': ["A'ana", 'Aiga-i-le-Tai', 'Atua', "Fa'asaleleaga", "Gaga'emauga", 'Gagaifomauga',
               'Palauli', "Satupa'itea", 'Tuamasaga', "Va'a-o-Fonoti", 'Vaisigano'],
    'NORTHERN MARIANA ISLANDS': ['Northern Islands', 'Rota', 'Saipan', 'Tinian'],
    'BHUTAN': ['Bumthang', 'Chhukha', 'Dagana', 'Gasa', 'Haa', 'Lhuntse', 'Mongar', 'Paro',
                'Pemagatshel', 'Punakha', 'Samdrup Jongkhar', 'Samtse', 'Sarpang', 'Thimphu',
                'Trashigang', 'Trashiyangtse', 'Trongsa', 'Tsirang', 'Wangdue Phodrang', 'Zhemgang'],
    'GUINEA': ['Bok\xe9', 'Conakry', 'Faranah', 'Kankan', 'Kindia', 'Lab\xe9', 'Mamou',
                'Nz\xe9r\xe9kor\xe9'],
    'SAN MARINO': ['Acquaviva', 'Borgo Maggiore', 'Chiesanuova', 'Domagnano', 'Faetano', 'Fiorentino',
                    'Montegiardino', 'San Marino', 'Serravalle'],
    'FRENCH POLYNESIA': ['Archipel des Marquises', 'Archipel des Tuamotu', 'Archipel des Tubuai',
                          'Iles Sous-le-Vent', 'Iles du Vent'],
    'TOKELAU': ['Atafu', 'Fakaofo', 'Nukunonu'],
    'GUATEMALA': ['Alta Verapaz', 'Baja Verapaz', 'Chimaltenango', 'Chiquimula', 'El Progreso',
                   'Escuintla', 'Guatemala', 'Huehuetenango', 'Izabal', 'Jalapa', 'Jutiapa', 'Pet\xe9n',
                   'Quetzaltenango', 'Quich\xe9', 'Retalhuleu', 'Sacatep\xe9quez', 'San Marcos',
                   'Santa Rosa', 'Solol\xe1', 'Suchitep\xe9quez', 'Totonicap\xe1n', 'Zacapa'],
    'BURUNDI': ['Bubanza', 'Bujumbura Mairie', 'Bujumbura Rural', 'Bururi', 'Cankuzo', 'Cibitoke',
                 'Gitega', 'Karuzi', 'Kayanza', 'Kirundo', 'Makamba', 'Muramvya', 'Muyinga', 'Mwaro',
                 'Ngozi', 'Rutana', 'Ruyigi'], 'GUADELOUPE': ['Guadeloupe'],
    'ERITREA': ['Anseba', 'Debub', 'Debub-Keih-Bahri', 'Gash-Barka', 'Maekel', 'Semien-Keih-Bahri'],
    'PORTUGAL': ['Acores', 'Aveiro', 'Beja', 'Braga', 'Braganca', 'Castelo Branco', 'Coimbra', 'Evora',
                  'Faro', 'Guarda', 'Leiria', 'Lisboa', 'Madeira', 'Portalegre', 'Porto', 'Santarem',
                  'Setubal', 'Viana do Castelo', 'Vila Real', 'Viseu'],
    'MONTENEGRO': ['Andrijevica', 'Bar', 'Berane', 'Bijelo Polje', 'Budva', 'Cetinje', 'Danilovgrad',
                    'Gusinje', 'Herceg Novi', 'Kola\u0161in', 'Kotor', 'Mojkovac', 'Nik\u0161i\u0107',
                    'Petnica', 'Plav', 'Pljevlja', 'Plu\u017eine', 'Podgorica', 'Ro\u017eaje', 'Tivat',
                    'Ulcinj', '\u0160avnik', '\u017dabljak'],
    'CROATIA': ['Bjelovarsko-Bilogorska \u017dupanija', 'Brodsko-Posavska \u017dupanija',
                 'Dubrova\u010dko-Neretvanska \u017dupanija', 'Grad Zagreb', 'Istarska \u017dupanija',
                 'Karlova\u010dka \u017dupanija', 'Koprivni\u010dko-Krizeva\u010dka \u017dupanija',
                 'Krapinsko-Zagorska \u017dupanija', 'Li\u010dko-Senjska \u017dupanija',
                 'Me\u0111imurska \u017dupanija', 'Osje\u010dko-Baranjska \u017dupanija',
                 'Po\u017ee\u0161ko-Slavonska \u017dupanija', 'Primorsko-Goranska \u017dupanija',
                 'Sibensko-Kninska \u017dupanija', 'Sisa\u010dko-Moslava\u010dka \u017dupanija',
                 'Splitsko-Dalmatinska \u017dupanija', 'Vara\u017edinska \u017dupanija',
                 'Viroviti\u010dko-Podravska \u017dupanija', 'Vukovarsko-Srijemska \u017dupanija',
                 'Zadarska \u017dupanija', 'Zagrebacka Zupanija'],
    'CAMBODIA': ['Baat Dambang', 'Banteay Mean Chey', 'Kampong Chaam', 'Kampong Chhnang', 'Kampong Spueu',
                  'Kampong Thum', 'Kampot', 'Kandaal', 'Kaoh Kong', 'Kracheh', 'Krong Kaeb',
                  'Krong Pailin', 'Krong Preah Sihanouk', 'Mondol Kiri', 'Otdar Mean Chey', 'Phnom Penh',
                  'Pousaat', 'Preah Vihear', 'Prey Veaeng', 'Rotanah Kiri', 'Siem Reab', 'Stueng Treng',
                  'Svaay Rieng', 'Taakaev', 'Tbong Khmum'],
    'KIRIBATI': ['Abaiang', 'Abemama', 'Aranuka', 'Arorae', 'Banaba', 'Beru', 'Butaritari',
                  'Central Gilberts', 'Gilbert Islands', 'Kanton', 'Kiritimati', 'Kuria', 'Line Islands',
                  'Maiana', 'Makin', 'Marakei', 'Nikunau', 'Nonouti', 'Northern Gilberts', 'Onotoa',
                  'Phoenix Islands', 'Southern Gilberts', 'Tabiteuea', 'Tabuaeran', 'Tamana', 'Tarawa',
                  'Teraina'],
    'BENIN': ['Alibori', 'Atakora', 'Atlantique', 'Borgou', 'Collines Department', 'Donga', 'Kouffo',
               'Littoral Department', 'Mono Department', 'Ou\xe9m\xe9', 'Plateau', 'Zou'],
    'PALESTINE, STATE OF': ['Ak Khal\u012bl', 'Al Quds', 'Ar\u012b\u1e29\u0101 wal Aghw\u0101r',
                             'Bayt La\u1e29m', 'Dayr al Bala\u1e29', 'Ghazzah', 'Jan\u012bn',
                             'Kh\u0101n Y\u016bnis', 'N\u0101blus', 'Qalq\u012byah', 'Rafa\u1e29',
                             'R\u0101m All\u0101h wal B\u012brah', 'Salf\u012bt', 'Sham\u0101l Ghazzah',
                             '\u0162\u016bb\u0101s', '\u0162\u016blkarm'],
    'COSTA RICA': ['Alajuela', 'Cartago', 'Guanacaste', 'Heredia', 'Lim\xf3n', 'Puntarenas',
                    'San Jos\xe9'],
    'ETHIOPIA': ['Addis Ababa', 'Afar', 'Amhara', 'Benshangul-Gumaz', 'Dire Dawa', 'Gambela', 'Harari',
                  'Oromia', 'Somali', "Southern Nations Nationalities and People's Region", 'Tigray'],
    'SWEDEN': ['Blekinge', 'Dalarnas', 'Gavleborgs', 'Gotlands', 'Hallands', 'Jamtlands', 'Jonkopings',
                'Kalmar', 'Kronobergs', 'Norrbottens', 'Orebro', 'Ostergotlands', 'Skane',
                'Sodermanlands', 'Stockholm', 'Varmlands', 'Vasterbottens', 'Vasternorrlands',
                'Vastmanlands', 'Vastra Gotalands'],
    'HEARD ISLAND AND MCDONALD ISLANDS': ['Heard Island and McDonald Islands'],
    'TIMOR-LESTE': ['Aileu', 'Ainaro', 'Baucau', 'Bobonaro', 'Cova Lima', 'Dili', 'Ermera', 'Lautem',
                     'Liquica', 'Manatuto', 'Manufahi', 'Oecussi', 'Viqueque'],
    'HOLY SEE (VATICAN CITY)': ['Holy See (Vatican City)'],
    'NORWAY': ['Akershus', 'Aust-Agder', 'Buskerud', 'Finnmark', 'Hedmark', 'Hordaland', 'Jan Mayen',
                'M\xf8re og Romsdal', 'Nord-Tr\xf8ndelag', 'Nordland', 'Oppland', 'Oslo', 'Rogaland',
                'Sogn og Fjordane', 'Svalbard', 'S\xf8r-Tr\xf8ndelag', 'Telemark', 'Troms', 'Vest-Agder',
                'Vestfold', '\xd8stfold'],
    'QATAR': ['Ad Daw\u1e29ah', 'Al Khawr wa adh Dhakh\u012brah', 'Al Wakrah', 'Ar Rayy\u0101n',
               'Ash Sham\u0101l', 'Az\u0327 Za\u0327`\u0101yin', 'Umm \u015eal\u0101l'],
    'PALAU': ['Aimeliik', 'Airai', 'Angaur', 'Hatobohei', 'Kayangel', 'Koror', 'Melekeok', 'Ngaraard',
               'Ngarchelong', 'Ngardmau', 'Ngatpang', 'Ngchesar', 'Ngeremlengui', 'Ngiwal', 'Peleliu',
               'Sonsoral'], 'NORFOLK ISLAND': ['Norfolk Island'],
    'DENMARK': ['Hovedstaden', 'Kujalleq', 'Midtjylland', 'Norder\xf8erne', 'Nordjylland', 'Qaasuitsup',
                 'Qeqqata', 'Sand\xf8', 'Sermersooq', 'Sj\xe6lland', 'Str\xf8m\xf8', 'Suder\xf8',
                 'Syddanmark', 'V\xe5g\xf8', '\xd8ster\xf8'],
    'NEPAL': ['Bagmati', 'Bheri', 'Dhawalagiri', 'Gandaki', 'Janakpur', 'Karnali', 'Kosi', 'Lumbini',
               'Mahakali', 'Mechi', 'Narayani', 'Rapti', 'Sagarmatha', 'Seti'],
    'PAPUA NEW GUINEA': ['Bougainville', 'Central', 'Chimbu', 'East New Britain', 'East Sepik',
                          'Eastern Highlands', 'Enga', 'Gulf', 'Hela', 'Jiwaka', 'Madang', 'Manus',
                          'Milne Bay', 'Morobe', 'New Ireland', 'Northern', 'Port Moresby',
                          'Southern Highlands', 'West New Britain', 'West Sepik', 'Western',
                          'Western Highlands'],
    'ZIMBABWE': ['Bulawayo', 'Harare', 'Manicaland', 'Mashonaland Central', 'Mashonaland East',
                  'Mashonaland West', 'Masvingo', 'Matabeleland North', 'Matabeleland South', 'Midlands'],
    'GABON': ['Estuaire', 'Haut-Ogoou\xe9', 'Moyen-Ogoou\xe9', 'Ngouni\xe9', 'Nyanga', 'Ogoou\xe9-Ivindo',
               'Ogoou\xe9-Lolo', 'Ogoou\xe9-Maritime', 'Woleu-Ntem'],
    'YEMEN': ["'Adan", "'Amr\u0101n", 'Aby\u0101n', "Al Bay\u1e11\u0101'", 'Al Jawf', 'Al Mahrah',
               'Al Ma\u1e29w\u012bt', 'Al \u1e28udaydah', "A\u1e11 \u1e10\u0101li'", 'Dham\u0101r', 'Ibb',
               'La\u1e29ij', "Ma'rib", 'Raymah', 'Shabwah', 'T\u0101\u2018izz', "\u015ean\u2018\u0101'",
               '\u015e\u0101\u2018dah', '\u1e28ajjah', '\u1e28a\u1e11ramawt'],
    'AUSTRALIA': ['Australian Capital Territory', 'New South Wales', 'Northern Territory', 'Queensland',
                   'South Australia', 'Tasmania', 'Victoria', 'Western Australia'],
    'SOUTH GEORGIA AND SOUTH SANDWICH ISLANDS': ['Bird Island', 'Bristol Island', 'Clerke Rocks',
                                                  'Montagu Island', 'Saunders Island', 'South Georgia',
                                                  'Southern Thule', 'Traversay Islands'],
    'PITCAIRN': ['Pitcairn Islands'],
    'KUWAIT': ['Al A\u1e29madi', 'Al Farw\u0101n\u012byah', 'Al Jahr\u0101\u2019',
                'Al \u2018\u0100\u015fimah', 'Mub\u0101rak al Kabir', '\u1e28awall\u012b'],
    'CENTRAL AFRICAN REPUBLIC': ['Bamingui-Bangoran', 'Bangui', 'Basse-Kotto', 'Haut-Mbomou',
                                  'Haute-Kotto', 'K\xe9mo', 'Lobaye', 'Mamb\xe9r\xe9-Kad\xe9\xef', 'Mbomou',
                                  'Nana-Grebizi', 'Nana-Mamb\xe9r\xe9', "Ombella-M'Poko", 'Ouaka', 'Ouham',
                                  'Ouham P\xe9nd\xe9', 'Sangha-Mba\xe9r\xe9', 'Vakaga'],
    'ARMENIA': ['Aragatsotn', 'Ararat', 'Armavir', 'Gegharkunik', 'Kotayk', 'Lori', 'Shirak', 'Syunik',
                 'Tavush', 'Vayots Dzor', 'Yerevan'],
    'COMOROS': ['Andjaz\xeedja', 'Andjou\xe2n', 'Mo\xfbh\xeel\xee'],
    'MACEDONIA, REPUBLIC OF': ['Ara\u010dinovo', 'Berovo', 'Bitola', 'Bogdanci', 'Bogovinje', 'Bosilovo',
                                'Brvenica', 'Centar \u017dupa', 'Debar', 'Debarca', 'Del\u010devo',
                                'Demir Hisar', 'Demir Kapija', 'Dolneni', 'Doran', 'Gevgelija', 'Gostivar',
                                'Gradsko', 'Ilinden', 'Jegunovce', 'Karbinci', 'Kavadarci', 'Ki\u010devo',
                                'Kon\u010de', 'Ko\u010dani', 'Kratovo', 'Kriva Palanka',
                                'Krivoga\u0161tani', 'Kru\u0161evo', 'Kumanovo', 'Lipkovo', 'Lozovo',
                                'Makedonska Kamenica', 'Makedonski Brod', 'Mavrovo i Rostu\u0161a', 'Mogila',
                                'Negotino', 'Novaci', 'Novo Selo', 'Ohrid', 'Peh\u010devo', 'Petrovec',
                                'Plasnica', 'Prilep', 'Probi\u0161tip', 'Radovi\u0161', 'Rankovce',
                                'Resen', 'Rosoman', 'Skopje', 'Sopi\u0161te', 'Staro Nagori\u010dane',
                                'Struga', 'Strumica', 'Studeni\u010dani', 'Sveti Nikole', 'Tearce',
                                'Tetovo', 'Valandovo', 'Vasilevo', 'Veles', 'Vev\u010dani', 'Vinica',
                                'Vrap\u010di\u0161te', 'Zelenikovo', 'Zrnovci', '\u010ca\u0161ka',
                                '\u010ce\u0161inovo-Oble\u0161evo', '\u010cu\u010der Sandevo', '\u0160tip',
                                '\u017delino'],
    'TONGA': ["'Eua", "Ha'apai", 'Niuas', 'Tongatapu', "Vava'u"],
    'HONDURAS': ['Atl\xe1ntida', 'Choluteca', 'Col\xf3n', 'Comayagua', 'Cop\xe1n', 'Cort\xe9s',
                  'El Para\xedso', 'Francisco Morazan', 'Gracias a Dios', 'Intibuc\xe1',
                  'Islas de la Bah\xeda', 'La Paz', 'Lempira', 'Ocotepeque', 'Olancho', 'Santa B\xe1rbara',
                  'Valle', 'Yoro'],
    'MAYOTTE': ['Acoua', 'Bandraboua', 'Bandr\xe9l\xe9', 'Bou\xe9ni', 'Chiconi', 'Chirongui', 'Dembeni',
                 'Dzaoudzi', 'Kani-K\xe9li', 'Koungou', "M'Tsangamouji", 'Mamoudzou', 'Mtsamboro',
                 'Ouangani', 'Pamandzi', 'Sada', 'Tsingoni'],
    'VIET NAM': ['C\u1ea7n Th\u01a1', 'Gia Lai', 'H\xe0 Giang', 'H\xe0 Nam', 'H\xe0 N\u1ed9i',
                  'H\xe0 T\xe2y', 'H\xe0 T\u0129nh', 'H\xf2a B\xecnh', 'H\u01b0ng Y\xean',
                  'H\u1ea3i D\u01b0\u01a1ng', 'H\u1ea3i Ph\xf2ng', 'H\u1eadu Giang',
                  'H\u1ed3 Ch\xed Minh (S\xe0i G\xf2n)', 'Kh\xe1nh H\xf2a', 'Ki\xean Giang', 'Kon Tum',
                  'Lai Ch\xe2u', 'Long An', 'L\xe0o Cai', 'L\xe2m \u0110\u1ed3ng', 'L\u1ea1ng S\u01a1n',
                  'Nam \u0110\u1ecbnh', 'Ngh\u1ec7 An', 'Ninh B\xecnh', 'Ninh Thu\u1eadn',
                  'Ph\xfa Th\u1ecd', 'Ph\xfa Y\xean', 'Qu\u1ea3ng B\xecnh', 'Qu\u1ea3ng Nam',
                  'Qu\u1ea3ng Ng\xe3i', 'Qu\u1ea3ng Ninh', 'Qu\u1ea3ng Tr\u1ecb', 'S\xf3c Tr\u0103ng',
                  'S\u01a1n La', 'Thanh H\xf3a', 'Th\xe1i B\xecnh', 'Th\xe1i Nguy\xean',
                  'Th\u1eeba Thi\xean\u2013Hu\u1ebf', 'Ti\u1ec1n Giang', 'Tr\xe0 Vinh', 'Tuy\xean Quang',
                  'T\xe2y Ninh', 'V\u0129nh Long', 'V\u0129nh Ph\xfac', 'Y\xean B\xe1i',
                  '\u0110\xe0 N\u1eb5ng', '\u0110\u1ed3ng Nai', '\u0110\u1ed3ng Th\xe1p'],
    'ANTIGUA AND BARBUDA': ['Antigua Island', 'Barbuda Island', 'Bird Island', 'Bishop Island',
                             'Blake Island', 'Crump Island', 'Dulcina Island', 'Exchange Island',
                             'Five Islands', 'Great Bird Island', 'Green Island', 'Guiana Island',
                             'Hawes Island', 'Hells Gate Island', 'Henry Island', 'Johnson Island',
                             'Kid Island', 'Lobster Island', 'Maiden Island', 'Moor Island', 'Nanny Island',
                             'Pelican Island', 'Prickly Pear Island', 'Rabbit Island', 'Red Head Island',
                             'Redonda Island', 'Sandy Island', 'Smith Island', 'The Sisters',
                             'Vernon Island', 'Wicked Will Island', 'York Island'],
    'SWITZERLAND': ['Aargau', 'Appenzell Ausserrhoden', 'Appenzell Innerhoden', 'Basel-Landschaft',
                     'Basel-Stadt', 'Bern', 'Fribourg', 'Gen\xe8ve', 'Glarus', 'Graub\xfcnden', 'Jura',
                     'Luzern', 'Neuch\xe2tel', 'Nidwalden', 'Obwalden', 'Sankt Gallen', 'Schaffhausen',
                     'Schwyz', 'Solothurn', 'Thurgau', 'Ticino', 'Uri', 'Valais', 'Waadt', 'Zug',
                     'Z\xfcrich'],
    'CANADA': ['Alberta', 'British Columbia', 'Manitoba', 'New Brunswick', 'Newfoundland and Labrador',
                'Northwest Territories', 'Nova Scotia', 'Nunavut', 'Ontario', 'Prince Edward Island',
                'Quebec', 'Saskatchewan', 'Yukon'],
    'JAMAICA': ['Clarendon', 'Hanover', 'Kingston', 'Manchester', 'Portland', 'Saint Andrew',
                 'Saint Ann', 'Saint Catherine', 'Saint Elizabeth', 'Saint James', 'Saint Mary',
                 'Saint Thomas', 'Trelawny', 'Westmoreland'],
    'SINGAPORE': ['Central Singapore', 'North East', 'North West', 'South East', 'South West'],
    'EGYPT': ['Alexandria', 'Aswan', 'Asyout', 'Bani Sueif', 'Beheira', 'Cairo', 'Daqahlia', 'Dumiat',
               'El Bahr El Ahmar', 'El Ismailia', 'El Suez', 'El Wadi El Gedeed', 'Fayoum', 'Gharbia',
               'Giza', 'Helwan', 'Kafr El Sheikh', 'Luxor', 'Matrouh', 'Menia', 'Menofia', 'North Sinai',
               'Port Said', 'Qalubia', 'Qena', 'Sharqia', 'Sixth of October', 'Sohag', 'South Sinai'],
    'CUBA': ['Artemisa', 'Camag\xfcey', 'Ciego de \xc1vila', 'Cienfuegos', 'Granma', 'Guant\xe1namo',
              'Holgu\xedn', 'Isla de la Juventud', 'La Habana', 'Las Tunas', 'Matanzas', 'Mayabeque',
              'Pinar del R\xedo', 'Sancti Sp\xedritus', 'Santiago de Cuba', 'Villa Clara'],
    'LEBANON': ['Aakk\xe2r', 'Baalbelk-Hermel', 'Beyrouth', 'B\xe9qaa', 'Liban-Nord', 'Liban-Sud',
                 'Mont-Liban', 'Nabat\xeey\xe9'], 'SAINT PIERRE AND MIQUELON': ['Miquelon', 'Saint Pierre'],
    '\xc5LAND ISLANDS': ['Br\xe4nd\xf6', 'Ecker\xf6', 'Finstr\xf6m', 'F\xf6gl\xf6', 'Geta', 'Hammarland',
                          'Jomala', 'Kumlinge', 'K\xf6kar', 'Lemland', 'Lumparland', 'Mariehamn',
                          'Saltvik', 'Sottunga', 'Sund', 'V\xe5rd\xf6'],
    'COCOS (KEELING) ISLANDS': ['Direction Island', 'Home Island', 'Horsburgh Island',
                                 'North Keeling Island', 'South Island', 'West Island'],
    'FAROE ISLANDS': ['Bordoy', 'Eysturoy', 'Mykines', 'Sandoy', 'Skuvoy', 'Streymoy', 'Suduroy',
                       'Tvoroyri', 'Vagar'],
    'SENEGAL': ['Dakar', 'Diourbel', 'Fatick', 'Kaffrine', 'Kaolack', 'Kedougou', 'Kolda', 'Louga',
                 'Matam', 'Saint-Louis', 'Sedhiou', 'Tambacounda', 'Thies', 'Ziguinchor'],
    'COOK ISLANDS': ['Aitutaki', 'Atiu', 'Avarua', "Ma'uke", 'Mangaia', 'Manihiki', 'Mitiaro', 'Nassau',
                      'Palmerston', 'Penrhyn', 'Pukapuka', 'Rakahanga'],
    'SEYCHELLES': ['Anse Boileau', 'Anse Etoile', 'Anse Royale', 'Anse aux Pins', 'Anu Cap',
                    'Baie Lazare', 'Baie Sainte Anne', 'Beau Vallon', 'Bel Air', 'Bel Ombre', 'Cascade',
                    'Glacis', "Grand'Anse Mahe", "Grand'Anse Praslin", 'La Digue', 'La Riviere Anglaise',
                    'Les Mamelles', 'Mont Buxton', 'Mont Fleuri', 'Plaisance', 'Pointe La Rue',
                    'Port Glaud', 'Roche Caiman', 'Saint Louis', 'Takamaka'],
    'ANGOLA': ['Bengo', 'Benguela', 'Bi\xe9', 'Cabinda', 'Cuando Cubango', 'Cuanza Norte', 'Cuanza Sul',
                'Cunene', 'Huambo', 'Hu\xedla', 'Luanda', 'Lunda Norte', 'Lunda Sul', 'Malanje',
                'Moxico', 'Namibe', 'U\xedge', 'Zaire'],
    'MALAYSIA': ['Johor', 'Kedah', 'Kelantan', 'Melaka', 'Negeri Sembilan', 'Pahang', 'Perak', 'Perlis',
                  'Pulau Pinang', 'Sabah', 'Sarawak', 'Selangor', 'Terengganu',
                  'Wilayah Persekutuan (Kuala Lumpur)', 'Wilayah Persekutuan (Labuan)',
                  'Wilayah Persekutuan (Putrajaya)'],
    'SAINT VINCENT AND THE GRENADINES': ['Charlotte', 'Grenadines', 'Saint Andrew', 'Saint David',
                                          'Saint George', 'Saint Patrick'],
    'RUSSIAN FEDERATION': ['Adygeya', 'Altay (Gorno-Altaysk)', 'Altayskiy', 'Amurskaya', "Arkhangel'skaya",
                            'Astrakhanskaya', 'Bashkortostan', 'Belgorodskaya', 'Bryanskaya', 'Buryatiya',
                            'Chechenskaya', 'Chelyabinskaya', 'Chukotskiy', 'Chuvashskaya', 'Dagestan',
                            'Ingushetiya', 'Irkutskaya', 'Ivanovskaya', 'Kabardino-Balkariya', 'Kalmykiya',
                            'Kaluzhskaya', 'Kamchatskaya', 'Karachayevo-Cherkesiya', 'Kareliya',
                            'Khabarovskiy', 'Khakasiya', 'Khanty-Mansiyskiy', 'Kirovskaya', 'Komi',
                            'Kostromskaya', 'Krasnodarskiy', 'Krasnoyarskiy', 'Kurganskaya', 'Kurskaya',
                            'Leningradskaya', 'Lipetskaya', 'Magadanskaya', 'Mariy-El', 'Mordoviya',
                            'Moskovskaya', 'Moskva', 'Murmanskaya', 'Nenetskiy', 'Nizhegorodskaya',
                            'Novgorodskaya', 'Novosibirskaya', 'Omskaya', 'Orenburgskaya', 'Orlovskaya',
                            'Permskaya', 'Permskiy', 'Primorskiy', 'Pskovskaya', 'Rostovskaya',
                            'Ryazanskaya', 'Sakha (Yakutiya)', 'Sakhalinskaya', 'Samarskaya',
                            'Sankt-Peterburg', 'Saratovskaya', 'Severnaya Osetiya-Alaniya', 'Smolenskaya',
                            "Stavropol'skiy", 'Sverdlovskaya', 'Tambovskaya', 'Tatarstan', 'Tomskaya',
                            "Tul'skaya", 'Tverskaya', 'Tyumenskaya', 'Tyva', 'Udmurtskaya',
                            "Ul'yanovskaya", 'Vladimirskaya', 'Volgogradskaya', 'Vologodskaya',
                            'Voronezhskaya', 'Yamalo-Nenetskiy', 'Yaroslavskaya', 'Yevreyskaya',
                            "Zabaykal'skiy"],
    'NEW ZEALAND': ['Auckland (T\u0101maki-makau-rau)', 'Bay of Plenty (Te Moana a Toi Te Huatahi)',
                     'Canterbury (Waitaha)', 'Chatham Islands Territory (Wharekauri)',
                     'Gisborne (T\u016branga nui a Kiwa)', "Hawke's Bay (Te Matau a M\u0101ui)",
                     'Manawatu-Wanganui (Manawatu Whanganui)', 'Marlborough', 'Nelson (Whakat\u016b)',
                     'Northland (Te Tai tokerau)', 'Otago (\u014c T\u0101kou)', 'Southland (Murihiku)',
                     'Taranaki (Taranaki)', 'Tasman', 'Waikato', 'Wellington (Te Whanga-nui-a-Tara)',
                     'West Coast (Te Taihau \u0101 uru)'], 'SAINT MARTIN': ['Saint Martin'],
    'KYRGYZSTAN': ['Batken Oblasty', 'Bishkek Shaary', 'Chuy Oblasty (Bishkek)', 'Jalal-Abad Oblasty',
                    'Naryn Oblasty', 'Osh Oblasty', 'Talas Oblasty', 'Ysyk-Kol Oblasty (Karakol)'],
    'WESTERN SAHARA': ['Aousserd', 'Boujdour', 'Es Smara', 'La\xe2youne', 'Oued ed Dahab'],
    'BOUVET ISLAND': ['Bouvet Island'],
    'BRUNEI DARUSSALAM': ['Belait', 'Brunei Muara', 'Temburong', 'Tutong'],
    'LESOTHO': ['Berea', 'Butha-Buthe', 'Leribe', 'Mafeteng', 'Maseru', 'Mohales Hoek', 'Mokhotlong',
                 "Qacha's Nek", 'Quthing', 'Thaba-Tseka'],
    'SYRIAN ARAB REPUBLIC': ['Al Hasakah', 'Al Ladhiqiyah', 'Al Qunaytirah', 'Ar Raqqah', "As Suwayda'",
                              "Dar'a", 'Dayr az Zawr', 'Dimashq', 'Halab', 'Hamah', 'Hims', 'Idlib',
                              'Rif Dimashq', 'Tartus'],
    'CONGO, THE DEMOCRATIC REPUBLIC OF THE (KINSHASA)': ['Bandundu', 'Bas-Congo', 'Kasa\xef-Occidental',
                                                          'Kasa\xef-Oriental', 'Katanga', 'Kinshasa',
                                                          'Maniema', 'Nord-Kivu', 'Orientale', 'Sud-Kivu',
                                                          '\xc9quateur'],
    'JAPAN': ['Aichi', 'Akita', 'Aomori', 'Chiba', 'Ehime', 'Fukui', 'Fukuoka', 'Fukushima', 'Gifu',
               'Gunma', 'Hiroshima', 'Hokkaido', 'Hukui', 'Hukuoaka', 'Hukusima', 'Hyogo', 'Ibaraki',
               'Ishikawa', 'Iwate', 'Kagawa', 'Kagoshima', 'Kanagawa', 'Kochi', 'Kumamoto', 'Kyoto',
               'Mie', 'Miyagi', 'Miyazaki', 'Nagano', 'Nagasaki', 'Nara', 'Niigata', 'Oita', 'Okayama',
               'Okinawa', 'Osaka', 'Saga', 'Saitama', 'Shimane', 'Shizuoka', 'Siga', 'Tiba', 'Tochigi',
               'Tokushima', 'Totigi', 'Tottori', 'Toyama', 'Wakayama', 'Yamagata', 'Yamaguchi',
               'Yamanashi'], 'JERSEY': ['Jersey'],
    'UKRAINE': ['Avtonomna Respublika Krym', 'Cherkasy', 'Chernihiv', 'Chernivtsi', 'Dnipropetrovsk',
                 'Donetsk', 'Ivano-Frankivsk', 'Kharkiv', 'Kherson', 'Khmelnytskyi', 'Kiev', 'Kirovohrad',
                 'Ky\xefv', 'Luhansk', 'Lviv', 'Mykolaiv', 'Odessa', 'Poltava', 'Rivne', 'Sevastopol',
                 'Sumy', 'Ternopil', 'Vinnytsia', 'Volyn', 'Zakarpattia', 'Zaporizhia', 'Zhytomyr'],
    'CHAD': ['Bahr el Ghazal', 'Batha', 'Borkou', 'Chari-Baguirmi', 'Ennedi-Est', 'Ennedi-Ouest',
              'Gu\xe9ra', 'Hadjer Lamis', 'Kanem', 'Lac', 'Logone Occidental', 'Logone Oriental',
              'Mayo-K\xe9bbi-Est', 'Mondoul', 'Moyen-Chari', 'Ouaddai', 'Salamat', 'Sila', 'Tandjil\xe9',
              'Tibesti', 'Ville de Ndjamena', 'Wadi Fira'],
    'LITHUANIA': ['Alytaus', 'Kauno', 'Klaip\u0117dos', 'Marijampol\u0117s', 'Panev\u0117\u017eio',
                   'Taurag\u0117s', 'Tel\u0161i\u0173', 'Utenos', 'Vilniaus', '\u0160iauli\u0173'],
    'UNITED KINGDOM': ['Aberdeen, City of', 'Aberdeenshire', 'Angus (Forfarshire)', 'Antrim', 'Argyll',
                        'Armagh', 'Avon', 'Ayrshire', 'Banffshire', 'Bedfordshire', 'Belfast, City of',
                        'Berkshire', 'Berwickshire', 'Bristol, City of', 'Buckinghamshire', 'Bute',
                        'Caithness', 'Cambridgeshire', 'Cheshire', 'Clackmannanshire', 'Cleveland',
                        'Clwyd', 'Cornwall', 'Cromartyshire', 'Cumbria', 'Derbyshire', 'Derry, City of',
                        'Devon', 'Dorset', 'Down', 'Dumfriesshire', 'Dunbartonshire (Dumbarton)',
                        'Dundee, City of', 'Durham', 'Dyfed', 'East Lothian (Haddingtonshire)',
                        'East Sussex', 'Edinburgh, City of', 'Essex', 'Fermanagh', 'Fife',
                        'Glasgow, City of', 'Gloucestershire', 'Greater London', 'Greater Manchester',
                        'Gwent', 'Gwynedd', 'Hampshire (County of Southampton)', 'Hereford and Worcester',
                        'Herefordshire', 'Hertfordshire', 'Inverness-shire', 'Isle of Wight', 'Kent',
                        'Kincardineshire', 'Kinross-shire', 'Kirkcudbrightshire', 'Lanarkshire',
                        'Lancashire', 'Leicestershire', 'Lincolnshire', 'London', 'Londonderry',
                        'Merseyside', 'Mid Glamorgan', 'Middlesex', 'Midlothian (County of Edinburgh)',
                        'Moray (Elginshire)', 'Nairnshire', 'Norfolk', 'North Humberside',
                        'North Yorkshire', 'Northamptonshire', 'Northumberland', 'Nottinghamshire',
                        'Orkney', 'Oxfordshire', 'Peeblesshire', 'Perthshire', 'Powys', 'Renfrewshire',
                        'Ross and Cromarty', 'Ross-shire', 'Roxburghshire', 'Rutland', 'Selkirkshire',
                        'Shetland (Zetland)', 'Shropshire', 'Somerset', 'South Glamorgan',
                        'South Humberside', 'South Yorkshire', 'Staffordshire', 'Stirlingshire', 'Suffolk',
                        'Surrey', 'Sutherland', 'Tyne and Wear', 'Tyrone', 'Warwickshire',
                        'West Glamorgan', 'West Lothian (Linlithgowshire)', 'West Midlands', 'West Sussex',
                        'West Yorkshire', 'Wigtownshire', 'Wiltshire', 'Worcestershire'],
    'MOROCCO': ['Chaouia-Ouardigha', 'Doukhala-Abda', 'F\xe8s-Boulemane', 'Gharb-Chrarda-Beni Hssen',
                 'Grand Casablanca', 'Guelmim-Es Semara', 'La\xe2youne-Boujdour-Sakia el Hamra',
                 'Marrakech-Tensift-Al Haouz', 'Mekn\xe8s-Tafilalet', 'Oriental', 'Oued ed Dahab-Lagouira',
                 'Souss-Massa-Dr\xe2a', 'Tadla-Azilal', 'Tanger-T\xe9touan', 'Taza-Al Hoceima-Taounate'],
    'GEORGIA': ['Abkhazia (Sokhumi)', "Ajaria (Bat'umi)", 'Guria', 'Imereti', "K'akheti", 'Kvemo Kartli',
                 'Mtshkheta-Mtianeti', "Rach'a-Lexhkumi-KvemoSvaneti", 'Samegrelo-Zemo Svaneti',
                 'Samtskhe-Javakheti', 'Shida Kartli', 'Tbilisi'],
    'UGANDA': ['Abim', 'Adjumani', 'Amolatar', 'Amuria', 'Amuru', 'Apac', 'Arua', 'Budaka', 'Bududa',
                'Bugiri', 'Bukedea', 'Bukwa', 'Buliisa', 'Bundibugyo', 'Bushenyi', 'Busia', 'Butaleja',
                'Dokolo', 'Gulu', 'Hoima', 'Ibanda', 'Iganga', 'Isingiro', 'Jinja', 'Kaabong', 'Kabale',
                'Kabarole', 'Kaberamaido', 'Kalangala', 'Kaliro', 'Kampala', 'Kamuli', 'Kamwenge',
                'Kanungu', 'Kapchorwa', 'Kasese', 'Katakwi', 'Kayunga', 'Kibaale', 'Kiboga', 'Kiruhura',
                'Kisoro', 'Kitgum', 'Koboko', 'Kotido', 'Kumi', 'Kyenjojo', 'Lira', 'Luwero',
                'Lyantonde', 'Manafwa', 'Maracha', 'Masaka', 'Masindi', 'Mayuge', 'Mbale', 'Mbarara',
                'Mityana', 'Moroto', 'Moyo', 'Mpigi', 'Mubende', 'Mukono', 'Nakapiripirit', 'Nakaseke',
                'Nakasongola', 'Namutumba', 'Nebbi', 'Ntungamo', 'Oyam', 'Pader', 'Pallisa', 'Rakai',
                'Rukungiri', 'Sembabule', 'Sironko', 'Soroti', 'Tororo', 'Wakiso', 'Yumbe'],
    'TANZANIA, UNITED REPUBLIC OF': ['Arusha', 'Coast', 'Dar es Salaam', 'Dodoma', 'Iringa', 'Kagera',
                                      'Kigoma', 'Kilimanjaro', 'Lindi', 'Manyara', 'Mara', 'Mbeya',
                                      'Morogoro', 'Mtwara', 'Mwanza', 'Pemba North', 'Pemba South',
                                      'Rukwa', 'Ruvuma', 'Shinyanga', 'Singida', 'Tabora', 'Tanga',
                                      'Zanzibar Central/South', 'Zanzibar North', 'Zanzibar Urban/West'],
    'BOLIVIA': ['Beni', 'Chuquisaca', 'Cochabamba', 'La Paz', 'Oruro', 'Pando', 'Potos\xed',
                 'Santa Cruz', 'Tarija'],
    'BOTSWANA': ['Central', 'Ghanzi', 'Kgalagadi', 'Kgatleng', 'Kweneng', 'North West', 'North-East',
                  'South East', 'Southern'],
    'BRAZIL': ['Acre', 'Alagoas', 'Amap\xe1', 'Amazonas', 'Bahia', 'Cear\xe1', 'Distrito Federal',
                'Esp\xedrito Santo', 'Goi\xe1s', 'Maranh\xe3o', 'Mato Grosso', 'Mato Grosso do Sul',
                'Minas Gerais', 'Para', 'Paraiba', 'Paran\xe1', 'Pernambuco', 'Piau\xed',
                'Rio Grande do Norte', 'Rio Grande do Sul', 'Rio de Janeiro', 'Rond\xf4nia', 'Roraima',
                'Santa Catarina', 'Sao Paulo', 'Sergipe', 'Tocantins'],
    'MADAGASCAR': ['Antananarivo', 'Antsiranana', 'Fianarantsoa', 'Mahajanga', 'Toamasina', 'Toliara'],
    'VIRGIN ISLANDS, U.S.': ['St. Croix', 'St. John', 'St. Thomas'],
    'GERMANY': ['Baden-W\xfcrttemberg', 'Bayern', 'Berlin', 'Brandenburg', 'Bremen', 'Hamburg', 'Hessen',
                 'Mecklenburg-Vorpommern', 'Niedersachsen', 'Nordrhein-Westfalen', 'Rheinland-Pfalz',
                 'Saarland', 'Sachsen', 'Sachsen-Anhalt', 'Schleswig-Holstein', 'Th\xfcringen'],
    'PUERTO RICO': ['Adjuntas', 'Aguada', 'Aguadilla', 'Aguas Buenas', 'Aibonito', 'Anasco', 'Arecibo',
                     'Arroyo', 'Barceloneta', 'Barranquitas', 'Bayamon', 'Cabo Rojo', 'Caguas', 'Camuy',
                     'Canovanas', 'Carolina', 'Cat', 'Ceiba', 'Ciales', 'Cidra', 'Coamo', 'Comerio',
                     'Corozal', 'Culebra', 'Dorado', 'Fajardo', 'Florida', 'Guanica', 'Guayama',
                     'Guayanilla', 'Guaynabo', 'Gurabo', 'Hatillo', 'Hormigueros', 'Humacao', 'Isabe',
                     'Juana Diaz', 'Juncos', 'Lajas', 'Lares', 'Las Marias', 'Las oiza', 'Luquillo',
                     'Manati', 'Maricao', 'Maunabo', 'Mayaguez', 'Moca', 'Morovis', 'Naguabo',
                     'Naranjito', 'Orocovis', 'Patillas', 'Penuelas', 'Ponce', 'Quebradillas', 'Rincon',
                     'Rio Grande', 'Sabana linas', 'San German', 'San Juan', 'San Lorenzo',
                     'San Sebastian', 'Santa Isabel', 'Toa Alta', 'Toa Baja', 'Trujillo Alto', 'Utuado',
                     'Vega Alta', 'Vega ues', 'Villalba', 'Yabucoa', 'Yauco'],
    'NIGER': ['Agadez', 'Diffa', 'Dosso', 'Maradi', 'Niamey', 'Tahoua', 'Tillab\xe9ri', 'Zinder'],
    'NICARAGUA': ['Atl\xe1ntico Norte', 'Atl\xe1ntico Sur', 'Boaco', 'Carazo', 'Chinandega', 'Chontales',
                   'Estel\xed', 'Granada', 'Jinotega', 'Le\xf3n', 'Madriz', 'Managua', 'Masaya',
                   'Matagalpa', 'Nueva Segovia', 'Rivas', 'R\xedo San Juan'],
    'SOMALIA': ['Awdal', 'Bakool', 'Banaadir', 'Bari', 'Bay', 'Galguduud', 'Gedo', 'Hiiraan',
                 'Jubbada Dhexe', 'Jubbada Hoose', 'Mudug', 'Nugaal', 'Sanaag', 'Shabeellaha Dhexe',
                 'Shabeellaha Hoose', 'Sool', 'Togdheer', 'Woqooyi Galbeed'],
    'KAZAKHSTAN': ['Almaty', 'Aqmola', 'Aqtobe', 'Astana', 'Atyrau', 'Batys Qazaqstan', 'Bayqongyr',
                    'Mangghystau', 'Ongtustik Qazaqstan', 'Pavlodar', 'Qaraghandy', 'Qostanay',
                    'Qyzylorda', 'Shyghys Qazaqstan', 'Soltustik Qazaqstan', 'Zhambyl'],
    'MALDIVES': ['Alifu Alifu', 'Alifu Dhaalu', 'Baa', 'Dhaalu', 'Faafu', 'Gaafu Alifu', 'Gaafu Dhaalu',
                  'Gnaviyani', 'Haa Alifu', 'Haa Dhaalu', 'Kaafu', 'Laamu', 'Lhaviyani', 'Mal\xe9',
                  'Meemu', 'Noonu', 'Raa', 'Seenu', 'Shaviyani', 'Thaa', 'Vaavu'],
    'MONTSERRAT': ['Saint Anthony', 'Saint Georges', "Saint Peter's"],
    'LATVIA': ['Aglona', 'Aizkraukle', 'Aizpute', 'Akn\u012bste', 'Aloja', 'Alsunga', 'Al\u016bksne',
                'Amata', 'Ape', 'Auce', 'Bab\u012bte', 'Baldone', 'Baltinava', 'Balvi', 'Bauska',
                'Bever\u012bna', 'Broc\u0113ni', 'Burtnieki', 'Carnikava', 'Cesvaine', 'Cibla',
                'C\u0113sis', 'Dagda', 'Daugavpils', 'Daugavpils (City)', 'Dobele', 'Dundaga', 'Durbe',
                'Engure', 'Garkalne', 'Grobi\u0146a', 'Gulbene', 'Iecava', 'Ik\u0161\u0137ile',
                'Il\u016bkste', 'In\u010dukalns', 'Jaunjelgava', 'Jaunpiebalga', 'Jaunpils', 'Jelgava',
                'Jelgava (City)', 'J\u0113kabpils', 'J\u0113kabpils (City)', 'J\u016brmala (City)',
                'Kandava', 'Koc\u0113ni', 'Koknese', 'Krimulda', 'Krustpils', 'Kr\u0101slava',
                'Kuld\u012bga', 'K\u0101rsava', 'Lielv\u0101rde', 'Liep\u0101ja', 'Limba\u017ei',
                'Lub\u0101na', 'Ludza', 'L\u012bgatne', 'L\u012bv\u0101ni', 'Madona', 'Mazsalaca',
                'M\u0101lpils', 'M\u0101rupe', 'M\u0113rsrags', 'Nauk\u0161\u0113ni', 'Nereta',
                'N\u012bca', 'Ogre', 'Olaine', 'Ozolnieki', 'Prei\u013ci', 'Priekule', 'Prieku\u013ci',
                'P\u0101rgauja', 'P\u0101vilosta', 'P\u013cavi\u0146as', 'Rauna', 'Riebi\u0146i', 'Roja',
                'Ropa\u017ei', 'Rucava', 'Rug\u0101ji', 'Rund\u0101le', 'R\u0113zekne',
                'R\u0113zekne (City)', 'R\u012bga', 'R\u016bjiena', 'Sala', 'Salacgr\u012bva', 'Salaspils',
                'Saldus', 'Saulkrasti', 'Sigulda', 'Skrunda', 'Skr\u012bveri', 'Smiltene', 'Stopi\u0146i',
                'Stren\u010di', 'S\u0113ja', 'Talsi', 'Tukums', 'T\u0113rvete', 'Vai\u0146ode', 'Valka',
                'Valmiera', 'Varak\u013c\u0101ni', 'Vecpiebalga', 'Vecumnieki', 'Ventspils',
                'Ventspils (City)', 'Vies\u012bte', 'Vi\u013caka', 'Vi\u013c\u0101ni', 'V\u0101rkava',
                'Zilupe', '\u0100da\u017ei', '\u0112rg\u013ci', '\u0136egums', '\u0136ekava'],
    'SLOVAKIA': ['Banskobystricky', 'Bratislavsky', 'Kosicky', 'Nitriansky', 'Presovsky', 'Trenciansky',
                  'Trnavsky', 'Zilinsky'],
    'GUYANA': ['Barima-Waini', 'Cuyuni-Mazaruni', 'Demerara-Mahaica', 'East Berbice-Corentyne',
                'Essequibo Islands-West Demerara', 'Mahaica-Berbice', 'Pomeroon-Supenaam', 'Potaro-Siparuni',
                'Upper Demerara-Berbice', 'Upper Takutu-Upper Essequibo'],
    'BELGIUM': ['Bruxelles-Capitale', 'R\xe9gion Flamande', 'R\xe9gion Walloni\xeb'],
    'IRAN, ISLAMIC REPUBLIC OF': ['Alborz', 'Ardab\u012bl', 'B\u016bshehr',
                                   'Chah\u0101r Ma\u1e29\u0101l va Bakht\u012b\u0101r\u012b',
                                   'E\u015ffah\u0101n', 'F\u0101rs', 'Golest\u0101n', 'G\u012bl\u0101n',
                                   'Hamad\u0101n', 'Hormozg\u0101n', 'Kerm\u0101n', 'Kerm\u0101nsh\u0101h',
                                   'Khor\u0101s\u0101n-e Jon\u016bb\u012b',
                                   'Khor\u0101s\u0101n-e Ra\u1e95av\u012b',
                                   'Khor\u0101s\u0101n-e Shom\u0101l\u012b', 'Kh\u016bzest\u0101n',
                                   'Kohg\u012bl\u016byeh va Bowyer A\u1e29mad', 'Kordest\u0101n',
                                   'Lorest\u0101n', 'Markazi', 'M\u0101zandar\u0101n', 'Qazv\u012bn', 'Qom',
                                   'Semn\u0101n', 'S\u012bst\u0101n va Bal\u016bchest\u0101n', 'Tehr\u0101n',
                                   'Yazd', 'Zanj\u0101n', '\u0100z\u0304arb\u0101yj\u0101n-e Gharb\u012b',
                                   '\u0100z\u0304arb\u0101yj\u0101n-e Sharq\u012b', '\u012al\u0101m'],
    'GUAM': ['Guam'],
    'AMERICAN SAMOA': ["Aunu'u", 'Ofu\u2011Olosega', 'Rose Atoll', 'Swains Island', "Ta'\u016b",
                        'Tutuila'],
    'MAURITIUS': ['Agalega Islands', 'Beau Bassin-Rose Hill', 'Black River', 'Cargados Carajos Shoals',
                   'Curepipe', 'Flacq', 'Grand Port', 'Moka', 'Pamplemousses', 'Plaines Wilhems',
                   'Port Louis', 'Port Louis (City)', 'Riviere du Rempart', 'Rodrigues Island', 'Savanne',
                   'Vacoas-Phoenix'],
    'LIECHTENSTEIN': ['Balzers', 'Eschen', 'Gamprin', 'Mauren', 'Planken', 'Ruggell', 'Schaan',
                       'Schellenberg', 'Triesen', 'Triesenberg', 'Vaduz'],
    'NAMIBIA': ['Erongo', 'Hardap', 'Karas', 'Kavango East', 'Kavango West', 'Khomas', 'Kunene',
                 'Ohangwena', 'Omaheke', 'Omusati', 'Oshana', 'Oshikoto', 'Otjozondjupa', 'Zambezi'],
    'TAJIKISTAN': ['Dushanbe', 'Khatlon', 'K\u016dhistoni Badakhshon', 'Sughd'],
    'GREECE': ['Anatolik\xed Makedon\xeda kai Thr\xe1ki', 'Attik\u1e2f', 'Dytik\xed Ell\xe1da',
                'Dytik\xed Makedon\xeda', 'Ion\xeda N\xedsia', 'Kentrik\xed Makedon\xeda', 'Kr\xedt\xed',
                'Not\xedo Aiga\xedo', 'Peloponn\xedsos', 'Stere\xe1 Ell\xe1da', 'Thessal\xeda',
                'Vore\xedo Aiga\xedo', '\xc1gion \xd3ros', '\xcdpeiros'],
    'BELIZE': ['Belize District', 'Cayo District', 'Corozal District', 'Orange Walk District',
                'Stann Creek District', 'Toledo District'],
    'GREENLAND': ['Kommune Kujalleq', 'Kommuneqarfik Sermersooq', 'Qaasuitsup Kommunia',
                   'Qeqqata Kommunia'],
    'TUNISIA': ['Ariana', 'Beja', 'Ben Arous', 'Bizerte', 'Gabes', 'Gafsa', 'Jendouba', 'Kairouan',
                 'Kasserine', 'Kebili', 'Kef', 'Mahdia', 'Medenine', 'Monastir', 'Nabeul', 'Sfax',
                 'Sidi Bouzid', 'Siliana', 'Sousse', 'Tataouine', 'Tozeur', 'Tunis', 'Zaghouan'],
    'KOREA, REPUBLIC OF': ["Ch'ungch'ongbuk-do", "Ch'ungch'ongnam-do", 'Cheju-do', 'Chollabuk-do',
                            'Chollanam-do', "Inch'on-Kwangyokhi", 'Kang-won-do', 'Kwangju-Kwangyokshi',
                            'Kyonggi-do', 'Kyongsangbuk-do', 'Kyongsangnam-do', 'Pusan-Kwangyokshi',
                            'Sejong', "Seoul-T'ukpyolshi", 'Taegu-Kwangyokshi', 'Taejon-Kwangyokshi',
                            'Ulsan-Kwangyokshi'],
    'LUXEMBOURG': ['Capellen', 'Clevaux', 'Diekirch', 'Echternach', 'Esch-sur-Alzette', 'Grevenmacher',
                    'Luxembourg', 'Mersch', 'Redange', 'Remich', 'Vianden', 'Wiltz'], 'MACAO': ['Macao'],
    'ISLE OF MAN': ['Isle of Man'],
    'MAURITANIA': ['Adrar', 'Assaba', 'Brakna', 'Dakhlet Nouadhibou', 'Gorgol', 'Guidimaka',
                    'Hodh Ech Chargui', 'Hodh El Gharbi', 'Inchiri', 'Nouakchott Nord', 'Nouakchott Ouest',
                    'Nouakchott Sud', 'Tagant', 'Tiris Zemmour', 'Trarza'],
    'FINLAND': ['Ahvenanmaan l\xe4\xe4ni', 'Etel\xe4-Suomen l\xe4\xe4ni', 'It\xe4-Suomen l\xe4\xe4ni',
                 'Lapin l\xe4\xe4ni', 'L\xe4nsi-Suomen l\xe4\xe4ni', 'Oulun l\xe4\xe4ni'],
    'JORDAN': ["Al 'Aqabah", 'Al Balq\u0101\u2019', 'Al Karak', 'Al Mafraq', 'Al \u2018A\u0305\u015fimah',
                'Az Zarq\u0101\u2019', 'A\u0163 \u0162af\u012blah', 'Irbid', 'Jarash', 'Ma\u2018\u0101n',
                'M\u0101dab\u0101', '\u2018Ajl\u016bn'], 'SINT MAARTEN (DUTCH PART)': ['Sint Maarten'],
    'TURKEY': ['Adana', 'Adiyaman', 'Afyonkarahisar', 'Agri', 'Aksaray', 'Amasya', 'Ankara', 'Antalya',
                'Ardahan', 'Artvin', 'Aydin', 'Balikesir', 'Bartin', 'Batman', 'Bayburt', 'Bilecik',
                'Bingol', 'Bitlis', 'Bolu', 'Burdur', 'Bursa', 'Canakkale', 'Cankiri', 'Corum',
                'Denizli', 'Diyarbakir', 'Duzce', 'Edirne', 'Elazig', 'Erzincan', 'Erzurum', 'Eskisehir',
                'Gaziantep', 'Giresun', 'Gumushane', 'Hakkari', 'Hatay', 'Igdir', 'Isparta', 'Istanbul',
                'Izmir', 'Kahramanmaras', 'Karabuk', 'Karaman', 'Kars', 'Kastamonu', 'Kayseri', 'Kilis',
                'Kirikkale', 'Kirklareli', 'Kirsehir', 'Kocaeli', 'Konya', 'Kutahya', 'Malatya',
                'Manisa', 'Mardin', 'Mersin', 'Mugla', 'Mus', 'Nevsehir', 'Nigde', 'Ordu', 'Osmaniye',
                'Rize', 'Sakarya', 'Samsun', 'Sanliurfa', 'Siirt', 'Sinop', 'Sirnak', 'Sivas',
                'Tekirdag', 'Tokat', 'Trabzon', 'Tunceli', 'Usak', 'Van', 'Yalova', 'Yozgat',
                'Zonguldak'], 'SAO TOME AND PRINCIPE': ['Principe', 'Sao Tome'],
    'TURKMENISTAN': ['Ahal', 'Asgabat', 'Balkan', 'Dashoguz', 'Lebap', 'Mary'],
    'MYANMAR': ['Ayeyarwady', 'Bago', 'Chin', 'Kachin', 'Kayah', 'Kayin', 'Magway', 'Mandalay', 'Mon',
                 'Nay Pyi Taw', 'Rakhine', 'Sagaing', 'Shan', 'Tanintharyi', 'Yangon'],
    'URUGUAY': ['Artigas', 'Canelones', 'Cerro Largo', 'Colonia', 'Durazno', 'Flores', 'Florida',
                 'Lavalleja', 'Maldonado', 'Montevideo', 'Paysand\xfa', 'Rivera', 'Rocha', 'R\xedo Negro',
                 'Salto', 'San Jos\xe9', 'Soriano', 'Tacuaremb\xf3', 'Treinta y Tres'],
    'PANAMA': ['Bocas del Toro', 'Chiriqu\xed', 'Cocl\xe9', 'Col\xf3n', 'Dari\xe9n', 'Ember\xe1',
                'Herrera', 'Kuna Yala', 'Los Santos', 'Ng\xe4be-Bugl\xe9', 'Panam\xe1', 'Panam\xe1 Oeste',
                'Veraguas'],
    'CHILE': ['Ais\xe9n del General Carlos Ib\xe1\xf1ez del Campo', 'Antofagasta', 'Araucan\xeda',
               'Arica y Parinacota', 'Atacama', 'B\xedo-B\xedo', 'Coquimbo',
               "Libertador General Bernardo O'Higgins", 'Los Lagos', 'Los R\xedos',
               'Magallanes y Antartica Chilena', 'Marga-Marga', 'Maule',
               'Regi\xf3n Metropolitana de Santiago', 'Tarapac\xe1', 'Valpara\xedso'],
    'HAITI': ['Artibonite', 'Centre', "Grand'Anse", 'Nippes', 'Nord', 'Nord-Est', 'Nord-Ouest', 'Ouest',
               'Sud', 'Sud-Est'],
    'CAMEROON': ['Adamaoua', 'Centre', 'Est', 'Extr\xeame-Nord', 'Littoral', 'Nord', 'Nord-Ouest',
                  'Ouest', 'Sud', 'Sud-Ouest'],
    'BULGARIA': ['Blagoevgrad', 'Burgas', 'Dobrich', 'Gabrovo', 'Jambol', 'Khaskovo', 'Kjustendil',
                  'Kurdzhali', 'Lovech', 'Montana', 'Pazardzhik', 'Pernik', 'Pleven', 'Plovdiv',
                  'Razgrad', 'Ruse', 'Shumen', 'Silistra', 'Sliven', 'Smoljan', 'Sofija', 'Sofija-Grad',
                  'Stara Zagora', 'Turgovishhe', 'Varna', 'Veliko Turnovo', 'Vidin', 'Vraca']
}
