# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-10 13:40


from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import misc.fields
import model_utils.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('dynforms', '0001_initial'),
        ('proposals', '0001_initial'),
        ('beamlines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False,
                                                                verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False,
                                                                      verbose_name='modified')),
                ('details', misc.fields.JSONField(blank=True, default={}, editable=False, null=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('beamline',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback',
                                   to='beamlines.Facility')),
                ('cycle',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback',
                                   to='proposals.ReviewCycle')),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynforms.FormSpec')),
            ],
            options={
                'ordering': ['beamline__acronym'],
            },
        ),
    ]
