# Generated by Django 5.0.9 on 2024-11-14 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_feedback_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='details',
            field=models.JSONField(blank=True, default=dict, editable=False, null=True),
        ),
    ]
