# Generated by Django 5.2.6 on 2025-09-08 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_alter_feedback_created_alter_feedback_modified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-created']},
        ),
    ]
