# Generated by Django 5.2.4 on 2025-09-09 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_alter_feedback_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('value', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ratings', to='surveys.category')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='surveys.feedback')),
            ],
            options={
                'indexes': [models.Index(fields=['feedback', 'category'], name='surveys_rat_feedbac_ad51a7_idx')],
                'unique_together': {('feedback', 'category', 'name')},
            },
        ),
    ]
