# Generated by Django 5.0.9 on 2024-11-30 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_feedback_form_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='spec',
        ),
    ]
